### ISSUE TITLE
Having issue with tabbing.

### ISSUE THREAD

**Issue by tbone21w** [isteven/angular-multi-select#109]
I'm having trouble with tabbing.  When I set tab order on my form the multi-select is not behaving correctly.   I created a fiddle to demo this, http://jsfiddle.net/teisaacs21w/vz4dg79u/

If tabbing in tab order (using tabindex) the muliti-select does tab and get focus but hitting spacebar does not select because the <span> has focus not the button.  For example, in fiddle start on the first field and tab twice and notice that the multi-select is tabbed to and focus is set.  Now hit space bar and notice the control does not open.

If default tabbing is used (items that have no tab index) this control works fine.  Also, notice how the multi-select is picked up twice when we continue to tab.  For  example in the fiddle start a the first field and tab 5 times and notice how the multi-select is picked up twice.

Also, ESC does not retain focus on the multi-select and mouse down external does not retain focus so the result is the user starts over on tab order.

I created a workaround but it has some issues. http://jsfiddle.net/teisaacs21w/vz4dg79u/1/ .  is this something you have worked on or have ideas how to best fix?

Todd

**Comment by chocobidou** [comment]
Hi, is that answer is always good ? I'm looking for changing the template but it's not working.
