### ISSUE TITLE
e.target.className.indexOf is undefined if target is svg element

### ISSUE THREAD

**Issue by Hypercubed** [isteven/angular-multi-select#11]
I needed to change line #L447 (https://github.com/isteven/angular-multi-select/blob/master/angular-multi-select.js#L447) because clicking on a svg element was not working as expected.

```
if ( e.target.className.indexOf === undefined || e.target.className.indexOf( 'multiSelect' ) === -1 ) {
```

**Comment by sandun86** [comment]
Turns out the issue is due to Google's Translate extension. Disabling it solve the problem.

**Comment by mattferrin** [comment]
@sandun86 Thanks.

**Comment by ztischenkosilobreaker** [comment]
I had the same issue with 'use' tags that we use inside 'svg' tags. To fix this error you can extend SVGAnimatedString prototype (as this is a type that className property returns in this case - apparently it does not have indexOf method, hence the unhandled exception), like this:

```
(SVGAnimatedString.prototype as any).indexOf = (() => {
    return function() {
        return this.baseVal.indexOf.apply(this.baseVal, arguments);
    };
})();
```
Once you drop this inside root directory of your app, the issue will be resolved as now your 'use' tags (or any other tag that returns type SVGAnimatedString type, rather then string, for className property of the node element) will have indexOf method. 

In my case adding 'notranslate' to each svg was not best solution as on the page there was a lot of svgs added at different times by different components. 

Hope it will help someone out there as well.
