### ISSUE TITLE
Grouping items in dropdown

### ISSUE THREAD

**Issue by NiteshSaxena** [isteven/angular-multi-select#114]
How can I group the items in dropdown using a property.

example: I have a input-model:
$scope.modernWebBrowsers = [
    {  name: "Opera",  type: "modern",  ticked: true  },
    {  name: "Internet Explorer", type: "modern",  ticked: false },
    {  name: "Firefox", type: "modern", ticked: true  },
    {  name: "Netscape Navigator", type: "classic", ticked: false },
    {  name: "Amaya", type: "classic", ticked: true  }
]; 

What I need is to group the items using property 'type'.
Will really appreciate your help.

**Comment by akshay-bbytes** [comment]
Group by issue in version 1.11.8

JS Code :
> $scope.selectByGroupData = [ 
> { id: 1, label: "David", gender: 'M' }, 
> { id: 2, label: "Jhon", gender: 'M' },
> { id: 3, label: "Lisa", gender: 'F' }, 
> { id: 4, label: "Nicole", gender: 'F' }, 
> { id: 5, label: "Danny", gender: 'M' }, 
> { id: 6, label: "Unknown", gender: 'O' } ]; 
> $scope.selectByGroupSettings = {
>           groupBy: 'gender',
> };

HTML:
```
<div ng-dropdown-multiselect="" options="selectByGroupData" selected-model="genderCollection" extra-settings="selectByGroupSettings">
                                    </div>
```
I tried by adding groupby attribute in html block also could not worked :(
Above code group by not working or if I'm missing something not sure
Please help asap
Thanks in advance..!!
