### ISSUE TITLE
Nested object data not rendering

### ISSUE THREAD

**Issue by zyadsherif** [isteven/angular-multi-select#120]
I am using the Multi Select with an object that has nested objects like so 

``` json
assignee:[
      {
        id:
        name:
          {
            id:
            name:
            email:
          }
        value:
      }
    ]
```

But the 2nd level data isn't displayed, only the top level data, any thoughts on this?

**Comment by HarelM** [comment]
To any one who read this in order to get the angular-gravatar working inside the multi-select (after wasting a few hours):
Html:
```html
<div name="name" isteven-multi-select
    input-model="input"
    output-model="output"
    button-label="icon name"
    item-label="icon name"
    tick-property="ticked">
</div>
```
controller code (assuming you injected to the controller the gravatarService:
```js
...
icon: "<img src='" + gravatarService.url(email) + "' width='24px' height='24px' />"
```
