### ISSUE TITLE
How to clear selected items?

### ISSUE THREAD

**Issue by mfields106** [isteven/angular-multi-select#154]
I would think that if you cleared the output model then the selected items would also be cleared like any other solution. Can you please provide a means to clear all selected items via Javascript

**Comment by naveenchander1909** [comment]
Hi @isteven,
      i have similar issue my question is you have written:
   "// Let's say this is your input model, and select property is 'ticked';" 
what is 'ticked ' here can u explain or show a fiddle for this?
