### ISSUE TITLE
How to write a function while clicking on Select All or Select None. This function i want to access in my controller.

### ISSUE THREAD

**Issue by rangareddy** [isteven/angular-multi-select#159]
Hi you have implemented function while click on item, in the same way i want one function while click on Select All or Select None. It is possibel.

**Comment by isteven** [comment]
Well yes, it's possible.

**Comment by rangareddy** [comment]
Can you add functionality for that one..

**Comment by isteven** [comment]
Will have it on v3.0.0, which is.. still on progress, sorry.
