### ISSUE TITLE
Button labels

### ISSUE THREAD

**Issue by MrS1lentcz** [isteven/angular-multi-select#160]
Hello, this library is actually usable only for english speakers because button labels cannot be changed. Could you add some options for custom button labels please? It is not very pretty to have mixed languages in one project...

**Comment by isteven** [comment]
Hi @MrS1lentcz,

They will be changeable on v3.0.0, however I'm stuck with other things at the moment.

If you want to, you can open the source code and modify the button language yourself.

You can also find some pull requests in this repo which deal with such language options.
