### ISSUE TITLE
Choose inputModel attributes to perform the search on

### ISSUE THREAD

**Issue by juanjmostazo** [isteven/angular-multi-select#161]
Hi,

First, congrats for the widget. I think it's an awesome library which I added to my project, pretty flexible and easy to use :)

However, I'm missing something that I think it's useful and makes me have extra data structures in my code. Sometimes you may want to perform search on only certain attributes, because you may hide some of them to the users, although you still want to use them internally for some other purposes.

For example, imagine you have a list of friends, each one containing a name and a numeric id. If you use that list as an input model for your widget and you type some numbers in the input search, it will search for the id of the friend, although you may be interested in hiding those ids to the users, letting them only search for names.

Ideally, this could be an extra parameter for the directive, something like:
search-field="XXX YYY ZZZ"
where XXX, YYY, ZZZ are the attributes that you want to use in the search.

What do you think? Thanks!

**Comment by isteven** [comment]
Hi @juanjmostazo , 

Thanks, glad that you like the directive.  Unfortunately it won't be easy to incorporate such search search-field feature. Perhaps in the future release.
