### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mfields106** [isteven/angular-multi-select#162]
After a long search I have identified this control as having a significant memory leak. When these controls are inside an ng-switch, each switch does not clear the memory. Lots of detached DOM trees.

Please let me know more information you need to troubleshoot this.

**Comment by isteven** [comment]
I'm aware the memory leaks, but can you show some sample scenarios on Fiddler or Plunker? That would be very helpful. Thanks.

**Comment by mfields106** [comment]
I will try to put it in fiddler, but my app is a bit complex with dynamic configuration ect.

I am curious. Have you considered connecting with the Angular guys on wether what you have built is the right approach.  I am now a bit concerned about components that are 100% angular. Taking concepts such as scope to a level of repitition that may not have been considered. It is one thing to use ng-repeat 100 times on one page but 1000 times?

**Comment by isteven** [comment]
If it's difficult to re-produce, perhaps you can at least try to locate the problem in the code, or give me some suggestions to fix it. 

I'm not really in touch with AngularJS guys.. not sure if they have resource to liaise & check 3rd party components like this one. I imagine if all 3rd party AngularJS component developers engage them and.. I guess there will be a sudden overload of to-dos for the AngularJS guys :)

It is well known that AngularJS is not the most resource-friendly framework. It's there to make developers' live easier, but there will always be some consequences. 

I admit that this directive is not optimized for such big amount of data (you're not the first to upload 1000++ data into it, btw) - however I am trying to find work around, for example, by using lazy-loading for it - it will be available on the next release.
