### ISSUE TITLE
Template parameter

### ISSUE THREAD

**Issue by bsides** [isteven/angular-multi-select#165]
Hi!,

I would like to be able to not change the template in your source directly. I'd rather indicate another file for the template. Is it possible?

Thank you

Edit: it's mostly to update the locales since the main language of the system I'm building isn't english. In [UI-BOOTSTRAP](https://github.com/angular-ui/bootstrap/wiki/FAQ) they use a very interesting tecnique of registering the templates in a variable, then I can just replace that with my templates. Would that be possible?

**Comment by isteven** [comment]
Hello, 

At the moment it is not possible. There are various Pull Requests which give you the ability to use different language in the buttons. You can also modify the template code directly.

**Comment by isteven** [comment]
Another thing is that I try not to trigger any extra http request.

This is why I don't really prefer to use a separate html file for the template.

**Comment by bsides** [comment]
You don't need another http request if your html template files are compiled in the same Javascript file with $templateCache. This is what I do at least, put them all in one giant Javascript file and then it will be loaded only once - and they can live with the same old js files with concat job. In fact that makes directives so modular and better that I believe it was made by UI-BOOTSTRAP team because of it. Thanks for the input though.

**Comment by isteven** [comment]
@bsides , 

I am considering this..

**Comment by tomaszkrym** [comment]
I think this is resolved by #198 and duplicates #197.

**Comment by bsides** [comment]
@isteven please remind me next week to help you with that. I have an example ready for you, but I'm not near the files this week.

**Comment by isteven** [comment]
Hi @bsides , 

No worry, @tomaszkrym already provided a Pull Request & it has been merged.

**Comment by bsides** [comment]
Oh nice! Thank you all :+1:
