### ISSUE TITLE
The small screen width support and the vertical display why not in the parent control inside

### ISSUE THREAD

**Issue by liulipengju** [isteven/angular-multi-select#166]
1. On the uiview inside, into the small screen without scrolling (left-right)
2. Vertical display double-click display a dropdown list not in parent space inside.
3.Can not provide about box shows you choose, left, on the right shows, the drop-down list does not display

**Comment by isteven** [comment]
Hi @liulipengju , 

I'm sorry but I don't think I understand the problem. Can you give a more detailed explanation? Please try to replicate the problem in Plunker or JSFiddler.

**Comment by liulipengju** [comment]
1 I show a page in U-VIEW.

2 on the page I wrote a FORM

3 in this FORM and I wrote a tabset

4 in this tabset and I wrote a multi-select.

5 this multi-select write in the bottom of the page.

6 when you click this multi-select is displayed after a drop-down list.

7 but this multi-select is absolutely positioned, cause its not shown in my FORM inside, because the drop-down list is very long, has blocked the submit button.

**Comment by liulipengju** [comment]
1. the browser pull the narrowest.

2.multi-select is the absolute positioning.

3 no scroll bars, contents of drop-down option width after 220px are not displayed.

4 or above me that question, Still covering my submit button, although I set max-height, let it have the scroll bar, because of No.3---- I couldn't see the drop-down scroll bar, I totally can not use.

**Comment by liulipengju** [comment]
Can not provide this functionality,
Multi-option is not a drop-down list,
It appears as: a left panel, the right of a panel, in the middle of the two panel provides buttons (← & →), the fixed display options on the left of this panel, will select items displayed in the right panel, right-hand side panel of elected an item and click ←, will remove choices like the opposite.

select2 had but not suppert ng-model.

**Comment by isteven** [comment]
@liulipengju , 

Can you please replicate the problem in JsFiddler or Plunker? 

For the <- and -> thing, you'd need something like this: http://jsfiddle.net/4zt4k5er/

**Comment by liulipengju** [comment]
please see 
http://plnkr.co/edit/?p=streamer&s=fNHn3tdzWczYJxFQ
1. run index.html
2. click  系统管理 -> 群组管理
3. dblclick  one record will display detial info
4.select one tab click multi select

**Comment by isteven** [comment]
OK.. I have followed the steps and this is what I see:

![multiselect](https://cloud.githubusercontent.com/assets/5432100/5735132/2cab930c-9bfc-11e4-9761-68c4b920e023.jpg)


1) Multiselect is absolutely positioned. Yes, it blocks the submit button, but that is the default behaviour of these kind of dropdowns. Even normal HTML dropdown will also block the submit button.

If you don't believe me, try to create a long list using the usual 

    <select>
        <option>Value 1</option>
        <option>Value 2</option>
        ....
        <option>Value 50</option>
    </select>
    <br />
    <input type="submit" value="Submit" />

I am sure the dropdown list will block the submit button as well.

2) It was not designed with horizontal scrollbar. However, you can easily add a horizontal scrollbar by modifying the CSS.

**Comment by liulipengju** [comment]
ok. i will trying. thank you.
