### ISSUE TITLE
set  output-model and select option but at controller not value

### ISSUE THREAD

**Issue by liulipengju** [isteven/angular-multi-select#167]
<div
 multi-select
 input-model="systemRightInit"
 output-model="systemRightSelect"
 button-label="name"
 item-label="name maker"
 tick-property="ticked"
>
</div>
<p>{{systemRightSelect}}</p>

when select option,  <p>had value

but at controller  the $scope.systemRightSelect is [] ,  null  why?

**Comment by liulipengju** [comment]
see http://plnkr.co/edit/?p=streamer&s=fNHn3tdzWczYJxFQ 
 at  app.js  --> $scope.modifyGroup () --> add alert($scope.systemRightSelect.length)   
1. run index.html
2. click 系统管理 -> 群组管理
3. click  添加 or dblclick one record and select option  and submit will alert 0
why?

**Comment by liulipengju** [comment]
![system](https://cloud.githubusercontent.com/assets/10510950/5739463/c2299e28-9c34-11e4-932a-6ce3af2704b2.png)

**Comment by isteven** [comment]
Hi @liulipengju , 

I see nothing when I click "Run" button on the fiddler. Perhaps you didn't save the fiddler properly? 

![multiselect](https://cloud.githubusercontent.com/assets/5432100/5752026/8ff16016-9ca8-11e4-9030-7e98ebc35060.jpg)

**Comment by liulipengju** [comment]
You see my screenshot yet

**Comment by liulipengju** [comment]
if you need i will re-deal the projeck at plunker.

**Comment by isteven** [comment]
Hi @liulipengju , 

Yes I've seen your screenshot, but there's nothing I can do just by looking at a screenshot. I also need to see your code so that I can help you.

**Comment by liulipengju** [comment]
ok, i will re-deal  ok. you can look  http://plnkr.co/edit/?p=preview&s=fNHn3tdzWczYJxFQ
.thank you.

**Comment by liulipengju** [comment]
sorry . please wait.

**Comment by liulipengju** [comment]
sorry . juct had a question.  now is ok.

please lock http://plnkr.co/edit/?p=streamer&s=zRdMrMrkbYh5Krqe
run it.
please , thanks.

**Comment by isteven** [comment]
Hi @liulipengju , 

After looking at your code, my initial suspect is, there's a conflict with angular-ui. 

Try to remove the angular-ui JS from your HTML page and refresh the Plunker. It worked when I tried.

**Comment by liulipengju** [comment]
you mean
this ui-bootstrap-tpls-0.12.0.js or angular-ui-router.min.js ？
but my project used use it.

**Comment by isteven** [comment]
The ui-bootstrap-tpls-0.12.0.js. 

I'm not sure about the solution, I never encountered this problem before.

**Comment by liulipengju** [comment]
oh, You continue to study, I will use the initialization module deal.

**Comment by isteven** [comment]
As in.. I am not able to help you on this error. 

My suggestion is, either you use my solution, or you use the angular-ui's solution. Which one is up to you.

**Comment by liulipengju** [comment]
oh, You continue to study, I will use the initialization module deal.

**Comment by liulipengju** [comment]
if had any msg please tell me, thank you very much.

**Comment by liulipengju** [comment]
if had any msg please tell me, thank you very much.
