### ISSUE TITLE
on-item-click not passing all data

### ISSUE THREAD

**Issue by grosch** [isteven/angular-multi-select#169]
When the on-item-click is called for a group=true type element, you see to just pass the group item, but not all the sub-items.  I need to know whether those are turned on or off as well...i.e. I don't want to hardcode the values back in again.

**Comment by isteven** [comment]
Hi @grosch , 

It's by design. The on-item-callback only returns the thing that you clicked. 

You can simply do a loop on the input-model during on-item-click() callback to check whether the sub-items are on or off.
