### ISSUE TITLE
Clear selection through controller.

### ISSUE THREAD

**Issue by deepakbhattarai** [isteven/angular-multi-select#170]
There is a select none button on the view and it calls select('none', $event) . How do I call this on controller?

**Comment by isteven** [comment]
Hi @deepakbhattarai , 

If you want to select none from your controller, simply loop your input-model and set all the check mark into false.

Let's say your input-model is $scope.data, and the check property is "ticked", then:

    ....
    angular.forEach( $scope.data, function( value, key ) {
        value.ticked = false;        
    }
    ....

**Comment by deepakbhattarai** [comment]
@isteven  Thank you very much. I didn't think that way first.
