### ISSUE TITLE
output model as object

### ISSUE THREAD

**Issue by poornimaarun** [isteven/angular-multi-select#171]
I dont need tick-property as true or false.It's output model is as Array.For ex,
NAME:[{"id":"1","name":"Rajesh","selected":true}].
But I need only id.For ex:
NAME:[{1}]

And moreover the input model consists of both id and name.Kindly reply me as soon as possible.

**Comment by isteven** [comment]
Hi @poornimaarun , 

The tick-property is intended to be boolean true or false. 

Output-model is also intended to be array of object. To get the ID, you can simply easily use something like.. NAME.id, am I correct?

**Comment by poornimaarun** [comment]
Thank you very much for your reply.
