### ISSUE TITLE
how to hide the reset button from the multiselect dropdown ?

### ISSUE THREAD

**Issue by sagarwasule** [isteven/angular-multi-select#172]
i don't need reset button as by default there will be no pre filled values selected in this dropdown

**Comment by isteven** [comment]
Hi @sagarwasule, please read the manual. You can hide (or display) any button combinations that you want.

**Comment by nhatnguyen26** [comment]
hey @sagarwasule, did you actually find it out? I am looking in the manual but seem I am missing thing again
