### ISSUE TITLE
on-close event got error with angularjs 1.3

### ISSUE THREAD

**Issue by truonghoangnguyen** [isteven/angular-multi-select#173]
hi
My app using 

                            `<div multi-select
                                input-model="domains"
                                button-label="title"
                                item-label="title"
                                tick-property="checked"
                                on-close="$scope.getLabels( data )"
                                >
                            </div>`

and error:

Uncaught Error: [$parse:isecdom] Referencing DOM nodes in Angular expressions is disallowed! Expression: $scope.getLabels( data )
http://errors.angularjs.org/1.3.9/$parse/isecdom?p0=%24scope.getLabels(%20data%20)

Note: angularjs 1.2.x work OK

**Comment by isteven** [comment]
https://github.com/isteven/angular-multi-select/issues/156
