### ISSUE TITLE
No notification when "Select None" button clicked.

### ISSUE THREAD

**Issue by grosch** [isteven/angular-multi-select#174]
How do I get a notification when they use the select none button?  I have to disable all my filters at that point.

**Comment by isteven** [comment]
Hi @grosch , 

At the moment there's no callback on the buttons. Will be adding them on next release.

**Comment by grosch** [comment]
Do you have an ETA?  My boss is giving me grief about this and the other case I opened where the "button" loses the label once you select things.

**Comment by isteven** [comment]
Unfortunately no. 

For the extra text on the button, perhaps you can see this PR: https://github.com/isteven/angular-multi-select/pull/95/files. Find the changes and copy them manually into the code. 

(Sorry for closing that issue, I have a habit of closing issues that's left for more than certain days without further comments by the users)
