### ISSUE TITLE
Refresh data

### ISSUE THREAD

**Issue by joaquinmautone** [isteven/angular-multi-select#175]
Hi, im sorry for my basic english. I have a problem with a multi-select grouping. 

The clear button dont work, and when i click on a group item, their children are not selected, only the first item; but when i click in the clear button of the search, everything is fixed.

It is possible to call methods prepareGrouping and prepareIndex after load the input-model?

thx!

**Comment by isteven** [comment]
Hi @joaquinmautone , 

Can you replicate this problem in JsFiddler or Plunker (or any other online JS collaboration tool)?

**Comment by joaquinmautone** [comment]
I solved the problem!

I needed to initialize the $scope variable into the $http.get function:

$scope.items = [ ];
$http.get('/GetData').success(function(data) {
    **$scope.items = [ ];**
    $scope.items = data;
  });

thanks for you fantastic work!

**Comment by isteven** [comment]
Hi @joaquinmautone , 

You've done the right thing there, - you initiate the directive with an empty array instead of null. But perhaps you'd want to use angular.copy on that data instead.

Anyway, since it's solved, I'm going to close this issue then :)
