### ISSUE TITLE
Go by link inside dropdown list

### ISSUE THREAD

**Issue by conmute** [isteven/angular-multi-select#176]
Just add this line after 261 line:
(after code: `$scope.syncItems = function( item, e, ng_repeat_index ) {`)

```javascript
if (e.target.tagName === 'A') {
     return;
}
```

**Comment by isteven** [comment]
Hi @conmute , 

I'm sorry I didn't really get you here. 

What is your problem? How can I help you?

**Comment by conmute** [comment]
I wanted links in dropdown list (when selecting, no viewing already selected) to be workable (like click and go somewhere else). When i am clicking to select one of item, it will select it, and will override link behaviour.

So this code prevents further processing if click event was fired on `a` (anchor) element.

**Comment by isteven** [comment]
Oh I see. So this is an input, not an issue. 

Thanks for the input @conmute, I will refer this issue when the others ask.

**Comment by conmute** [comment]
Awesome! Thank you too! You do really nice maintaining, i get a respond from you very fast.

**Comment by isteven** [comment]
No problem, happen to be in front of my PC now :)

Since it's not really a problem, do you mind if I close this issue?

**Comment by conmute** [comment]
Sure
