### ISSUE TITLE
Weird Issue with double event fire.

### ISSUE THREAD

**Issue by RichLinnell** [isteven/angular-multi-select#177]
Top work with the directive, very nice n easy to use.

I had a weird issue with the control firing the click event twice.  This effectively checked and then immediately unchecked the the selected Item. 

I'm not 100% sure why, it may be something to do with Unions, but who knows.  

I got around this by making a very small modification to the `$scope.syncItems` procedure in your directive thus:

`$scope.syncItems = function( item, e, ng_repeat_index) {`
`                if (e.processed) return;`
`                e.processed = true;`
`                e.preventDefault();`
`                e.stopPropagation();`
`                ...`

Obviously a further investigation into why the event is triggering twice might be a more professional approach, but I just need to get my code out, so this will suffice for me.

**Comment by isteven** [comment]
Thanks for letting me know. I have heard similar stuffs happened with Batarang, so perhaps it's similar with your case.

**Comment by RichLinnell** [comment]
No problem. The workaround works perfectly. Feel free to use it - It's a pretty certain catchall.






Sent from Surface





From: Steven
Sent: ‎Monday‎, ‎2‎ ‎February‎ ‎2015 ‎07‎:‎43
To: isteven/angular-multi-select
Cc: Richard Linnell





Thanks for letting me know. I have heard similar stuffs happened with Batarang, so perhaps it's similar with your case.

**Comment by schrink** [comment]
I have the same issue.

**Comment by isteven** [comment]
Monitoring this.. anyone can help to replicate the issue?
