### ISSUE TITLE
Reset the selection in JS

### ISSUE THREAD

**Issue by deejaygeekout** [isteven/angular-multi-select#179]
I'm trying to implement it  in a clear button. I can't find a way. 

So I have a clear button in my parent view. when I click it, it will reset all the angular multi select directives. Better if there's a broadcast implementation so in just one line, everything will be cleared. 

Thanks!

**Comment by isteven** [comment]
Hi,

Just loop over the input model using angular.forEach, and like within that loop.. selected = false?

**Comment by deejaygeekout** [comment]
Oh! That's pretty neat trick since it is binded. Got it working! thanks! :)

**Comment by isteven** [comment]
No problem.

It's not a trick.. read more about AngularJs ng-model and bindings. Perhaps you're missing some great features you don't realize.
