### ISSUE TITLE
Usage of !important values prevents custom styling.

### ISSUE THREAD

**Issue by vproman** [isteven/angular-multi-select#181]
I'm trying to size the height of the select to fit the rest of my form fields, but because of this !important I'm unable to override the style without adding an !important myself.  I'm wondering if these !important flags were just used as quick fixes to get the styling correct?  Was there another reason to use them?

I'd like to help clean up the CSS so they important values not necessary, but I don't want to do so if there was a special reason they were used.

**Comment by isteven** [comment]
Hi @vproman, 

The !importants are used to override other !importants items that might (and usually) arise in other CSS libraries. 

Feel free to clean up the CSS (and do test combining them with other CSS libs). A Pull Request then would be very appreciated.
