### ISSUE TITLE
cannot set property "ticked"

### ISSUE THREAD

**Issue by cornelinux** [isteven/angular-multi-select#183]
Thanks a lot for this directive.

I am using the directive like this:

controller:

    $scope.scopes = [{name: "scope1", marked: "scope1", ticked: false}, ... ]

the view:

    <div multi-select
                 input-model="scopes"
                 output-model="selectedScope"
                 button-label="icon name"
                 item-label="icon name maker"
                 tick-property="ticked"
                 selection-mode="single"
                    >
            </div>

In the chrome console I get the error:
Cannot set property 'ticked' of undefined
    at Scope.link.$scope.syncItems (http://localhost:5000/static/contrib/js/angular-multi-select.js:409:81)
    at $parseFunctionCall 

it just seems to be decorative cosmetics since it seems to work like expected. 
But - am I using the directive somehow wrong?

**Comment by isteven** [comment]
Hi @cornelinux , 

From your directive declaration in the view, it seems that you'd want to display:

- on the button: icon and name
- on the selection items: icon, name and maker

But the directive failed to find "icon" and "maker" properties within your input-model array of objects.

That's my guess. If I'm wrong, perhaps you'd want to try to reproduce the problem in JsFiddler or Plunker so I can analyze better.

**Comment by cornelinux** [comment]
Hi @isteven,
thanks for the quick response. 
Just to give you more information, before I try a plnkr:

In the lines 407-409:

                    // we refresh input model as well
                    inputModelIndex = $scope.filteredModel[ index ][ $scope.indexProperty ];
                    $scope.inputModel[ inputModelIndex ][ $scope.tickProperty ] = $scope.filteredModel[ index ][ $scope.tickProperty ];

the "inputModelIndex" is undefined. The $scope.indexProperty is ids_XYZ, which looks self generaed, but does not exist in the filteredModel.

**Comment by isteven** [comment]
Yea.. I guess I need to see your complete data as well. That's why Plunker / Fiddler will be useful.

**Comment by cornelinux** [comment]
Here is the plnkr of my code. (Alas, without the console.log)

http://plnkr.co/edit/UsbDFI9xQiwgpbe15T3C

I am not sure, if the error, that I get also prevents from the on-close event to be triggered.
Depending on the selected "scope" (name clash!) i want to fill another multiselect "actions"...

**Comment by isteven** [comment]
Hi, sorry for the late reply, it was already late at night :)

Anyway, after looking at your plunker code, I noticed that you use AngularJs version 1.3.x.

At the moment, the directive only support AngularJs version 1.2.x.

I tried using the earlier version and it seemed OK.

**Comment by cornelinux** [comment]
Oh. My bad. Did not realize that.
I realized, that the issue prevents the on-item-click event to be triggered.
Anyway, if I comment out the lines around 407 the event works fine.
I am using your directive for single select and multi select successfully.

**Comment by isteven** [comment]
The <code>on-close</code> callback will also trigger an error if you use AngularJs v1.3.x (I'm fixing this in v3.0.0).

Actually this is the first time I heard error on the <code>on-item-click</code> callback.

Anyway, if your issue is solved, may I close this thread?

**Comment by cornelinux** [comment]
...so 3.0 vill support angular 1.3?
Yes, you may close it. Thanks a lot.

**Comment by isteven** [comment]
Yes, it will support angular 1.3.x :)
