### ISSUE TITLE
preventing xss

### ISSUE THREAD

**Issue by c0debreaker** [isteven/angular-multi-select#184]
Hi @isteven ,

The values I'm using on the dropdown is coming from a database.They are list of devices. I modified one value to have a javascript onmouseover code. When I put my mouse, it executed it. I looked at your directive and I see you are using ng-bind-html which AngularJS claims should prevent xss attacks.

I have ngSanitize injected but it's still allowing the attack. Do you know of anything I missed?

**Comment by c0debreaker** [comment]
Ah, could this be the issue why it's allowing it?

```
return $sce.trustAsHtml( label );
```

That's from $scope.writeLabel function

**Comment by c0debreaker** [comment]
I changed it to return label and attacked stopped! :) Looks like that is it.
However, is this the proper way of fixing it?

**Comment by isteven** [comment]
Hi @c0debreaker , 

If I recall correctly.. the <code>$sce.trustAsHtml</code> is used to allow HTML tags in the selections. You can remove those, but then you'd be limited to normal text.

**Comment by c0debreaker** [comment]
Yup, it's ok. Thank you for the confirmation.

**Comment by isteven** [comment]
No problem, glad to know the directive works for you.

**Comment by sidcool1234** [comment]
Was this issue fixed in any of the versions?
