### ISSUE TITLE
need grouping feature support in the dropdown options

### ISSUE THREAD

**Issue by madasuk** [isteven/angular-multi-select#185]
Hi isteven, Thanks for the nice plugin. But I am looking for some thing like (With Optgroups) at  http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/. The drop down options should support grouping, with select all groups, select individual groups, etc features as shown in the above referred link. Is it possible to achieve those features with this plugin?

**Comment by isteven** [comment]
Hi @madasuk,

Why don't you visit the <a href="http://isteven.github.io/angular-multi-select">manual & demo page</a>, try the features yourself, and then decide whether it suits your requirements? :smiley:

**Comment by madasuk** [comment]
Superb, after getting to this plugin I became little exited and overlooked the super excellent features you supported, sorry for that.
