### ISSUE TITLE
Close button does not call method in the controller

### ISSUE THREAD

**Issue by dasilvas3** [isteven/angular-multi-select#187]
Added on-close attribute on the directive which maps to a function in the controller. When the user clicks outside of the dropdown and it closes the function gets called but when the user clicks on the close button it does not.  According with the documentation the close button click should fire the event and invoke the function.

regards 

Adriano

**Comment by isteven** [comment]
Hi @dasilvas3 , 

This is quite uncommon.. Have you read the manual properly? Do you use the supported browser and the correct AngularJs version?

**Comment by dasilvas3** [comment]
Thanks for your reply. Yes everything is set properly. I can see the issue.
On line 702 of your directive you are missing $scope.onClose( { data:
element } ); you have that when the user clicks on the ESC button line
757.  I have added this to line 702 and now it works.
