### ISSUE TITLE
How to clear/reset from external control

### ISSUE THREAD

**Issue by benjaminmbrown** [isteven/angular-multi-select#192]
I have multiple multi-selects that perform filtering on a list. I'm trying to come up with a 'clear all filters' function that resets all of the multi-selects to None Selected. However, I'm not sure how I can reset all of these from another function. 

When I change the output-model outside of the multi-select, it does not respect the change. Is this a scoping issue? How do I accomplish what I need to do?

**Comment by benjaminmbrown** [comment]
I just answered my own question...Here's how to do it in underscore if anyone needs it:

   _.each($scope.YOURINPUTMODEL, function (value, key) {
		        value.ticked = false;
		    })

**Comment by isteven** [comment]
Hi @benjaminmbrown , 

Yeah basically since there's a listener on input-model, whatever changes you do to it will update the directive.
