### ISSUE TITLE
Groups leave one line blank before next group starts

### ISSUE THREAD

**Issue by NiteshSaxena** [isteven/angular-multi-select#193]
My dropdown has an object passed as input with groups. It leaves one blank line between the end of one group and the start of another. Please suggest?

**Comment by isteven** [comment]
Hi @NiteshSaxena , please replicate in JsFiddle/Plunker?

**Comment by NiteshSaxena** [comment]
Hi @isteven , here is the link, 
http://plnkr.co/edit/cSr9ccvbqjrku0ZusyQd?p=preview
It has a blank line between groups,
sorry for the css.

**Comment by isteven** [comment]
Hi Nitesh, 

Try to upgrade to version 2.0.2 or 3.0.0.
