### ISSUE TITLE
output-model not containing the selected items

### ISSUE THREAD

**Issue by JK00** [isteven/angular-multi-select#196]
I'm know I'm doing something silly here, but I've been stuck on this for a while now.

                <isteven-multi-select    
                    input-model="browsers"    
                    output-model="selectedBrowsers"
                    button-label="name"
                    item-label="name"
                    tick-property="ticked"
                    group-property="msGroup"
                    max-labels="3"
                    max-height="170px"
                    helper-elements="all, filter"
                    on-item-click="multiSelectClick( data )"
                    on-select-all="multiSelectSelectAll()"
                    on-select-none="multiSelectSelectAllNone()"
                >
                </isteven-multi-select>
        {{selectedBrowsers}}

This displays the output as expected.

But, the below prints '[]'.  Why?  What am I doing wrong?

        $scope.multiSelectClick = function (data) {
            console.log($scope.selectedBrowsers);
        }

**Comment by JK00** [comment]
I have some more insights into this issue.

If I wrap the directive in a div with an ng-if, it doesn't work.  For example, replicate this issue with:

    <div ng-if="1">
            <isteven-multi-select    
                input-model="browsers"    
                output-model="selectedBrowsers"
                button-label="name"
                item-label="name"
                tick-property="ticked"
                group-property="msGroup"
                max-labels="3"
                max-height="170px"
                helper-elements="all, filter"
                on-item-click="multiSelectClick( data )"
                on-select-all="multiSelectSelectAll()"
                on-select-none="multiSelectSelectAllNone()"
            >
            </isteven-multi-select>
    </div>

Remove the surrounding div and it works.

**Comment by isteven** [comment]
Hi @JK00 , 

I also would like to know more.. as usual, can you replicate the problem in Plunker / JsFiddler?

**Comment by JK00** [comment]
Just got it to replicate on plnkr.  Here you go.
If you comment out the div with ng-if 1, it works.

http://plnkr.co/edit/4sCQy30RxV6Y2VowyC3F?p=preview

**Comment by isteven** [comment]
My quick guess is that because of this.. 

http://stackoverflow.com/questions/19177732/what-is-the-difference-between-ng-if-and-ng-show-ng-hide

I suggest you to use ng-show instead.

**Comment by tomaszkrym** [comment]
The point of this issue is missing '.' in the name of the $scope variable used in the example. If you would use $scope.something.selectedScope to bind the value, the code in the plunker would start to work.

See http://jimhoskins.com/2012/12/14/nested-scopes-in-angularjs.html

**Comment by IllyaMoskvin** [comment]
Targeting a nested property for `output-model` is a valid work-around, but not a fix.

@isteven's suggestion of using `ng-show` instead of `ng-if` worked in my case.

Hmm.. it probably has something to do with the directive not "existing" when the `ng-if` condition is not met that throws it off. I'd guess that there's a `$watch` somewhere that's being bound incorrectly – either one defined explicitly in this module, or one set up implicitly by AngularJS through its two-way binding.
