### ISSUE TITLE
Use templateUrl instead of template in directives declaration

### ISSUE THREAD

**Issue by tomaszkrym** [isteven/angular-multi-select#197]
The approach with templateUrl and templateCache allows to customize the template easily. I.e. this approach is used in http://angular-ui.github.io/bootstrap/

@isteven, if you accept this request, I can submit a PR.

**Comment by isteven** [comment]
Hi @tomaszkrym, 

Sorry for the late reply & thanks for the PR.  I actually considered & tried similar solution, and I couldn't find a good reason / benefit to use it.

For example, how is this going to make template customization easier? The template is still HTML tags converted to Javascript string which, IMO, not much different with what we have now.

I also tried using a physical, separate HTM file, but really bad in terms of modularity. You can't put the template file anywhere you like without extra configuration / hacks. 

Perhaps you can explain to me how is this solution better than what I currently use?

**Comment by tomaszkrym** [comment]
The point is that the module including isteven-multi-select.html can override 'isteven-multi-select.html' with putting his version to $templateCache. Currently programmer would have to fork whole  isteven-multi-select.js, what is much worse in scope of upgrading to new releases.

**Comment by isteven** [comment]
Hi @tomaszkrym ,

To be honest I personally have no problem so far modifying directive templates directly on the JS file, but your explanation is valid, and there's no harm doing it either. Will merge your $templateCache PR.

**Comment by tomaszkrym** [comment]
Hi @isteven,

In my projects we usually include templates as <script type="text/ng-template"> in main html file (and so we override templates from libs), but this approach involves server side code.
