### ISSUE TITLE
output-model not working in template

### ISSUE THREAD

**Issue by martybalandis** [isteven/angular-multi-select#199]
If I use template directive, output-model doesn't show up.

example:
    app.directive("mydirective", function () {
        return {
            restrict: "E",
            templateUrl: 'test.html'
        };
    });

if i put in test.html it does not make the output of what it is ticked. If I put directly, it works.
Can this be fixed?

**Comment by isteven** [comment]
Hi @martybalandis , 

As usual, can you provide a Fiddler or Plunker?

**Comment by martybalandis** [comment]
ok. give me few moments, Ill try to make one

**Comment by martybalandis** [comment]
Never mind for now. http://embed.plnkr.co/3c9QOR/preview 
It seems to be conflicting with something and simply does not work. I added to fiddler and it works. I'll close the issues for now. I find it pretty strange cause I do not see any differences at all.
