### ISSUE TITLE
Empty helper-elements causes error

### ISSUE THREAD

**Issue by octaviandavid** [isteven/angular-multi-select#206]
TypeError: Cannot read property 'getElementsByTagName' of undefined
    at Scope.link.$scope.getFormElements (isteven-multi-select.js:311)

Example http://isteven.github.io/angular-multi-select/#/demo-single-selection-mode

**Comment by isteven** [comment]
Hi @octaviandavid , 

Yeah this is related with issue #201. Currently working on it.

**Comment by djindjic** [comment]
I'm getting this error if I use helper-elements="":
![image](https://cloud.githubusercontent.com/assets/1564068/7247127/43ea6128-e806-11e4-92b1-23bdb4f50b74.png)
@isteven , is it same issue related problem?

**Comment by isteven** [comment]
Hi @djindjic , 

Are you using the latest version (v4.0.0)? If not, please try upgrading first. If you do, then please try to replicate it in JsFiddler or Plunker so I can have look.

**Comment by djindjic** [comment]
Yes, I have 4.0.0. I've posted this problem in separate issue. Thanks!
