### ISSUE TITLE
not show selected items

### ISSUE THREAD

**Issue by jmls** [isteven/angular-multi-select#209]
I was wanting to use the select shown as a button with an icon (ie no labels) 

is this possible ? max-labels=0 still shows "(x)" where x = number of selected items. All I want to do is to have an icon on the button instead of a text label

is there an option for this ..

**Comment by isteven** [comment]
Hi @jmls , 

There's no option for that, but if I recall correctly, there are some PRs which do that.

**Comment by ataurrahim** [comment]
Is there any way to show just the number of items selected, to not show the labels or icons?

**Comment by isteven** [comment]
Hi @ataurrahim , 

Sorry for the late reply. If you see the manual and set "max-labels"=0, it will only show the number of items selected ("Total=XX").

**Comment by ataurrahim** [comment]
Thanks @isteven
