### ISSUE TITLE
Change 'None selected' text.

### ISSUE THREAD

**Issue by alainux** [isteven/angular-multi-select#21]
How can I change this text ? Into displaying something custom, e.g. Car Type: None

**Comment by ShivPandey** [comment]
<div
   multi-select
   ...
   default-label="default text"
   .... >
</div>

not working

**Comment by ShivPandey** [comment]
`<div
   multi-select
   ...
   default-label="default text"
   .... >
</div>`

not working

**Comment by malikzee807** [comment]
translation="{nothingSelected : 'Your Text Here'}"
