### ISSUE TITLE
Way to specify output model properties

### ISSUE THREAD

**Issue by tedyoung** [isteven/angular-multi-select#212]
I see an attempt at an implementation of this desire in pull request #127 (specifically the code here https://github.com/Reltik/angular-multi-select/commit/9c8b21da8a1a8fa2fbb10c2a09d7e6a7c972d34c#diff-1241a935ee88b892bb37c0e348dee1e2R435), and it would be nice to have that built-in. If you'd like a cleaner PR for this, let me know.

**Comment by stefanvitz** [comment]
i just opened an request for an output model attribute or an ngModel/ng-change support.
#231 has an patch inside an comment. not possible to do an actual pull request atm.

**Comment by isteven** [comment]
Thanks guys, the code was cherry-picked from the PRs and integrated in v4.0.0.
