### ISSUE TITLE
select and unselect is not working properly at group level in v1.2.0 (for IE8 compatibility) 

### ISSUE THREAD

**Issue by madasuk** [isteven/angular-multi-select#213]
Hi Isteven, I really stuck up to use this nice plugin for my IE8 compatible project,  I am using V1.2.0 to have IE8 support, When I select  'Group1' or 'Group2' the drop down is not working properly. The items won't be selected or unselected correctly, even the drop down itself closes when I click  'Group1' or 'Group2'. Please find my plunker at http://plnkr.co/edit/it6rX2WXXvBUEkCG49jp?p=preview. Is there any fix for this?

**Comment by isteven** [comment]
Hi @madasuk,

I am currently without a internet-connected PC here, so I won't be able to
check my repo for a while.

FYI v1.x.x don't support grouping.

If you really need grouping then get v2.0.2 and above but you need to
create some built in functions that are not available in IE8. You'll also
need to rewrite the CSS as some selectors are CSS3 only.

I understand your problem. I too,  need to support IE8 in my workplace.
That's why v1.x.x supports IE8.

Cheers.

**Comment by madasuk** [comment]
Thanks Isteven, So here is my request for this plugin, either it has to  be supported with grouping feature in v1.x.x or V3.0.0 should be made IE8 compatible. Is it possible to consider this request? If yes, can I have any estimation for release? Otherwise, it would be very difficult for me to continue with this nice plugin because our customers definitely want IE8 support and our project needs to use grouping feature. Thanks for your valuable time.

**Comment by isteven** [comment]
Hi @madasuk , 

Unfortunately there's no plan to provide IE8 support on the newer versions. It's quite hard to do so, and I'm quite resource stricken here, occupied with many things (not to mention fixing the current bugs).

If you eventually decide to modify this directive yourself, you can examine the code and basically do these:

1. Create/override javascript functions which are not supported by IE8. These are easily visible - they trigger errors when called.
2. Modify the CSS, remove & replace the selectors and/or properties not supported by IE8. You might not get exact style but at least it should work.

Browser compatibility tools will help you a lot on this.. If I recall correctly, some are available online.

Hope you can find a good work around. Cheers.

**Comment by madasuk** [comment]
Thanks @isteven , I am closing the issue. As there are some security vulnerabilities in IE8, I will reconsider the decision of supporting IE8.
