### ISSUE TITLE
Getting started ?

### ISSUE THREAD

**Issue by jerry-cbn** [isteven/angular-multi-select#218]
Hello . Thanks for this amazing directive .

Could someone explain clearly how to initiate Angular JS app and to load the module ?

How can I do the link between the module and the controller ?

All the examples uses ngRoute and routeProvider . It uses multiple files with redirections (redirectTo and templateUrl) ; It works, but how could I have only one html file ?

Could someone give me a simple example  ?

Thanks in advance .

Jérémy

**Comment by tedyoung** [comment]
I made a plunker that's pretty basic, hopefully that'll get you started: http://plnkr.co/edit/nuuMlw?p=info

**Comment by jerry-cbn** [comment]
Hello .

One word : Thanks !

Your example is simple and useful !

**Comment by tedyoung** [comment]
I'm glad you found it useful. If you have no further questions, may I suggest closing this issue?

**Comment by jerry-cbn** [comment]
Yes , of course . I do .
Have a nice day : )
