### ISSUE TITLE
Dynamic Update ?

### ISSUE THREAD

**Issue by jerry-cbn** [isteven/angular-multi-select#222]
Hello , I need help again : )

The demo "Dynamic Update" show how to update dynamically the list with a onClick event (attribute ng-click). 
But, how could I dynamically update with anything else than a click event ? (for example, with a traditional Timeout function).

I tried : 

setTimeout ( function() { 
      switchSource( 'modernBrowsers' );
}, 0 );

But it doesn't work ;:(

**Comment by isteven** [comment]
Hi, can you replicate the case in JsFiddler / Plunker / CodePen here?

**Comment by jerry-cbn** [comment]
Hello ! Of course ;

Here is it : http://plnkr.co/edit/LDIOu2Jlt0SvDuUzdJjv?p=preview

(thanks to tedyoung for his job).

I'm trying to call switchSource() function in a traditional setTimeout() function, but I've got an error : switchSource is undefined :(

**Comment by jerry-cbn** [comment]
I got it !!

Plunk : http://plnkr.co/edit/LDIOu2Jlt0SvDuUzdJjv?p=preview
