### ISSUE TITLE
Error: [$compile:tpload] Failed to load template: isteven-multi-select.htm

### ISSUE THREAD

**Issue by eehlers** [isteven/angular-multi-select#227]
In the documentation it says:

Define your input-model:

$scope.modernBrowsers = [
  	{ 	icon: [...]/opera.png..., 	name: Opera, 	maker: Opera Software, 	ticked: true 	}
  	{ 	icon: [...]/internet_explorer.png..., 	name: Internet Explorer, 	maker: Microsoft, 	ticked: false 	}
  	{ 	icon: [...]/firefox-icon.png..., 	name: Firefox, 	maker: Mozilla Foundation, 	ticked: true 	}
  	{ 	icon: [...]/safari_browser.png..., 	name: Safari, 	maker: Apple, 	ticked: false 	}
  	{ 	icon: [...]/chrome.png..., 	name: Chrome, 	maker: Google, 	ticked: true 	}
];

This code generates errors, the strings need to be enclosed in quotes, and the list items must be delimited by commas.

I fixed those errors and now the addon fails with the following error:

Error: [$compile:tpload] Failed to load template: isteven-multi-select.htm

**Comment by isteven** [comment]
Well.. pardon my typo in the documentation.

**Comment by isteven** [comment]
Hi @eehlers , 

Is there any update regarding this issue? Or you have managed to find a solution?

**Comment by eehlers** [comment]
I tried to create an example on Jsfiddler but I did not get the error there, perhaps because the versions of angular available on Jsfiddler do not correspond to the version of angular that I am using (1.3.14).

I notice that file isteven-multi-select.js appears twice in your repo:

1) ./isteven-multi-select.js
2) ./doc/js/libs/isteven-multi-select.js

I get the error with 1) but not with 2).

> Well.. pardon my typo in the documentation. 

I don't appreciate your sarcasm, I reported those errors as a courtesy to you, and to spare your users the same confusion that I experienced.

Apart from that, thanks for providing this code, it works for me now.

Kind Regards,
Eric

**Comment by isteven** [comment]
Hi Eric,

Correct, the doc contains a copy of the directive. However they should be the same file/version. 

Good to know it works for you, but you might want to use v4.0.0 instead (which is still beta for now, but you can grab it here https://github.com/isteven/angular-multi-select/issues/248). I screwed up with v3.0.0, and v4.0.0 contains the fixes.

My apology for the sarcasm. Like most open source developers, I receive issues almost daily from  users. Some of them properly post & help me analyze things along the way, and then there are some who act like they are entitled to everything in life. At times, I might fail to differentiate them. 

Cheers.

**Comment by eehlers** [comment]
i first cloned your repo on 11 Mar.  At that time you were on SHA 6e6c85.  In that revision, the following two files were different:

./isteven-multi-select.js
./doc/js/libs/isteven-multi-select.js

Only the second worked for me.

I just now did a new pull from your repo and today in the latest HEAD (SHA 6355f1) those two files are the same.

My app is stable now but next time I look at it I will upgrade to v4.0.0 (or whichever is the latest version at that time) and let you know.  I would say you could close this ticket for now.

Many thanks for your help.
