### ISSUE TITLE
I want to limit number of selected items to be displayed as button label

### ISSUE THREAD

**Issue by mariapithia** [isteven/angular-multi-select#228]
<multi-select input-model="MyList"
                      output-model="outputBrowsers"
                      button-label="name"
                      item-label="name"
                      tick-property="ticked">
  </multi-select>

Now in MyList object i have 50 values and when i am selecting all 50 values then all those selected 50 values are displayed as button label.

Now what i want to do is I want only 5 selected values to be displayed as button label instead of 50.

So far i have manage to do by directly editing this line in isteven-multi-select.js file on this line:
 var tempMaxLabels = 5; // after

var tempMaxLabels = $scope.outputModel.length;//this was before

but can you tell me how do i do this without editing multi-select.js file???

**Comment by isteven** [comment]
Hi @mariapithia , 

If you read the manual properly, there's a way to set the maximum number of items to be displayed on the button.

**Comment by mariapithia** [comment]
Hello Sir
Yaa i got this working by setting the max-label property.i havent read the documentation carefully and just went on solving problem by debugging the code and all.anyways thank you so much for replying sir.
