### ISSUE TITLE
I want to use multi select using angular translate 

### ISSUE THREAD

**Issue by haseeb200** [isteven/angular-multi-select#229]
I have an issue I want to create multi select using angular translate expression. I mean Button labels and all the options in multi select must support multi lingual. I am using angular translate in my application every things work fine except the multi select. I am not able to handle input model using angular translate.
My input model is like this.

languages={
name:"Angular translate expression",
ticked:true
}

when the multi select is build it renders the name as its rather than translate it using angular translate.

**Comment by isteven** [comment]
Hi @haseeb200 , 

Perhaps you can replicate this case in Plunker or JsFiddler, but can't guarantee anything, as I'm not really knowledgeable about angular translate.

**Comment by damiangreen** [comment]
I'm also experiencing this issue. modifying  localLang after it's rendered does'nt update the labels, so if you're loading translations asynchronously you have a problem
