### ISSUE TITLE
Refresh Button

### ISSUE THREAD

**Issue by jonataswalker** [isteven/angular-multi-select#247]
Hi isteven, your component is great.

Are you watching if ticked property is true (to refresh button)? I mean, in single mode, I've put a "confirm service" between the selection and the action.

If "cancel" I need to mark the previous ticked. So I'm registering based on onOpen event the previous ticked, but I can't update back the button.

Did you get it? If you think necessary, I can create a plunker to demonstrate.

Thanks for your time.

**Comment by isteven** [comment]
Hi @jonataswalker ,

I use watchers in the directive, but only to monitor changes you do from outside, for example:
- You pass new data into the input-model
- You update the input-model from the controller, such as: $data[ 0 ].name = "John"

I'm not sure I understand you, but I guess you can always register the last state using onClick() callback.

If this is not what you're looking for, then I guess you need to provide me a Plunker or JsFiddler.

**Comment by jonataswalker** [comment]
Hi isteven, I will show you soon what I've had to do, to get I wanted.

Thanks for your response.
