### ISSUE TITLE
v4.0.0 is brewing, beta testers needed

### ISSUE THREAD

**Issue by isteven** [isteven/angular-multi-select#248]
Hi all,

Quite busy recently so to make it short; 

I screw up big time on v3.0.0. Will update with v4.0.0 within this week. 

v4.0.0 will bring:
- Fixes for v3.0.0 problems
- output-properties: you can now define which object property you want to include in your output-model.

v4.0.0, depending on your usage, may break things up: the input-model behaviour goes back to v2.x.x. It is now no longer be "locked". Whatever changes you do will be reflected as well in the input-model. So before you re-use your input-model somewhere (say for a different multi-select or anything), you need to copy them first into a new variable. 

You can test the __output-properties__ attribute to select the output data properties. Just type the object property, similar with button-label and item-label.

Other than that, there are no changes in the directive declaration, so if you're not re-using your input-model data  and stick to output-model for the output, you're safe.

Thanks for users who gave feedbacks on this. Muchas gracias. Terima kasih.

Sorry for the inconvenience. Cheers.

**Comment by jonataswalker** [comment]
I'm glad to know about this update.

Regards.

**Comment by isteven** [comment]
Hi all,

I have pushed v4.0.0 in the dev branch. Kindly help me to test this. No new documented feature, so please test with whatever current requirements / spec that you have.

The raw files can be grabbed from:

JS: https://raw.githubusercontent.com/isteven/angular-multi-select/dev/js/libs/isteven-multi-select.js
CSS: https://raw.githubusercontent.com/isteven/angular-multi-select/dev/css/isteven-multi-select.css

Please post the bugs or any weird behaviour here. Thanks!

**Comment by fortesl** [comment]
What is the expected time frame for a bower release of v4.0.0?

Thanks.

**Comment by isteven** [comment]
Hi @fortesl ,

Supposedly this Sunday or the coming Monday.

Kindly help me to test, and do let me know your feedback.

**Comment by RyanPicanco** [comment]
I tried out the beta of v4.0.0. The only issue I see is when you have the `maxLabels` property set. It checks the `attrs` in the if statement on line 527, but then it pulls the maxLabels value out of `$scope`.

Doing this will fix it:

```javascript
if ( typeof attrs.maxLabels !== 'undefined' && attrs.maxLabels !== '' ) {
    tempMaxLabels = ~~$scope~~attrs.maxLabels;
}
```

**Comment by jonataswalker** [comment]
Everything works fine here.

**Comment by isteven** [comment]
hi @RyanPicanco ,

Thanks, noted.
