### ISSUE TITLE
should be able to work only with one group and it items

### ISSUE THREAD

**Issue by smart987** [isteven/angular-multi-select#249]
Hi isteven, Thanks for nice plugin. I need grouping functionality in your plugin but my specific requirement is I should be able to select/UN-select  only one group. While I am selecting or UN-selecting in one group or that group related items, I should not be able to select or UN-select other group and their related group items. Is it possible to have this functionality?

**Comment by isteven** [comment]
Hi @smart987 , 

Unfortunately no, you will need to modify the directive yourself.
