### ISSUE TITLE
single select output-model result as an array of object

### ISSUE THREAD

**Issue by AhamedSKR** [isteven/angular-multi-select#25]
single select output-model result as an array of object,  it must send Object only not array of objects

Actual
[{"id":1,...}]

Expected
{"id":1}

**Comment by KasraKhosravi** [comment]
Hi isteven. I really need to save the single select as a single object and not as an array of objects. Is there any possible and logical way to approach this problem now?

**Comment by isteven** [comment]
Hi @KasraKhosravi ,

Since it's a single-select mode, you can always access the first index of the output-model, say:

    $scope.result[ 0 ]

Does that answer your question?

**Comment by KasraKhosravi** [comment]
First of all, thanks for the great lib :)

Imagine my output is sth like this :  

`{
  "Food": [
    {
        "type": "Pizza"
    }
  ]
}`

The thing is that I am generating input-model options from **remote-url**. What I really want to achieve is sth like this :    

`{
  "Food": 
    {
      "type": "Pizza"
    }
}`

In my code, I am defining the directive in this way:

`
<isteven-multi-select
        input-model="vm.options"
        output-model="vm.data"
        button-label="{{ vm.labelProperty }}"
        item-label="{{ vm.labelProperty }}"
        tick-property="ticked"
        selection-mode="single">
    </isteven-multi-select>
`

and it is really important for me that the data that is in `vm.data` not be saved as an array of objects. Sorry if my explanations are not clear enough. I am still an AngularJS newbie.

**Comment by isteven** [comment]
I'm not sure I understand, since, from your example, it seems that you're more concerned with the input-model instead. 

Can you try to replicate in Plunker or JsFiddler?
