### ISSUE TITLE
Incorrect behaviour when output-model is pre-set or changed outside of the directive

### ISSUE THREAD

**Issue by alexandery** [isteven/angular-multi-select#250]
Hi,

I have the following (as an example):

```javascript
availableParts : {
  {id: 1, name:"engine", checked: false},
  {id: 2, name:"wheels", checked: false},
  {id: 3, name:"gears", checked: false},
};

car {
  parts: []
}
```
```html
<div isteven-multi-select
	 input-model="availableParts "
	 output-model="car.parts"
	 button-label="name"
	 item-label="name"
	 tick-property="checked">
</div>
```

So, now the problems that I discovered.
1. The directive is not working correctly when "output-model" is changed outside of the directive UI
Now, if I have some other piece of code adding a part into car.parts (lets say - "gears") the directive UI does not reflect that initially and displays "None Selected" message. After I click on the drop-down, the title changes to 'Gears' but once I drop the selection list down, 'Gears' item is not checked in the list of available options.
2.  The directive is not working correctly when output-model is pre-initialized
The directive simply clears out output-model instead of making sure that appropriate items are checked in the input-model list. I don't think this is an appropriate behaviour (how would one use the directive in case of an edit functionality of existing data?).

I am not sure if this is by design. If it is then I believe these design decisions are not really valid. I would appreciate any insight into this behaviour.

**Comment by isteven** [comment]
Hi @alexandery , 

As the name implies, the output-model is only an output.

If you want to do changes or initialize your data, do it in the input model, such as:

     availableParts : {
          { id: 1, name:"engine", checked: false },
          { id: 2, name:"wheels", checked: true },
          { id: 3, name:"gears", checked: false },
     };

The directive will then

**Comment by alexandery** [comment]
@isteven Well, this makes the usability of the directive extremely limited, I'm afraid. I'm confused.

So, if I have 50 cars (lets say) and 10 available parts, you are saying that instead of just feeding my model and providing a single array of available parts, I actually need to go ahead and start modifying the "input-model" to synchronize that with what my model is, thus creating 50 copies of my 'availableParts' array and then feeding those into each multi-select drop down I have on the page? This will kill the performance, pollute the $scope with unnecessary data and make the code very confusing and sloppy. 

Of course this is your directive and you've developed what you felt was correct, but don't you see where I'm coming from? Haven't you run into use cases when users need to be able to actually edit existing data? I would expect any control to initialize it's state according with the model it is being bound to.

This was confusing to me when I saw the directive - the whole 'input-model' and 'output-model' instead of 'options' and 'ng-model', which make it fit the whole model of "here are my available options, and here is an array that need to contain only those, that a user selects".

**Comment by isteven** [comment]
Hi @alexandery ,

Before I make further (wrong) assumption, can you kindly provide a simple JsFiddler or Plunker to explain your use case? 

For example, your <code>car.parts</code> array was empty. Perhaps you can give example of the initiation you mentioned.

**Comment by alexandery** [comment]
@isteven 
Ok, took me a little while, but here is the Plunker: http://plnkr.co/edit/mmc62clkMjks741EDRUi?p=preview. 

* Once it loads, check the 'parts' array on 'car' object - it has 1 item "gears". 
* Once you click "Toggle Multi Select" button - your directive is loaded and starts working. Check the "parts" array now - it's empty - your directive effectively killed the model state. 
* Now click "Add Wheels" button and observe "car" state as well as the display of your directive - car.parts now has "wheels" while your directive displays "None Selected".
* Now drop your control down - the title changes to "wheels" but "wheels" options is not checked.
* Now select "engine" or "gears" - it will kill "wheels" from car json and insert whatever you clicked.

Now imagine if I have 10 or 20 of those drop-downs on a page each dealing with a different car with different parts selected!

Not sure if you are interested in my opinion on this, but I believe this behaviour is incorrect. If you do welcome other opinions, here is mine (if you don't - that's fine). The correct behaviour I would expect from a select (multi or single) would be as follows:
* There is a single list of available options. There is no such thing as "tick-property" in the model originally - your directive does angular.copy() and extends this local copy with ".ticked". This way I only need to have a single array of options available which can be fed into as many drop-downs as I want. Optionally the directive is still watching the original list for changes.
* What you call 'output-model' is effectively ng-model which gets set upon user selecting items.
* Your directive gets initialized with what's in ng-model (output-model) upon start to ensure that the appropriate items are checked according to the state of the model (eg. two-way synchronization)

I would appreciate your comments on this and whether this is something that you would be willing to adjust. Thanks!

**Comment by isteven** [comment]
I understand what you mean. I believe this conversation mentioned the same thing: https://github.com/isteven/angular-multi-select/issues/58

I do consider that, but to be honest it's a lower priority for me, for reasons: 

- The current solution works. Granted, the user must do modification prior supplying the data to the input-model.
- You mentioned that no "tick-property" is required (the directive should create such required properties by itself internally). This is true, but it's basically just moving the complexity from the controller into the directive. I believe you can create a simple function to modify your array of objects in the controller yourself.

I don't say my solution is correct - it's just a choice, based on my experience as an old school dev (something like.. "form follows function"). IMHO, the array of object with such "tick-property" is the best embodiment of the selection states. With just looking at the array of object, you know which are selected, and which are not.

Btw if you really need it urgently, use v2.x.x first. v3.0.0 is buggy. I'm working on a fix now. Really sorry for this.

**Comment by isteven** [comment]
Btw, after a second look at your Plunker, I assume you use "addWheels()" to programatically select something?

**Comment by alexandery** [comment]
@isteven Yes, something else can decide: car #10 needs to have wheels (not a user clicking on the drop down). This should be reflected by the directive in it's UI. But even this is a subset of the fact that your directive does not respect what the model is set to (output-model in your terminology).

**Comment by alexandery** [comment]
@isteven Fair enough. As I said - this is your directive and you built it the way you wanted. I guess I'll see what to do next - either find something else, build my own or completely change your directive using it as a base. I would much rather prefer not to get into building my own as I don't have much time plus I'd rather use something that's used by lots of other people.

Regarding your comment about "tick-property". What you've done here is you exposed internals of your directive and you forced users to adjust their models to fit your approach. I believe this is not a proper way to design reusable components - as an end-user I shouldn't care how you track what was selected, all I need to have is my domain model and I want the model property to be set as a list of selected options. Neither of these are satisfied by the directive, unfortunately. But since it works for you, that's ok - it just means that the directive would be very limited in it's use.

**Comment by isteven** [comment]
Btw, correct me if I'm wrong: after a second look at your Plunker, I assume you use "addWheels()" to programatically select something?

If you want to do that (like you said, not a user clicking on the dropdown), i assume you can directly do it like.. 

    $scope.availableParts[ 2 ].checked = true

**Comment by alexandery** [comment]
If all I'm dealing with is a single list - sure, I can accept that approach (which is still a hack to me). But as I said - if I need to display 5-10-20 drop-downs for 5-10-20 cars each of which has different set of parts in it's model, this becomes prohibitive as I would have to create 5-10-20 copies of my "availableParts" array, loop through all of them for each of the cars setting the values. Plus I'd have to make sure everything is synchronized on the page to work properly.

And even then it doesn't address the issue when my model is changed outside of the controller.

The correct way to build this (and again, I don't want to offend you in any way) is to have a **single** list of available options and let directive to create it's own local internal copy of that and work off of that, assigning the selected items from this local list into ng-model (output-model). Upon startup the directive should make sure to do something along these lines:

```javascript
$scope.localList = angular.copy($scope.availableOptions);
for (var i = 0; i < $scope.localList.length; i++){
  $scope.localList[i].checked = SUDO_CODE: $scope.localList[i] is in ng-model array
}
```

**Comment by isteven** [comment]
Hi @alexandery , 

No worries, I understand your requirements and the limitation of the directive in this case. I just wish I have more development time to address these request. 

I'm not sure I can call that a hack. To me, it's simply utilizing the wonderful bindings provided by AngularJs. 

If you want to fork & modify, I suggest to wait a moment. I am pushing new version soon.

**Comment by alexandery** [comment]
@isteven Fair enough, I totally understand your position. The control does what you needed it to do and it's great you made it available for others to use.

As for bindings - I was not implying not to use bindings. As a matter of fact I was kind of leaning towards more angular-like (if I can call it that) way of creating the components. 

I'll wait for your updated version and will see if I decide to fork your codebase to create something on top of it. In any case - thank you for your work and this discussion!

**Comment by lrika** [comment]
Dear Isteven,

I am new user to use angularjs.

I have some questions to ask you about outputModel properties. In the scope, it already store the data to display, but on the button to display the value doesn't display the value. I am so sorry to ask this questions if this question already existed. Could you give me some reason which make this problem occur?

Thank you so much for your time.

Kind regards,

Lrika
