### ISSUE TITLE
Getting DOM Errors

### ISSUE THREAD

**Issue by gizmoboy** [isteven/angular-multi-select#251]
Hi, we're trying to get the directive working in a sample site, and we've gotten it installed and rendering properly, however, something is not wired up.

When the user clicks to open the dropdown, we get a pair of errors:

 TypeError: Cannot read property 'getElementsByTagName' of undefined
    at k.link.$scope.getFormElements (isteven-multi-select.js:311)
    at k.link.$scope.toggleCheckboxes (isteven-multi-select.js:717)
    at fb.functionCall (angular.js:10847)
    at fb.statements (angular.js:10622)
    at hint.js:798
    at k.$get.k.$eval (angular.js:12702)
    at k.$get.k.$apply (angular.js:12800)
    at k.scopePrototype.$apply (hint.js:1478)
    at HTMLButtonElement.<anonymous> (hint.js:797)
    at HTMLButtonElement.n.event.dispatch (jquery.js:4409)
angular.js:10072 TypeError: Cannot read property 'getElementsByTagName' of undefined
    at k.link.$scope.getFormElements (isteven-multi-select.js:311)
    at isteven-multi-select.js:271
    at angular.js:14305
    at e (angular.js:4397)
    at angular.js:4705

When you close it, you get another one of the second error above.

If you click an item, you get teh pair of errors again.

I'm hoping this is a common issue that is just us loading something improperly.

**Comment by isteven** [comment]
Hi, this is related with bug #201.

I suggest to use v2.0.2, or if you want to, you can help me beta test & use v4.0.0 (bug fix for v3.0.0). Read more here: #248

**Comment by gizmoboy** [comment]
OK, we downloaded 4 and laid it in over 3.0; now we're getting this error:

 TypeError: Cannot convert undefined or null to object
    at isteven-multi-select.js:442
    at angular.js:14305
    at e (angular.js:4397)
    at angular.js:4705

**Comment by isteven** [comment]
Hi @gizmoboy , can provide me with a Plunker or JsFiddler of your use case?

**Comment by praveeny1986** [comment]
I am getting the following error. Tried v4 but getting same error.
Any idea why ?
TypeError: Cannot convert undefined or null to object
    at isteven-multi-select.js:470
    at angular.js:16210
    at completeOutstandingRequest (angular.js:4902)
    at angular.js:5282

**Comment by isteven** [comment]
Hi @praveeny1986 , 

Please provide a JsFiddler or Plunker.

**Comment by praveeny1986** [comment]
Hi @isteven ,Thanks for the prompt response.
Somehow it works in the jsFiddler but inside my add it is throwing the above mentioned error. I will dig deeper.

Thanks,
Praveen

**Comment by isteven** [comment]
@praveeny1986 , you're welcome.

**Comment by 02** [comment]
I had this problem and just managed to resolve it. 
The reason is that you're accessing your application using 127.0.0.1, Multi-Select most likely runs into problems with protection against cross browser injection or something, so it can't access something it needs. Anyway, use the external IP to access your application, and it should work.

**Comment by skesani** [comment]
Cannot read property 'selectAll' of undefined
    at Object.link (isteven-angular-multiselect/isteven-multi-select.js:953:125)
Please let me know how to fix this issue.
