### ISSUE TITLE
Any way to close the dropdown menu form one of the callback functions?

### ISSUE THREAD

**Issue by carlosminatti** [isteven/angular-multi-select#254]
I want the same behaviour the dropdown has when it is in single mode. A click on one option close the dropdown. Otherwise it would be good a 'close' button since for some un experienced users it might be confusing or not easy to understand that they need to click outside the dropdown to close it.

I tried to call toggleCheckboxes() from the callbacks without succeed, but I'm not expert in Angular.

**Comment by isteven** [comment]
Correct me if I'm wrong.. A click in one option close the dropdown in multi select mode?  Then, how will you select other options if it closes right after you click something? 

I believe clicking outside (or the main button itself) to close a dropdown is a classic behaviour of these elements, including the native HTML dropdown. I believe non-experienced users won't have much problem.

**Comment by carlosminatti** [comment]
Yes, that is the common behaviour, but my client asked me for that. And I also had the feeling that was not clear, I think it is because this is a very different dropdown, and opened and with many options, sometimes doesn't look like a dropdown. 

A quick solution was to do jQuery('body').trigger('click') on the callbacks (element clicked, select all and select none). 

If you want to select more than one option, you open the dropdown again and click another option. At least for my project, that looks like the best behaviour.

**Comment by isteven** [comment]
Hi @carlosminatti , 

I can't do that, as it will make the dropdown counter-intuitive. Imagine the rest of the users who are used to the common behavior.

If you want something like that, I suggest you to either modify the directive code yourself, or use a different directive. Slightly different, but this one should work just like your requirement: https://github.com/angular-ui/ui-select

**Comment by Shubhi12** [comment]
i want to add a cross x mark on the selected options of my dropdown list. how can i do that in html/css and angular
