### ISSUE TITLE
Dropdown not visible in IE8 when using Version 1.2.0

### ISSUE THREAD

**Issue by NiteshSaxena** [isteven/angular-multi-select#257]
I am using version 1.2.0 as it supports IE-8 but the dropdown is not visible. Need Help.
Thanks.

**Comment by isteven** [comment]
Hi Nitesh, please provide a Plunker or JsFiddler so I can have a look.

**Comment by NiteshSaxena** [comment]
Hi isteven, Sorry for the late reply, I was trying to reproduce the issue but couldn't. Finally found the reason, Now using version 2.0.1, it is supporting IE-8 but I have to use directive as attribute not as element.
