### ISSUE TITLE
input-model passed as custom directive option with bindToControler: true

### ISSUE THREAD

**Issue by djindjic** [isteven/angular-multi-select#258]
I'm getting this console error:
![image](https://cloud.githubusercontent.com/assets/1564068/7249925/38d3d20c-e81e-11e4-8b0b-d33eff7a15e6.png)

here is a plunker sample:
http://plnkr.co/edit/q12it06gT0zn6Rqelm89?p=preview

@isteven, I've mentioned this [here](https://github.com/isteven/angular-multi-select/issues/206), but it seems like it doesn't related to the same issue.

**Comment by isteven** [comment]
Hi @djindjic , 

I tried to open it in Google Chrome (latest version), and I saw no error (I tried clicking, using keyboard, etc).

Can you explain to me on how to trigger the error?

**Comment by djindjic** [comment]
try to open dev tools before clicking to see logged error, didn't you?

**Comment by isteven** [comment]
OK.. below are the screenshots I got.

This one is right after I entered the URL / refresh the browser:

![1](https://cloud.githubusercontent.com/assets/5432100/7250143/58f76de4-e852-11e4-8bf3-d7d4cc626b26.png)

Afterward, I clicked the "Run" button on top:

![2](https://cloud.githubusercontent.com/assets/5432100/7250149/6a5865c0-e852-11e4-94d9-1fd897ff321e.png)

**Comment by djindjic** [comment]
I have browserChanged callback and trying to log browser name in console. It works after few clicks, but log this error on initial browserChanged event

**Comment by djindjic** [comment]
did you try to select another browser from select?

**Comment by isteven** [comment]
Yes.. I tried selecting the items, using both mouse and keyboard. From what I see, your Fiddler works fine. 

![3](https://cloud.githubusercontent.com/assets/5432100/7250240/2251958e-e853-11e4-9d28-1b533a5435ac.png)

**Comment by djindjic** [comment]
please, give me screenshot without cleaning console.log messages. It could be that you have changed selected browsere few times and clear console errors without notice initial. As I said, error is shown only at initial change event

**Comment by isteven** [comment]
OK, here you go - this one is the screenshot without clearing my console.

![4](https://cloud.githubusercontent.com/assets/5432100/7250383/6d8ac40c-e854-11e4-902a-33afb5a8664e.png)

**Comment by djindjic** [comment]
:( it's really strange, here is my screen:
![image](https://cloud.githubusercontent.com/assets/1564068/7250788/7f040d12-e825-11e4-8665-50bc8b955739.png)

**Comment by djindjic** [comment]
:( it's really strange, here is my screenshot:
![image](https://cloud.githubusercontent.com/assets/1564068/7250812/aac17d36-e825-11e4-9d47-76340698f9a1.png)

**Comment by isteven** [comment]
The only reason I can think of is, it tries to focus before the DOM element is ready.

May I know why did you use timeout to push the data into the input-model array? Usually people do this if they want to populate the input-model with data from, say, AJAX call.

**Comment by djindjic** [comment]
yes, in my real app I have aax call in this place.
finnaly, here is my screencast from sauce labs :)
https://saucelabs.com/tests/6e15494342534cbb9944d8c33a4e46bd

**Comment by isteven** [comment]
I saw the screencast.. But I still can't determine the issue. 

No guarantee here, but a simple hack I can offer is for you to comment out these:

    formElements[ $scope.tabIndex ].focus();
    $scope.setFocusStyle( $scope.tabIndex );
    
They're in line 675 & 676.

**Comment by djindjic** [comment]
oh yes, it works. you can close this tracking if it was just my issue.
thank you!
