### ISSUE TITLE
Over-use of !important

### ISSUE THREAD

**Issue by greggroth** [isteven/angular-multi-select#261]
There are cases in the CSS where I don't see what it's necessary to use `!important` ([example](https://github.com/isteven/angular-multi-select/blob/6355f1f2b5f36e69b0f2c38065ed725114b365f0/doc/css/isteven-multi-select.css#L43)).  It limits the end-users ability to adjust the input to match their site's stye.  Are you open to removing some of them or is there a particular reason their used?

**Comment by isteven** [comment]
Hi @greggroth , 

In the beginning they were used to prevent changes by other UI kits such as bootstrap / YUI etc.

They are perfectly safe to remove / modify according to your needs. I suggest to just modify the CSS file directly.
