### ISSUE TITLE
Selecting Items Acts Weird 

### ISSUE THREAD

**Issue by codyjacques** [isteven/angular-multi-select#267]
So for an item in the multi-select, if you click on the text it is automatically selected, but 2 clicks are required if you're clicking on that elements row but outside of the text.  Another weird thing about this behavior is that the second click can be on a different element and that'll be selected.  The proper behavior would be to just have 1 click select on the whole element.

if you remove this logic from the top of syncItems:
                if($scope.secondclick) {
                    $scope.secondclick = false;
                    return;
                }

and remove ng-click="syncItems( item, $event, $index )" from this element:
'<input class="checkbox focusable" type="checkbox" ng-disabled="itemIsDisabled( item )" ng-checked="item[ tickProperty ]" ng-click="syncItems( item, $event, $index )" />'

then the whole thing works with 1 click.  I think from a usability standpoint this is the right thing to do

**Comment by isteven** [comment]
Hi @codyjacques ,

I coudn't find "$scope.secondclick" in the code. Are you using the latest version (v4.0.0)?
