### ISSUE TITLE
Binding multi select to dictionary

### ISSUE THREAD

**Issue by c437** [isteven/angular-multi-select#268]
$scope.items3 = 
       {  '000001'  : 'Chicago',
         '000002'  : 'New York',
         '000003'  : 'Washington'}  ;  

How do I bind items to multi-select? Please provide some code so that the name is 'Chicago' and value as '000001'.

**Comment by c437** [comment]
I fix it by converting dictionary to object using lodash like below:
 var response= $.map($scope.items3 , function (key, value) {
            return { id: value, label: key };
        });

**Comment by isteven** [comment]
You've done it right. You need to first format the data into a proper array of object. 

To achieve this you can use any library or technique you like.

Don't forget to put additional object property to determine the selection status.
