### ISSUE TITLE
ParseError: Unrecognised input =>  -webkit-box-shadow: box-shadow: ...

### ISSUE THREAD

**Issue by vcavel** [isteven/angular-multi-select#271]
Grunt less gives me an error on this  :

```
Running "less:production" (less) task
>> ParseError: Unrecognised input in bower_components/angular-multi-select/isteven-multi-select.css on line 175, column 5:
>> 174     outline: 0;
>> 175     -webkit-box-shadow: box-shadow: inset 0 0 1px rgba(0,0,0,.065), 0 0 5px rgba(102, 175, 233, .6) !important;
>> 176             box-shadow: inset 0 0 1px rgba(0,0,0,.065), 0 0 5px rgba(102, 175, 233, .6) !important;
Warning: Error compiling app.less Use --force to continue.
```

Replacing  ``-webkit-box-shadow: box-shadow: inset ...`` by ``-webkit-box-shadow: inset ...`` removes the error.

I am not amazingly skilled at css but what's in the code doesn't seem right (double property), is it a bug? What is the purpose of the ``box-shadow``?

If it's a bug I can pull request, thanks for the good job !

**Comment by isteven** [comment]
Hi @vcavel , 

This is fixed in v4.0.0. Try to upgrade. 

(I also just realize that my manual still showing v3.0.0 as the latest version. Sigh)

**Comment by vcavel** [comment]
Sweet, thank you!

**Comment by vcavel** [comment]
Just tested it and it works, thanks
