### ISSUE TITLE
Scroll bar is not working in IE11

### ISSUE THREAD

**Issue by Chandakumar1984** [isteven/angular-multi-select#272]
While we have more items ,scrollbar is not showing in IE11 while its working properly in chrome!

**Comment by isteven** [comment]
Hi @Chandakumar1984 ,

Did you use max-height attribute? 

If yes, try to use "px" in it, say, max-height="100px"

**Comment by Chandakumar1984** [comment]
Hello isteven,

Yes I tired that but seems its not working in IE11 :( 

Thanks for your replay!

**Comment by isteven** [comment]
Alright, can you try to replicate the problem in Plunker or JsFiddler?
