### ISSUE TITLE
2 Mulit-Selects binding to the "same" data

### ISSUE THREAD

**Issue by ChadRockwell** [isteven/angular-multi-select#273]
I have a page that requires 2 different multi-selects that _originate_ from the same array.  However, I use lodash to filter/sort the original data, thus creating new collections/arrays.  I don't bind the multi-selects to the original data but the newly created filter/sorted data.  When I choose an option in one of the mulit-selects the binding of the other changes too.   They are essentially "in sync" even though they are bound to 2 different collections. I would expect them to behave independently of each other but they don't.  I'm hoping I'm just missing something here.

Thanks.

http://embed.plnkr.co/LP4GSCFyav7skmZXXRgK/preview

**Comment by isteven** [comment]
Hi @ChadRockwell ,

Usually I use angular.copy to make sure I create a deep copy of an object.

I am not sure how Iodash filter works, but seems that it just created object reference in your example.

For example, adding this works:

$scope.compareYears = angular.copy( _.sortByOrder($scope.data,['year'],[false]) );

**Comment by ChadRockwell** [comment]
Thanks for the work around.  It will accomplish what I need.  

FYI...I don't believe that lodash maintains an object reference.  I did an object compare in Chrome dev tools and it indicated that the 2 collections (after the sort) did not point to the same object in memory.  I'm still perplexed why this doesn't work.

**Comment by isteven** [comment]
@ChadRockwell , 

Glad can help. Cheers.
