### ISSUE TITLE
Can it be closed when an item selected?

### ISSUE THREAD

**Issue by hxlniada** [isteven/angular-multi-select#274]
When i use the single mode, I wan't it to be closed when item selected? Is there something I missed?

**Comment by isteven** [comment]
It is closed when you click an item.

**Comment by hxlniada** [comment]
Sorry, my problem is:
```javascript
               clickedItem = angular.copy( item );
               console.log(1, clickedItem);                                                    
                if ( clickedItem !== null ) {   
                    console.log(2, clickedItem);                     
                    $timeout( function() {
                        console.log(3, clickedItem);
                        delete clickedItem[ $scope.indexProperty ];
                        delete clickedItem[ $scope.spacingProperty ];      
                        $scope.onItemClick( { data: clickedItem } );
                        clickedItem = null;                    
                    }, 0 );                                                 
                }      
```
```
1 Object
vendor.js:747 2 Object
vendor.js:745 1 Object
vendor.js:747 2 Object
vendor.js:749 3 Object
vendor.js:749 3 null
vendor.js:102 TypeError: Cannot convert undefined or null to object
    at vendor.js:750
    at vendor.js:138
    at e (vendor.js:40)
    at vendor.js:44
```
weird

**Comment by hxlniada** [comment]
Sorry..
But my problem is:
When I clicke an item, something will process twice! and it cause an error
              
  clickedItem = angular.copy( item );                                                    
              if ( clickedItem !== null ) {                        
                    $timeout( function() {
                        delete clickedItem[ $scope.indexProperty ];
                        delete clickedItem[ $scope.spacingProperty ];      
                        $scope.onItemClick( { data: clickedItem } );
                        clickedItem = null;                    
                    }, 0 );                                                 
                }

**Comment by isteven** [comment]
Can you try to replicate the problem on Plunker or JsFiddler?

**Comment by hxlniada** [comment]
Sorry, there is no problem on JsFiddler, there must be someting wrong in my code, but i can't figure it out...
Thank you...resolved

**Comment by terales** [comment]
@hxlniada what was a problem? I've faced it too.

**Comment by hxlniada** [comment]
@terales I didn't resolve it.. I write a multi-select by myself, based on angular bootstrap...

**Comment by isteven** [comment]
Hi @hxlniada , @terales ,

I don't know what's wrong, but it would be helpful if you can replicate the problem on JsFiddler or Plunker.

**Comment by terales** [comment]
Sorry, I can't run angular 1.3 in jsFiddle: http://jsfiddle.net/0k8udanr/2/

**Comment by isteven** [comment]
I guess you can try using angular 1.2. 

Load the framework from the first dropdown on the top left.

**Comment by terales** [comment]
NO luck with 1.2 as with 1.3 :(

http://jsfiddle.net/0k8udanr/4/

**Comment by isteven** [comment]
Hi @terales , 

I did not see anything in your example.. This is what I saw:

![code](https://cloud.githubusercontent.com/assets/5432100/7743761/431b84ca-ffd0-11e4-9429-cbd3513c6b16.jpg)

**Comment by terales** [comment]
Yep, as I wrote 3 days ago I can't run angular in jsFiddle. You suggested to try angular 1.2, but there was no luck too.

**Comment by isteven** [comment]
Hi @terales ,

No wonder I saw nothing. Please read JsFiddler documentation on how to load JS frameworks / libraries.

http://doc.jsfiddle.net/basic/introduction.html

**Comment by terales** [comment]
I've set up a demo on Plunker: http://plnkr.co/edit/eQIYAPFEmx36veG9TsGx

I'll try to reproduce bug on this weekend.

**Comment by fredtma** [comment]
Having the same error as @hxlniada but what I have noticed is that i get the error 'Cannot convert undefined or null to object' (line isteven-multi-select.js:442) when running on local machine but when deployed live the error disappears.
