### ISSUE TITLE
Using Angular filters?

### ISSUE THREAD

**Issue by mattdittman** [isteven/angular-multi-select#275]
Is there no way to use custom angular filters with this? I love the functionality here, but it would be great to be able to use custom as well as angular-supplied filters without having to loop through a collection in the controller and manually adding a property to the objects during initialization. 

For example, if we're binding to a $scope.persons collection, it's huge to leverage angular's filters so we could ailas each item from .persons, like "person in persons" ... so in the item-label we could do something like "person | fullName". Accepting a filter result would negate the need for the one-off style of the item-label format. Instead of item-label="icon name maker" as in your example, a developer should find it easy to create a "displayBrowserText" filter for each browser and pass in the root object. 

Example: 
<div
    isteven-multi-select
    input-model="modernBrowsers"
    repeat-alias="modernBrowser"
    output-model="outputBrowsers"
    button-label="modernBrowser | displayBrowserButtonText"
    item-label="modernBrowser | displayBrowserItemText"
    tick-property="ticked"
>

**Comment by isteven** [comment]
Hi @mattdittman , 

Unfortunately at the moment there's no support for custom AngularJs filters.

I created such button-label and item-label in a space separated-values so users can easily see & change what they want to display on the directive (imagine a newbie dev, or someone who's just into Angular).
