### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by alexandernst** [isteven/angular-multi-select#282]
I see that there are quite some issues and pull requests. Most of them haven't received a single reply.

I need a project like this for a project I'm working currently on, which makes me ask "What is the current state of the project?". Are you going to support it, develop new features and fix existing bugs, accept pull requests, etc?

**Comment by isteven** [comment]
HI @alexandernst , 

Thank you for considering this directive for your project. Now, answering your questions:

1. I see that there are quite some issues and pull requests. Most of them haven't received a single reply.. 

> I believe that's a bit harsh.. If you see the closed issues, you can see that I tried to at least reply to every issue. Now for the pull requests, I pulled a few automatically, and cherry picked some manually (not using Git, just copy & paste them as I need). The rest are PRs that, IMHO, are not so popular, and I feel that including them into the code will only make the code even bigger without benefiting most of the users.

2. I need a project like this for a project I'm working currently on, which makes me ask "What is the current state of the project?". Are you going to support it, develop new features and fix existing bugs, accept pull requests, etc?

The current state of the project is: alive - latest version is v4.0.0. 

Am I going to support it? Yes. Until when? God knows. I'm not paid to do this, so I am sure you understand that there might be other things with higher priority in my life.

What can I assure you is that, when I decide not to support it any longer, I will find someone to maintain the code, fix bugs, and continue the development.

Develop new feature.. yes, but only if it serves greater good. There's no way I can work on each and every feature requests. 

I hope my explanation is clear. My apology if they sound harsh to you - I am just trying to be honest with the facts & situation here.

**Comment by alexandernst** [comment]
@isteven Ok, nice to hear that! I already forked the project and applied a few fixes, but if you're still keeping it then I'd prefer to submit patches here rather than going on with a fork.

This is my fork: https://github.com/alexandernst/angular-multi-select

As you'd see, I already did some changes:

* applied #265 , #260 and #232 (with some small fixes on top of those)
* removed all trailing spaces
* converted spaces to tabs (indent)
* moved from bower to npm
* renamed the project (replaced "isteven" with "angular")

I'd like to push back some of those changes, so tell me which ones do you want to keep and I'll make a PR. Just one thing, please use GitHub's "accept PR" instead of manually merging stuff because that would make contributing a lot easier.

**Comment by isteven** [comment]
@alexandernst 

I will indeed apply #265 and #260.. But I need to first test everything before I merge them. And I am really2 busy at the moment. Big things are happening in my life.

I did created something like #232.. it's pretty easy actually, just regular expressions to replace things.. but I cancelled it, thinking of having an output formatter function instead... say, a function which return any HTML format they want. From what I see, people prefer something like that.

As for the rest.. let's continue the discussion some other time, I am currently occupied with something important. I hope you understand. Thanks for the inputs btw, much appreciated.

**Comment by alexandernst** [comment]
@isteven Ok, great! Since I can't put this on hold as I'm actually paid to do it, I'll keep patching my fork. Ping me when you're ready to discuss how to merge back the two projects.

**Comment by alexandernst** [comment]
@isteven After a week of work this is how my fork looks like: https://github.com/alexandernst/angular-multi-select

You're free to cherry pick the improvements I did, but I must say there is almost nothing left from the original code. I must say you failed at following "the Angular way". The entire focusing management, selections, etc seems way over-engineered and complex.

There are some small things left in the TODO, but overall, it's done.

If you still want to merge the two projects, ping me.
