### ISSUE TITLE
retrieving selected options from server not working

### ISSUE THREAD

**Issue by Valencia2014** [isteven/angular-multi-select#283]
I can send my objects to my server just fine, but when I try to pull it back from the server to the output-model, that doesn't work. Where do I point the selected options to? I know it's not my server calls because I can see the correct info in both my data logs and the network log in browser. I do think it has to do with the mutated input discussed here>https://github.com/isteven/angular-multi-select/issues/276 .

**Comment by isteven** [comment]
Hi @Valencia2014 ,

You don't pull to output-model. It's output-only. Whatever data you pass to output-model will simply be ignored by the directive.

Whatever data you want to pass into the directive, pass it using the input-model.

If it's still unclear, perhaps you can replicate the case in Plunker or JsFiddler.

**Comment by Valencia2014** [comment]
Thanks for that super quick response. When I did the get call successfully, I just looped through each object since there aren't many (and since the objects are different) and ticked them off in the input-model.
