### ISSUE TITLE
Selected button going empty?

### ISSUE THREAD

**Issue by gizmoboy** [isteven/angular-multi-select#285]
I'm trying to get my head around a sample using grouping with a single-select, and I'm seeing a weird visual glitch where the dropdown starts with "None Selected" and when I choose an entry it shows that entry, but when I click on the dropdown to change the entry, it reduces to a tiny empty button (which is no longer under the mouse).

Pretty sure I've got something misconfigured, but I don't know what.

There are a few console errors regarding undefined expressions as well. I'm sure they;lre related, but they're the unhelpful embedded angular errors.

I've got a plunk of the issue here: http://plnkr.co/edit/UcCS6DbKHidPVlCRG1Pt?p=preview

**Comment by isteven** [comment]
Hi, I'm rushing but just a quick guess:

Add 

    ....
    output-model="aScopeVar" 
    ....

in your directive declaration. Hope it helps.

**Comment by gizmoboy** [comment]
I thought the output model was deprecated in 4.0 now that the input model reverted to 2.x. Style. 

Best,

-- 
-- jas
--
http://www.linkedin.com/in/jeffreysullivan


*** Sent from my mobile device. Please excuse brevity and errors.  ***

**Comment by isteven** [comment]
Hi @gizmoboy , 

Input-model reverts back, but output-model is now required.

Reason being lot of users asked about the extra variables in the input-model, so to make things tidy, it's better to have them grab the results from output-model instead. 

Sorry for the confusion. I screwed big time on v3.0.0.
