### ISSUE TITLE
Want to use group-property and horizontally orientate each group

### ISSUE THREAD

**Issue by troddick** [isteven/angular-multi-select#287]
Is it possible to have each group be horizontally orientated with the content below each group name.
Ex: (tried to add spacing to visualize the columns for each group)
<strong>Physical</strong>&emsp;&emsp;<strong>Chemical</strong>&emsp;&emsp;<strong>Biological</strong> 
      Acidity &emsp;&emsp;&nbsp; Carbon  &emsp;&emsp;&emsp;   Algae
      habitat   &emsp;&emsp;    Major Ions &emsp;&nbsp;        Amphibians
      precipitation  &emsp;   pH   &emsp;&emsp;&emsp;        Birds

Rather than:

<strong>Physical</strong>
    Acidity     &emsp;           habitat     &emsp;        precipitation
<strong>Chemical</strong>
    Carbon      &emsp;         Major Ions   &emsp;    pH
<strong>Biological</strong>
    Algae       &emsp;          Amphibians   &emsp;   Birds

Thanks,
Tonia

**Comment by isteven** [comment]
Hi @troddick , 

Unfortunately no. The horizontal layout is simply a responsive CSS play. The HTML template stays the same on both horizontal & vertical layout. You need to change the HTML template as well to achieve the grouping you want.

And this is just a quick guess, but you might need to also change the ng-repeat logic. As for now it's just a simple ng-repeat, but I'm not sure whether the same looping logic is enough to achieve what you want.
