### ISSUE TITLE
Custom html for dropdown elements

### ISSUE THREAD

**Issue by sameertanna** [isteven/angular-multi-select#288]
Hello,

I would like to display custom html in the dropdown for each element. Something like this --

<b ng-bind-html="group.DisplayName"></b>
<br />
<small>
             {{group.GroupMembers}}
</small>

Basically, I would like to display each element in the dropdown in two lines, first line will be the name of the group and the second line will be comma separated list of people (usually less than 6) in that group (as shown in the html above).

Can someone please tell me how this can be achieved?

**Comment by isteven** [comment]
Hi @sameertanna ,

Unfortunately as for now there's no support for template formatting like that. 

If you really need it, you can do so in the data (input-model). Just put whatever HTML string required, and the directive will display it.
