### ISSUE TITLE
I want to use tooltip 

### ISSUE THREAD

**Issue by joaquinmautone** [isteven/angular-multi-select#289]
Hi, I want to use angularUI tooltip per each item from the multi-select.
I try to do it this way:

`$scope.objetivos.push({
       id: v.id,
       nombre: '<span tooltip="Hola!" tooltip-placement="right" tooltip-trigger="mouseenter">' +
                        v.nombre + 
                        '</span>',
       ticked: false
});`

What i am doing wrong? which is the right way to do this?
Thanks!

**Comment by isteven** [comment]
Hi @joaquinmautone ,

Unfortunately I have no experience in integrating directive within a directive like that. I suspect there's a problem during compilation. Not sure whether AngularJs can compile something like that.
