### ISSUE TITLE
A page with many select picker

### ISSUE THREAD

**Issue by flyher** [isteven/angular-multi-select#291]
i read this demo:
http://isteven.github.io/angular-multi-select/#/demo-grouping

if i have some select and they  must use one datasource, there has a problem.
they will show users the same selected result,but i need different selected result.
could you help me ?

![1](https://cloud.githubusercontent.com/assets/5570324/8123223/3b8e8282-10f8-11e5-8342-f1d97b71b928.png)

**Comment by isteven** [comment]
Hi,

Deep copy the input model to new scope variables as required and then pass
them to each directive.

Example;

Let's say $scope.data1 is the original data:

$scope.data2 = angular.copy( $scope.data1 );

$scope.data3 = angular.copy( $scope.data1 );

..And so on.

Then pass these data2 and data3 to the directive declaration as required.

**Comment by flyher** [comment]
well,thank you very much.
this can also solve my problem.
```html
<div ng-repeat="index in search_len">
    ........data info..........
</div>
<div ng-click="add_select()">
```
then i add an function add_select()  in control js to change search_len's data.
but with you answer, i have another question,

-----------------------

when i create html by js code,
```js
$("#divid").html(........data info..........);
```

it seems that the select cannot init options data in your function, it can be bind only when the html tag already exist in html code.is it?

**Comment by isteven** [comment]
Hi, I have bever tried dynamic declaration  like that before, so I can't
say much about it. To be safe, declare them explicitly. Maybe you can also
try hiding & showing them instead.

**Comment by flyher** [comment]
Thank you~~~~
