### ISSUE TITLE
how to close the drop down list in the drop down panel?

### ISSUE THREAD

**Issue by rcholic** [isteven/angular-multi-select#292]
I would like to see if it's possible to add a Close button next to the Reset icon so I can  close the drop down list without having to click outside of the box. What's the best way of doing this? Thanks

**Comment by isteven** [comment]
Hi @rcholic , 

You don't need to click outside to close the box. You can click the dropdown button again to close it.

**Comment by rcholic** [comment]
thanks @isteven

**Comment by isteven** [comment]
You're welcome. 

If this answers your problem, please close the issue.
