### ISSUE TITLE
Default Values?

### ISSUE THREAD

**Issue by trexlee26** [isteven/angular-multi-select#294]
Hi,

Sorry to bug you as this is a simple issue but has been driving me nuts for hours. How do you add a default value to the dropdown?

All I want it to say is Select instead of having it blank...then the values underneath.

Thanks so much!

**Comment by georgy7** [comment]
@trexlee26 Could you help me to fix the same thing? Did you use the version 4.0.0?
I tried to iterate over input-model and make `n.selected = true`. It didn't work. I also tried to do that in `$timeout`. I tried to make `n.selected = true` and fill output-model at the same time.

**Comment by georgy7** [comment]
@trexlee26 I found it! There is not a specific field like `selected`. Instead, the field, specified in the `tick-property` tag parameter used. For example, for

    <div isteven-multi-select
        ...
        input-model="yourInput"
        tick-property="ticked">
    </div>

You can do

    angular.forEach($scope.yourInput, function(n) {
        if (someCondition(n)) {
            n.ticked = true;
        }
    });

(version = 4.0.0)

**Comment by isteven** [comment]
@trexlee26 , 

Yes that is correct. Basically you just do whatever you want to the input-model.

**Comment by ShivPandey** [comment]
how to select all by default?

**Comment by isteven** [comment]
@ShivPandey 

In your controller, just loop over your input-model & set the select property to true.
