### ISSUE TITLE
select item on enter key press

### ISSUE THREAD

**Issue by aljamala** [isteven/angular-multi-select#296]
Is there any way to allow for the selection to happen based on an enter press instead of a mouse click?

**Comment by isteven** [comment]
Hi,

Just like any normal HTML form element, the directive supports clicking
using spacebar. This applies for both selection and helper element buttons.

**Comment by aljamala** [comment]
ok! thats one way to think about it. 

the angularjs dropdown does support this for example...
https://github.com/angular-ui/ui-select

I also can't tab to the drop down and just press down to open it, so in this sense its not very accessible I guess hence making it less usable.  But thanks for your prompt response!
