### ISSUE TITLE
Modifying output-model  externally doesnot reflect change.

### ISSUE THREAD

**Issue by f1shear** [isteven/angular-multi-select#298]
It should support output-model to be modified externally. It will increase its usability.

**Comment by davidda** [comment]
I guess you want to change the selection programmatically. This can be done with the input-model by changing the property you specified in *tick-property* for the individual array items. There is no need to modify the output-model.

**Comment by isteven** [comment]
Hi @f1shear , 

As what @davidda mentioned, you do all the input modification in the input-model.

output-model is, as the name implies, output only.

**Comment by zy8008** [comment]
If using multiple controls on the same page, and use the same source data, I hope is that through the output model to specify a constant value choice, please consider this scenario

![image](https://cloud.githubusercontent.com/assets/11024800/8691118/3d550fc4-2af1-11e5-8af3-f6e2082bed79.png)

**Comment by isteven** [comment]
Hi @zy8008 ,

The input-model acts like ng-model, so to use them for more than 1 directive, you need to copy your source data first. Usually angular.copy will work.

Read these issues for a solution:

https://github.com/isteven/angular-multi-select/issues/273

https://github.com/isteven/angular-multi-select/issues/291

**Comment by zy8008** [comment]
Thanks isteven

I think I mistook the output models as ng - model, because I, according to the usage of the select control, you are the data sources and ng - model with an object
