### ISSUE TITLE
When Use Multiple widget on same page focus issues comes On Open/Click 

### ISSUE THREAD

**Issue by amit-rana** [isteven/angular-multi-select#308]
I have multiple multi select drop-downs on same page . What happen suppose I am opening first one ..on top of the page and than I am scrolling down at bottom of the page and open another at bottom so.. My focus go to the previous open drop-down ( on top if the page ) and page scroll to top ...SO when I have multiple page get scroll ...because of this ...Any known solution rather than click out side and close first already open drop-down .. Because programmers can understand that not the end-user..

**Comment by amit-rana** [comment]
why we are focusing after close event 
    

                // close callback                
                $timeout( function() {
                    $scope.onClose();
                }, 0 );

                // set focus on button again
                 element.children().children()[ 0 ].focus();// <---- this part keep focus on old drop down

**Comment by amit-rana** [comment]
Is there any issue if I can  put this on comment ... 

Far now I did't get any problem while use mouse but I guess this helpful when we use key up and down right ?

**Comment by isteven** [comment]
Hi, @amit-rana,

I guess you are right. 

The original goal is to emulate the behavior of an HTML select box. It's should be triggered only when the user click the button, or when the user close using ESC button, but not when the user click on the document. 

I will amend this on the next release.

**Comment by amit-rana** [comment]
@isteven  Thanks till next release I will comment that line and bower will update lib when new lib comes with updated code

**Comment by sdir456** [comment]
any updates on this?

**Comment by isteven** [comment]
Hi @sdir456 , 

Unfortunately no update for now - my hands are full & I haven't got time to code.

    // set focus on button again
    element.children().children()[ 0 ].focus();// <---- this part keep focus on old drop down

You can comment that line for now, or if you're willing to think a bit, you can put certain condition there, so that the <code>focus()</code> will only be triggered when user:
- Click the button to close the dropdown
- Hit ESC key

**Comment by bigkype** [comment]
Do you have any documentation on how I can use multiple instances of this menu???

**Comment by isteven** [comment]
@bigkype,

Is your problem related to this issue? If not,  please open a new issue & replicate the problem there.  

If the code is too long, you can use JsFiddler, Plunker, or any other online JS collaboration tool and copy & paste me the URL.
