### ISSUE TITLE
translation with angular-gettext

### ISSUE THREAD

**Issue by cornelinux** [isteven/angular-multi-select#309]
I am using angular-mult-select. It is great. I also started using angular-gettext (https://github.com/rubenv/angular-gettext) which is an extremely convenient way to translate your porject without touching the code.

This can be done by adding a filter "translate" like this:

    <input placeholder="{{ some example|translate}}">

or simply using a directive:

    <div translate>
         The text to translate.
    </div>

But this does not play nice with putting the translation into the controller as described here.
I also do not like to add a lang-javascript-object for every language in my controller.

Could there be another way to handle the translation?
Like the providing options for the labels like

    <div isteven-multi-select
            label-selectAll="Tick all">
    </div>

**Comment by isteven** [comment]
Hi @cornelinux ,

It was used to be like that.. but then we ended up with lots of directive parameters, which is not really nice in my opinion.
