### ISSUE TITLE
Is it possible to remove the "tick" displayed in the dropdown for multiselect? 

### ISSUE THREAD

**Issue by rohandalvi** [isteven/angular-multi-select#312]
Removing the ticked property from input-model doesn't appear like the solution. I dont want to display the "tick" when I select any item from the list. 

Actually, I am trying to do this because of a problem that doesn't remove the displayed tick on deselecting a previously selected item. For example, if I select Item1 (then the tick is displayed besides it) now on deselecting it, the tick still remains and doesn't disappear.

**Comment by isteven** [comment]
Hi @rohandalvi , 

Can you replicate the problem in JsFiddler or Plunker? 

For simply removing the tick mark, you can open the js code, find this variable with string value  '&#10003;'

Change that with an empty string ''.
