### ISSUE TITLE
Does we have pagination feature on scroll  ?

### ISSUE THREAD

**Issue by amit-rana** [isteven/angular-multi-select#314]
In case we have large set of list to in drop down so at that time it take too much effort on single call .. so if we have some pagination feature like first load only some number decide by developer and use some get method to get next set of data on scroll reach at end.  or when search it also work with that ...

i.e.   myGetDataMethod?q="",from=0,to=20

**Comment by isteven** [comment]
Hi @amit-rana , 

No unfortunately we don't have paging. 

I am trying to create a lazy loading - means it will only display the data when you search it.

**Comment by amit-rana** [comment]
@isteven yes lazy loading might help ...

**Comment by amit-rana** [comment]
@isteven Does lazy loading available now ?

**Comment by isteven** [comment]
No.. I cannot promise on when I can provide a functionality.

**Comment by amit-rana** [comment]
Ok NP let me fork lib an try my self for it..

**Comment by isteven** [comment]
That's the spirit of open source developers.. Thumbs up! :+1:

**Comment by amit-rana** [comment]
@isteven OK Sorry for late, busy with other stuff but i did today some code on lazy loading with ajax 
check here my [ last commit on fork ]( https://github.com/amit-rana/angular-multi-select/commit/5d9ca506e6f930c053146ab806386e3ef972cd98 ) . and let me know that it  will work or not,   with my demo working good  .. Next step is binding search and keep it there with results. 

The challenge part in search is if user do change in text than we have to manage calls . so i guess some typeahead timeout we can manage them ... and also keep text in search filter input so when user opens it , he/she can understand that current result is for specific search...( at that time we can't use local search or we can provide some small toggle between local and ajax but for non-IT user it will be complex so better we use only ajax when ajax is there no local ) .we can just bind it with current pagination ajax or we can provide same options for search just like we did for pages ..we going to use same call in controller  but for directive both call will be different ( ajaxOption, ajaxSearchOption )

What you think..
