### ISSUE TITLE
Controller 'ngModel', required by directive 'input', can't be found!

### ISSUE THREAD

**Issue by FirstImpression** [isteven/angular-multi-select#315]
I keep getting this error "Controller 'ngModel', required by directive 'input', can't be found!"
(https://docs.angularjs.org/error/$compile/ctreq?p0=ngModel&p1=input)
because the inputs[checkbox] are missing ng-model directive.

What am I doing wrong?

**Comment by isteven** [comment]
Hi, 

Can help to replicate your code in Plunker or JsFiddler?

**Comment by FirstImpression** [comment]
Fixed it thanks

**Comment by nukulb** [comment]
@FirstImpression do you remember what this issue was? Running into the same issue.

**Comment by nukulb** [comment]
got it, I had forgotten I was overriding the checkbox directive.
