### ISSUE TITLE
Update to docs re: preselecting values

### ISSUE THREAD

**Issue by mkelso** [isteven/angular-multi-select#317]
When preselecting the options you need to pass in 'ticked' as true, not 'selected' as stated in the documentation
http://isteven.github.io/angular-multi-select/#/configs-options

**Comment by isteven** [comment]
Hi,

Find in documentation "tick-property". You can set it to any object proprety name you want to indicate the item state.

Example, if you set tick-property="aloha", then you can use aloha = true or false in your input-model.

**Comment by mkelso** [comment]
Apologies isteven, I see that now. Fantastic directive btw! Thank you very much
