### ISSUE TITLE
Possibilty to show "All selected" when all items are selected

### ISSUE THREAD

**Issue by RoelRoel** [isteven/angular-multi-select#318]
Is it possible to show someting like "All" when all items are selected instead of all values seperated by commas?

It will make the screen look much more "clean" when default everthing is selected (for a filter dropdown).

**Comment by isteven** [comment]
Hi @RoelRoel , 

Yes, have a look at "max-labels" in the config doc.

**Comment by RoelRoel** [comment]
But I would like it if you could see the labels when you selected less than all (no matter how much), but see the text "All" (translatable) when you selected all.

**Comment by isteven** [comment]
I understand that, but then I guess you'll need to customize that yourself.

**Comment by RoelRoel** [comment]
Ok that was easy, I added the "else if" part in $scope.refreshButton function:

  $scope.refreshButton = function() {

                $scope.varButtonLabel   = '';                
                var ctr                 = 0;                  

                // refresh button label...
                if ( $scope.outputModel.length === 0 ) {
                    // https://github.com/isteven/angular-multi-select/pull/19                    
                    $scope.varButtonLabel = $scope.lang.nothingSelected;
                }
                else if ( $scope.outputModel.length === $scope.inputModel.length){
                    $scope.varButtonLabel = $scope.lang.allSelected;
                }
                else {     [...]
