### ISSUE TITLE
De-Select one option and All options 

### ISSUE THREAD

**Issue by akreddy89** [isteven/angular-multi-select#320]
Hi,

Is there a way to Deselect a particular option and De Select all the options at once using the Javascript.

Basically I have an ALL option, When other options are selected i need to De-select All option and When All is selected i need to Deselect all the other options been checked.

Any help would be greatly appreciated.

**Comment by isteven** [comment]
Hi,

Yes, let's say your input-model is $scope.data, you can always do something like..

$scope.data[ 5 ].ticked = false;

Want to select all or none programatically? Just loop over the data and set all the tick-property to false / true.

**Comment by akreddy89** [comment]
okay thanks, One more question. I have alot of options to be selected. After User selects a certain number or after the width limit is reached can we should like 'A,B,C,D.....' 

Because after the width limit is reached its expanding its height and pushing the other elements down.
In my case the user can select upto 50 options.

**Comment by jpack482** [comment]
There is an attribute called `max-labels` that takes a string to be parsed into an integer (`max-labels="3"`, for example), which will limit the number of labels displayed on the dropdown. After the max is reached, the number selected displays in parentheses on the right of the dropdown.

**Comment by isteven** [comment]
@jpack482 

Thanks for the response :+1: That is indeed correct.

**Comment by corydorning** [comment]
Maybe I'm not understanding this, but if i use this code:
```
$scope.data[ 5 ].ticked = false;
```

That option is not being 'checked'. I guess what I'm looking for is a way to have options preselected based on the model i'm passing in. Anyway to do this? Happy to open up a new issue if need be.

**Comment by isteven** [comment]
@corydorning 

To pre-select some options, you do it on your <code>input-model</code>, such as 

    $scope.data[ 5 ].ticked = true;
    $scope.data[ 7 ].ticked = true;

**Comment by corydorning** [comment]
disregard. got this module mixed up with a similar one. doh.

**Comment by AkashNagina** [comment]
Hi,
I am selecting all items on loading of page i want to show 'All Selected' instead of showing name of items and i want only one item to be selected or all item ca n be selected, how could i implement these two?
Thanks in advance!!
