### ISSUE TITLE
Problem while saving and loading from local storage

### ISSUE THREAD

**Issue by AravindKv805** [isteven/angular-multi-select#321]
HI,

I am saving the output model from multiple selection mode into my local storage and when I reload the page, the selected options do not show up. It still says "None Selected". However, if I click on the drop down, my selected options are shown. But still, the selected options are not "ticked" in the drop down. So if I try to add one more option, my previously selected options disappear and only the new selected option is shown.

The issue I am facing is that once I reload the page, the selected options are retrieved from local storage in the same format as the output model but are not reflected in the selected options as I mentioned above.

**Comment by isteven** [comment]
Hi @AravindKv805 ,

Please replicate the issue in Plunker or JsFiddler.
