### ISSUE TITLE
Max-height is not a max height css property

### ISSUE THREAD

**Issue by maxflow7934** [isteven/angular-multi-select#324]
Using the max height attribute on the directive leads to a "height" css property. This should be a max-height css property.

**Comment by isteven** [comment]
Hi @maxflow7934 ,

Thanks for notifying, may I know if it's related to this issue below?

https://github.com/isteven/angular-multi-select/issues/153

**Comment by aciccarello** [comment]
@isteven No, I think it is is an issue with [line 924](https://github.com/isteven/angular-multi-select/blob/d5589891a5590aebabd46975f2a52d312fcee855/isteven-multi-select.js#L924)

`"height:" + attrs.maxHeight` should be `"max-height:" + attrs.maxHeight`

**Comment by isteven** [comment]
@aciccarello , 

May I know if you can test this fix on IE11 (and IE12)? 

I used max-height before but it didn't work in IE. That's why I switched to height.

**Comment by aciccarello** [comment]
Oh, okay. I didn't understand the connection to #153 at first because I max-height looked like it was applied. Once i started scrolling I saw the issue...

**Comment by maxflow7934** [comment]
It is not related to #153. It was not working in Firefox in my case. 
I can currently not tell if it is working in IE...

**Comment by aciccarello** [comment]
@maxflow7934 It sounds like `height` is intentionally being used instead of `max-height` because of #153. If #153 is fixed, then `max-height` can be used. If not, maybe the attribute name should be changed to `height` to clear up the confusion?

**Comment by isteven** [comment]
@aciccarello 

You are correct. It's intentionally used because of that #153  

However changing the attribute name means a breaking change for those who previously used it. If it's gonna be a breaking change, I was thinking to do it in the next big release instead.

**Comment by aciccarello** [comment]
@isteven That makes sense. Maybe for now the documentation should note that it is actually height and possibly link to #153.

**Comment by isteven** [comment]
@aciccarello , 

Yeah, documentation, plus a lot of other things need to be updated :)
