### ISSUE TITLE
Static button label

### ISSUE THREAD

**Issue by phanhongphucit** [isteven/angular-multi-select#328]
I see button-label is configuration to display a list of selected items. But I don't want to see list of item value on the button instead of a static text, because we can see a list of selected item when show dropdown panel. How can I set static text for the button?

Thanks

**Comment by isteven** [comment]
Hi,

There's no option to set a static text, only the number of selection on max-labels. 

If you really want static text, you'll need to modify the code yourself.

**Comment by paladice** [comment]
It's sad :/. Good continuation.
