### ISSUE TITLE
Output model is not updated immediately

### ISSUE THREAD

**Issue by georgi-kovachev** [isteven/angular-multi-select#329]
I had a dropdown list like this.
<div
      isteven-multi-select
      input-model="partnerSites"
      output-model="selectedPartnerSites"
      button-label="name"
      item-label="name"
      tick-property="ticked"
      class="partner-sites"
      max-height="200px"
      max-labels="1"
      on-select-all="loadMentees()"
      on-select-none="loadMentees()"
      on-reset="loadMentees()"
      >
  </div>

and in the loadMenttes function
$scope.loadMentees = function() {
  console.log($scope.selectedPartnerSites);
};
but the selectedPartnerIds doesnot contain updated values, it has some delay.

if I change it to like this it works.
$timeout(function(
console.log($scope.selectedPartnerSites);
), 2000);

But I think this is not the right solution, any ideas?

**Comment by isteven** [comment]
Hi @georgi-kovachev , 

In AngularJs, scopes and DOMs are tightly attached one to another, and sometimes things don't always go in the sequence we expected. In this case, this is where $timeout can help, albeit in a hack-ish way. 

The directive alone doesn't really follow the so-called "Angular way", and I do use some $timeouts in  it, so if you ask me, any solution is a solution, including yours.
