### ISSUE TITLE
Change text when nothing is selected

### ISSUE THREAD

**Issue by srachit** [isteven/angular-multi-select#332]
How do i change the text of the dropdown menu when nothing is selected?
Currently I'm trying:
```javascript
                    <div isteven-multi-select input-model="inputModal" output-model="outPutModal"
                         button-label="name"
                         item-label="name"
                         orientation="horizontal"
                         tick-property="ticked"
                         group-property="msGroup"
                         helper-elements="all none filter"
                         nothingSelected = "Please select an option">
                    </div>
```

But this does not seem to work.

**Comment by isteven** [comment]
Hi @srachit , 

Find the "translation" section in the manual (http://isteven.github.io/angular-multi-select/#/configs-options).

**Comment by raja73** [comment]
Hi @isteven ,

I want to open and close the multi-select by clicking on a button.
I mean when I click on the button the drop-down should be shown and if I click again the drop-down should be closed.

Please help me out with this.
