### ISSUE TITLE
ng-controller attribute not in scope

### ISSUE THREAD

**Issue by the666bbq** [isteven/angular-multi-select#333]
Hi Steven,

I have a problem with 'translation' being undefined when I use ng-controller to bind my controller directly to the multiselect instead of via the router. Translation works fine when I link that same controller via the routeProvider.

cfr :  http://plnkr.co/edit/DGfDvm27043robZmQKr9

it seems to be a timing/scope problem...

What do I need to change to use ng-controller ? I would like to re-use the multiselect on multiple controllers in a single view.

**Comment by isteven** [comment]
Hi @the666bbq , 

To be honest I don't really understand why, and I personally never bind my controller directly to my directive (be it using router or routeProvider).

To achieve the same goal (re-use the multi select), would it be possible if you try to declare it in a service or factory instead, then inject it into the controllers?

**Comment by the666bbq** [comment]
Thanks for the update Steven,
it got me thinking: since routeprovider links the controller to your (partial) view that meant that the controller scope was 'outside' your multiselect. My problem was indeed fixed when I use a wrapper element (div) that contains the multiselect and where the wrapper element gets the ng-controller.
Might not be ideal, but it gets me riding my learning curve again :package: 

updated plnkr : http://plnkr.co/edit/oGxIyVmaXoNYjaUzbd2V

**Comment by isteven** [comment]
Indeed with that wrapper, the controller can find the multi-select DOMs and pass the data into it.

IMHO it's actually the classic angular solution. If you ask me, that's pretty much OK. But again, I'm not really an Angular-way purist.
