### ISSUE TITLE
Using isteven-multiselect with angular material design

### ISSUE THREAD

**Issue by facuxt** [isteven/angular-multi-select#334]
Hello. i have a  weird issue... i am using this beautifull multi select component with angular material design. and when i reload the page, the <md-input directive and its components inside looks ugly.. it only happens in pages where isteven-multiselect is loaded (im using ocLazyLoad aswell). No errors or warnings in console... any hint what is happening here?

**Screenshots.**
Here is the page loaded, but i first visited other section of the page when the multiselect is not present. Then i visit this section wich have isteven multi select on it. look the inputs... they look like they should
![okisteven](https://cloud.githubusercontent.com/assets/7550822/9274031/596d91c0-4268-11e5-9a5d-345ffcc9e96c.png)

But then, i refresh the page... (F5) and then the inputs style dissapeared... 
![ugly1](https://cloud.githubusercontent.com/assets/7550822/9274030/5965bcac-4268-11e5-8c69-503ca1a2d103.png)

they have text on them but the font is white... i cant find any css style applied to it.. so i dont know if there is any compatibility or if im just doing something wrong.
![uglytext](https://cloud.githubusercontent.com/assets/7550822/9274029/59615b08-4268-11e5-98c4-34a510cee8b4.png)

*Thanks in advance*

**Comment by isteven** [comment]
Hi facuxt ,

I don't have experience in Material, so my answer might not be very helpful - but I guess it's CSS problem. Most likely one of the class overrides Material class.

Can you help me to replicate this in Plunker or JsFiddler so I can have a look?

**Comment by facuxt** [comment]
Hello isteven, thanks for the reply! and thank you very much for the component!! is awesome!! here is a codepen with the issue replicated..
http://codepen.io/anon/pen/RPmjJv

To see how it should looks like without isteven-multi-select, you should change the JS line number 2
  .module( "MyApp")

But then when you enable your component... with line
  .module( "MyApp", [ "isteven-multi-select" ])

then all the components are destroyed...

any idea? i just included js.. no css file...

**Comment by isteven** [comment]
Hi @facuxt,

When I checked my web inspector, I saw something like this:

Refused to execute script from 'https://raw.githubusercontent.com/isteven/angular-multi-select/master/isteven-multi-select.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

If I recall correctly, some collaborative tool don't like to load raw JS file from Github like that (and I'm so sorry for not providing a CDN yet - too busy for now)

Can you try to load the JS file manually? As in.. copy & paste the directive code (and its CSS) into your codes?

**Comment by facuxt** [comment]
hello again... here is a codepen with the js copied into it..

http://codepen.io/anon/pen/NqZKPw


it trows another error and i don't know why it happens.

Thanks in advance.

**Comment by isteven** [comment]
Hi,

May I know where do you declare the ngMaterial module into your app?

**Comment by facuxt** [comment]
Thats interesting...with this i had a clue of what was happening here... i couldn't replicate the issue in my app, but the interesting thing is that i avoided the bug just simply not using OcLazyLoad to load isteven-multi-select... i just added to the index the js, but lazyload only loads the css..., the directive is now declared in my app. Now the app is not broken when i reload it... 
Thank you very much. I will try to check if im able to reproduce the error in a codepen...  Can you recomend me any debugging tool for angularjs? im developing just using sublime text and chrome ...

Thank you again and sorry for this weird issue.

**Comment by isteven** [comment]
Uhmm..  I was trying to give you a hint, but let me try to be direct here:

 Put ngMaterial into your myApp definition - at least I could see them working.

    .module( "MyApp", [ "isteven-multi-select" , "ngMaterial" ])

**Comment by facuxt** [comment]
yes, it works... but.. when you put just this... 
.module( "MyApp") it also works with ngMaterial.. dont know why...

in my app i have this declared..

var app = angular.module('app', [
    'ngAnimate',
    'ngAria',
    'ngCookies',
    'ngMessages',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngMaterial',
    'ngStorage',
    'ngStore',
    'ui.router',
    'ui.utils',
    'ui.bootstrap',
    'ui.load',
    'ui.jp',
    'pascalprecht.translate',
    'oc.lazyLoad',
    'angular-loading-bar'
  ]);


and isteven-multi-select was loaded by oclazyload... that didnt work... so i just include the module like this and attach the js to the index.

var app = angular.module('app', [
    'ngAnimate',
    'ngAria',
    'ngCookies',
    'ngMessages',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngMaterial',
    'ngStorage',
    'ngStore',
    'ui.router',
    'ui.utils',
    'ui.bootstrap',
    'ui.load',
    'ui.jp',
    'pascalprecht.translate',
    'oc.lazyLoad',
    'angular-loading-bar',
    'isteven-multi-select'
  ]);


What i was doing wrong?

**Comment by facuxt** [comment]
btw.. that codepen is a fork directly of one used for demos in this page..
https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by isteven** [comment]
Let's see..

Reading the doc at https://oclazyload.readme.io/docs/oclazyload-directive, I saw the directive lazy loading example:

    <div oc-lazy-load="{['js/testModule.js', 'partials/lazyLoadTemplate.html']}">
      
      <test-directive></test-directive>
    </div>

May I know how do you lazy-load the multi-select in your CodePen? I could be wrong but I didn't really see it there.

**Comment by facuxt** [comment]
sorry for the misunderstanding... i am using lazyload in my local project... not in codepen... i just wanted to replicate the error... this issue is solved just without using lazyload... i dont know.. but it doesnt seems to be your component the problem though... 

Thank you again!

**Comment by isteven** [comment]
Hi @facuxt ,

You're welcome. Sorry I couldn't really provide a helpful solution - I have no experience in that lazyload library myself.
