### ISSUE TITLE
Error: [$compile:tpload] Failed to load template: isteven-multi-select.htm on bower package release 4.0.0

### ISSUE THREAD

**Issue by stl-winniechan** [isteven/angular-multi-select#338]
I install angular-multi-select package to my application via bower install. However, I get the following error when loading the page: 
```
Error: [$compile:tpload] Failed to load template: isteven-multi-select.htm
```
Does anyone has idea? I can't locate "isteven-multi-select.htm" in the bower package.

Any help is appreciate.

**Comment by isteven** [comment]
Something is not right here.. The template is actually available in the JS code. 

For a quick fix, you can simply modify the JS file. 

Create property "template" in directive, and then cut the template at the bottom and put it into the "template" property you just created. 

For guidance, look at release version 2.x.x or 3.x.x to see how the previous versions were structured.

**Comment by stl-winniechan** [comment]
Bower package for 3.0.0 works fine. Thanks.
