### ISSUE TITLE
Highlight string that matches on search

### ISSUE THREAD

**Issue by EstebanErcole** [isteven/angular-multi-select#339]
Hi @isteven, i'm having some issue to highlight the string that matches with the results when i do a search, like:

i have  this names:   Joe, Paul, Sally

if i type: Jo --> Joe item appears as a match, but the characters 'J' and 'o' are not highlighted.

Do you know how can i get this working?

Thanks

**Comment by isteven** [comment]
@Esteban, 

That's indeed the correct behavior. There's no such thing as characters highlight in this library.

If you need one, you'll have to code it yourself.
