### ISSUE TITLE
Auto-fit to bootstrap col width

### ISSUE THREAD

**Issue by asimnzr** [isteven/angular-multi-select#341]
Hi,

I am using this awesome multi-select in my project, but what I need is:

1. Multi-select should auto-fit itself to, suppose bootstrap col-2. I tried few things i.e. setting width to 100%, but no success.
2. Setting Background of dropdown button colour to some colour other than white.

Can anyone help me in working around above two points?

Thanks

**Comment by isteven** [comment]
@asimnzr , 

In ".multiSelect > button" (line 35), add width 100%

In ".multiSelect .checkboxLayer" (line 94), add width 100% and remove position absolute.

I hope it's good enough to get you started. You might need to do further fine tunings though.

**Comment by asimnzr** [comment]
I was able to do it at my own and saw your message late.. Thanks for help though!

**Comment by isteven** [comment]
Great to hear that.

I'll be closing the issue then.

**Comment by ameyarockers** [comment]
Hi,

I am planning to use multiselect in one of my projects inside ui-rid (angular grid, another popular anguar table) as editable template but some how i can't bind the array for input-model inside template. For now, I was trying to use hardcoded scope values inside the template.

I am currently using your base example to test things with arrays (modernbrowser) as you've used in your sample.

Any help would be greatly appreciated. 

Here is the template i am using:
var cellMultiSelectTemplate = '<div isteven-multi-select input-model=\"modernBrowsers\" output-model="outputBrowsers" button-label="icon name" item-label="icon name maker" tick-property="ticked"></div>';

and here is the column definition:
 { name: 'Browsers', field: '', cellClass: 'editableCell', editableCellTemplate: cellMultiSelectTemplate, enableColumnMenu: false, minWidth: 250 },

That's how it looks in grid with no data:
![capture](https://cloud.githubusercontent.com/assets/12022450/9635974/9ca6951a-51b6-11e5-9cb3-2d850c7bbf5b.PNG)

Any help is highly appreciated.

**Comment by getcodenow** [comment]
Hi,

Thank you for this project.  I think it is best multi-select after evaluating numerous.

Quick question - i have already changed ".multiSelect > button" (line 35), add width 100%, but I haven't been able to figure out how to right justify the caret.

Do you know how to get the caret to appear on the right side of the dropdown box instead of to the right of the text?  Thank you for any ideas you can suggest.

![sample](https://cloud.githubusercontent.com/assets/14164521/9719328/d59cacde-5548-11e5-88e0-d6c3cead7bdc.png)

**Comment by isteven** [comment]
Hi @getcodenow , 

I'm aware on the difficulty of moving the caret to the far right. Unfortunately it's an unavoidable trade-off when you expand the button to fit 100% parent width.

I'm not sure I can help you with this, but you can try to play with the CSS.

**Comment by isteven** [comment]
@ameyarockers ,

Sorry for the late reply.

Have you managed to solve your probhlem?

**Comment by getcodenow** [comment]
Thank you for getting back to me.  I couldn't figure it out.  I ended up switching to https://github.com/dotansimha/angularjs-dropdown-multiselect.  I'll close the issue.

**Comment by isteven** [comment]
@getcodenow , 

No worry, glad you can find a suitable solution :)

**Comment by dkhunt27** [comment]
This seems to fix the caret issue; moving it to the right side

.multiSelect .caret
  margin: 5px 0px 1px 12px  !important;
  float: right
