### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by PehrGit** [isteven/angular-multi-select#342]
Hey,

First-off, awesome component! 

Would you consider creating a nuget package for the .NET inclined?

Thanks!

**Comment by isteven** [comment]
@PehrGit ,

I have zero knowledge on how to create a nuget package :)

**Comment by PehrGit** [comment]
I created a NuGet package, which can be found here: https://www.nuget.org/packages/angular-multi-select/

**Comment by isteven** [comment]
@PehrGit , thanks for the help, appreciate it!
