### ISSUE TITLE
working fine in browser but Does not displaying list in my ionic app.

### ISSUE THREAD

**Issue by dhruv95goradiya** [isteven/angular-multi-select#343]
first of all, thanks for this Helping post.
i have used this with my ionic app. its working fine in browser but when i tested in my phone, the list of items is not displaying.
will you please guide me.

**Comment by isteven** [comment]
Unfortunately I'm not really familiar with Ionic, so I can't promise you anything.

List of items is not displaying, as in, empty list, or the popup element does not appear at all? If the popup does not appear at all, most likely it's CSS problem.

**Comment by dhruv95goradiya** [comment]
ok..
yup, may be you are right... :)
now its working fine.
thanks a lot for your help.

**Comment by dhruv95goradiya** [comment]
its working fine now....
thanks a lot :)
