### ISSUE TITLE
select box does not work on pressing enter

### ISSUE THREAD

**Issue by rkshkundu** [isteven/angular-multi-select#346]
if we are focused on any option and press enter., It doesnt work. It works by pressing space bar. I know behind he scene we are using checkboxes, thats why selection works by pressing spacebar. But plz make it selected even by pressing enter key.

**Comment by isteven** [comment]
Hi, 

You'll need to modify the code yourself. Just find the ASCII 32 and replace it with.. 13 (I think enter is 13)

**Comment by rkshkundu** [comment]
Thanks for quick response. I am not so good in this. Can you help me.
I am using the following js file.
http://isteven.github.io/angular-multi-select/js/libs/isteven-multi-select.js

**Comment by isteven** [comment]
Sorry, after re-looking at the problem, I think you would need create an extra keypress listener instead. Try to detect key 13 (Enter) in this listener and trigger the "syncItems" function.

Again, you will need to modify the code yourself.

**Comment by rkshkundu** [comment]
I have event on click of enter. In "syncItems" we are passing three arguments, that are item, e, ng_repeat_index. I think e is for event which I have, what about rest two??

**Comment by isteven** [comment]
Item is the currently highlighted object in the input-model.

ng_repeat_index is the index of the currently highlighted object in the input-model

Yes, e is the event.

You can see the way it is called from the template at the bottom of the code.

**Comment by rkshkundu** [comment]
Thanks for support.
Finally I have done it.
Thanks

**Comment by rkshkundu** [comment]
:-)

**Comment by rkshkundu** [comment]
I have used the following line, when we press enter

element.bind("keydown keypress", function (event) {
              if(event.which === 13) {
                event.preventDefault();
                var check = angular.element(event.target);
                check.trigger('click');
                $scope.$apply();       
              }
            });
