### ISSUE TITLE
Is it possible to use controller as?

### ISSUE THREAD

**Issue by saralamuralikrishna** [isteven/angular-multi-select#348]
When I use controller as and dynamically populate the input model then reset give error 

Unable to get property 'ticked' of undefined or null reference

**Comment by isteven** [comment]
Hi @saralamuralikrishna ,

Can you try to replicate this on Plunker or JsFiddler?

**Comment by afnanKH** [comment]
We have the same issue here.

here is how we populate the control

    for(var i=1; i<$rootScope.allCountries.length; i++)
            {
                var countryData =  {
                    name: $rootScope.allCountries[i].name,
                    ticked: true};

                $scope.inputCountries.push(countryData);
            }


    <div class="col-md-5" isteven-multi-select input-model="inputCountries" output-model="outputCountries" button-label="icon name" item-label="icon name maker" tick-property="ticked"></div>

**Comment by isteven** [comment]
@afnanKH , 

Can please replicate in Plunker or JsFiddler?
