### ISSUE TITLE
Button Full Width

### ISSUE THREAD

**Issue by georgi-kovachev** [isteven/angular-multi-select#349]
Hi, I have one question.
How can I make the dropdown element to have 100% of width?

![screen shot 2015-09-24 at 1 31 35 am](https://cloud.githubusercontent.com/assets/6533251/10060885/105786a2-625d-11e5-85eb-22dd4e488ca4.png)

**Comment by georgi-kovachev** [comment]
Can I have some answers for this?

**Comment by isteven** [comment]
Hi @georgi-kovachev ,

Try this: https://github.com/isteven/angular-multi-select/issues/341
