### ISSUE TITLE
Control opening in odd place when it becomes larger than it's container.

### ISSUE THREAD

**Issue by valevalorin** [isteven/angular-multi-select#352]
I have a multiselect with a ton of possible options (locations) and it is placed inside a bootstrap panel. I have the panel set to scroll on overflow. If I open the multiselect and select all locations then close it, the control itself is really long; longer than the panel so the scroll bar appears. When I click on the part of the control I can see, the multiselect dialog appears at the bottom of where the list is, ie hundreds of pixels down the screen, before the panel scrolls to see the bottom of the panel. This results in the panel remaining hundreds of pixels down screen completely disconnected from the control which has scrolled into view.

Trying to access the select when only a few things are selected and the control does not overflow results in normal expected behavior.

![dmaselect](https://cloud.githubusercontent.com/assets/7844459/10149573/204cb6da-6600-11e5-9762-950e29650e4c.png)
![dmaselect2](https://cloud.githubusercontent.com/assets/7844459/10149575/20732c20-6600-11e5-8ff8-3886afeb8f89.png)

**Comment by isteven** [comment]
@valevalorin , 

Width wise, the directive indeed will expand to fill 100% parent element's width. I suggest to put a wrapper element (say a DIV) to wrap the directive. You can then play with the height and width.

If that doesn't work, please replicate this in Plunker or JsFiddler so I can look further.

**Comment by valevalorin** [comment]
Is the issue isn't with the width or the height of the element; they can be whatever. The issue is where the multiselect shows up. Here's a fiddle demonstrating the issue: http://jsfiddle.net/valorin/qxwkdmf5/1/

If you click on the directive and hit select all you'll see the dialog move down the page. If you continue selecting and deselecting the directive you'll see the dialog appear and disappear at the bottom of the result pane far away from the directive box.

**Comment by isteven** [comment]
Ok.. I see what you mean. 

This is the reason:

![git](https://cloud.githubusercontent.com/assets/5432100/10168765/cdca58b6-6700-11e5-9772-8284d2958095.png)

The selection list simply popups at the bottom right after the button (positition:absolute). Now, with all the items selected, the button naturally grows taller. Say 500px tall. When your panel-body is only 300px tall, there will be a 200px height difference. And because of the absolute positioning, it will show up outside of the panel. 

Some CSS addition might fix this problem. Would you like to explore this yourself, or you want a direct answer?

**Comment by valevalorin** [comment]
I know what it was doing, just not the best way to fix it. I was hoping that might've been a way to specify that the dialog should appear after scroll events or something clean like that. If that isn't the case I'll just CSS. Thanks.

**Comment by isteven** [comment]
Hi @valevalorin , 

Yeah unfortunately no such way/settings.. it's simply how HTML/CSS works. 

Anyway I would use <code>position:relative</code> on the <code>panel-body</code>. It should bring the popup within the <code>panel-body</code> right after the button.
