### ISSUE TITLE
Runtime translation change

### ISSUE THREAD

**Issue by FrogDevelopper** [isteven/angular-multi-select#353]
Hi !

I define the labels elements on the initialisation of my controller, but need to be able to change the labels on runtime.
I use the code avec the documentation :
```javascript
$scope.localLang = {
                    selectAll: $translate.instant('multi.select.all'),
                    selectNone: $translate.instant('multi.select.none'),
                    reset: $translate.instant('multi.select.reset'),
                    search: $translate.instant('multi.select.search'),
                    nothingSelected: $translate.instant('multi.select.nothing')
                };
```
Actually, when changing the local, all my labels on my page change but the multi-select, even if I redefine my `$scope.localLang`.

If I look at the code, you generate one the template, so I asume that I need to re-generate the component ? Or is there an other way ?

Thanks for any help

N.B.: sorry if it's trivial, but I'm more back-end dev than front-end, and I'm very bad with javascript and all >_<

**Comment by isteven** [comment]
@FrogDevelopper , 

Sorry for the late reply. Unfortunately as for now it doesn't support dynamic translation. However, you may want to try to update the code yourself.

Try to find this line

    // i18n
    translation     : '='   

And change it into

    // i18n
    translation     : '@'   

Disclaimer: I haven't tested this suggestion.
