### ISSUE TITLE
Close dropdown in js

### ISSUE THREAD

**Issue by hspeedy** [isteven/angular-multi-select#355]
I need to close the dropdown from script. I use debounce function and data is loaded 2 seconds after
last change in selection. At this time I want to close the dropdown from my script. How can I achieve
this? Please help me out.

**Comment by isteven** [comment]
@hspeedy ,

There's no programatic way to do so, but you may try this:

The dropdown has a class, which is <code>checkboxLayer</code>. On show, it will have extra class <code>show</code>. You can try to remove this <code>show</code> class to hide it.
