### ISSUE TITLE
Output model gives an array in 'single' selection-mode

### ISSUE THREAD

**Issue by zachlysobey** [isteven/angular-multi-select#357]
Title says it:
When I use this directive in single selection mode, the scope property bound to output-model gets a single item array. Given that only a single selection is possible, I think it would be better to have it just be the single object, no array.

With the current setup (as I understand it), I will have to set a watcher on this value, and set a different scope property to get the object I want. (not ideal).

**Comment by isteven** [comment]
@zachlysobey , 

Thank you for the feedback. It's initially designed like that.

(After about year of reflection.. perhaps I might be wrong. I'll see how it goes)

**Comment by benjamincharity** [comment]
Also, answered in the [FAQ](https://isteven.github.io/angular-multi-select/#/faq).

> **Why output-model is still an array of objects, even when there's only one item?**
> So that you don't need to write different logic to process the output data. Once an array, always an array (At least in multiple selection mode - things might change in the single selection mode. I'll see how it goes along the way).

**Comment by zachlysobey** [comment]
Ah. Thanks @isteven and @benjamincharity.

I lean towards thinking it shouldn't be wrapped in a single array in single-selection mode, but I definitely see the point of view for having it be consistent.

On a side note, I recently discovered ngModelController, which makes it pretty easy to tinker with how data is modeled. This provides a significantly better approach than adding watchers (etc..) to getting the array syntax to work with my data model. 

Anyway... I'm closing this issue as this behavior was a design choice rather than an oversight. Thank you for considering the alternate approach. Perhaps re-open if you plan to change it?

**Comment by isteven** [comment]
Agree.. This is one of those things that are always fiercly debated, and admitedly, my approach is not always the most common. I'll make sure to think thoroughly before I change it, as it will be a breaking changes :)
