### ISSUE TITLE
How can i write directive for isteven_angular_multi_select ?

### ISSUE THREAD

**Issue by sasikumargn** [isteven/angular-multi-select#360]
Hi 

I'm new to angular JS. I have a common drop down which i'm using in many places. so i started writing directive for drop down. But the issue is when selecting the values from drop down, scope are not present in the controller. scopes are available in directive.

I have tried with on-item-click events, its triggering the function. but the selected values are not present in data.

Could you pls help me to get the output model value in controller on selection of drop down.

Thanks

**Comment by isteven** [comment]
@sasikumargn , 

Can you try to replicate your problem in Plunker or JsFiddler?

**Comment by sasikumargn** [comment]
I have done this, Thanks
