### ISSUE TITLE
Having drop-downs in ng-repeat with single input model does not work correctly

### ISSUE THREAD

**Issue by cluka** [isteven/angular-multi-select#362]
Hi,
I'm having more drop-downs in a ng-repeat, each bound to the same input model.
So changing one, updates both instead of only one.

http://plnkr.co/edit/Ajeyqhu9l1Ga7TMwGxBS?p=preview

How can I fix this without duplicating input model?

**Comment by isteven** [comment]
@cluka , 

Unfortunately you need to duplicate the input-model. The directive (and Javascript in general) treats object as one, unless you duplicate them.

I suggest to use <code>angular.copy</code> to do deep-copy (basically duplicating) the object.

**Comment by cluka** [comment]
Ok, thanks
