### ISSUE TITLE
New to show different default lables

### ISSUE THREAD

**Issue by narendrasanchi** [isteven/angular-multi-select#366]
Hi , I have multiple multi select dropdown lists on same page and I need to show different default label for each multi select like for Region multi select I want to show "Select Regions" , for country multi select I want to show "Select Country" and for state multi select I want to show "Select State"  . How can it be done . Please advice..

**Comment by isteven** [comment]
@narendrasanchi , 

Check the "translation" option on the config page http://isteven.github.io/angular-multi-select/#/configs-options
