### ISSUE TITLE
outputCardNumbers output scope variable is always undefined

### ISSUE THREAD

**Issue by masalinas** [isteven/angular-multi-select#370]
I have angular v1.2.26 and angular-multiseled 5.5.4. 

My problem is simple the component bind correctly the driver cards number in multiselect, I change something or anything and click ok in my form, always the $scope.outputCardNumbers variable is undefined. I don't know why?

This is code:
Javascript form controller:
=============
define(['modules/master/module'], function (module) {
    "use strict";

    module.registerController('DriverFormCtrl', ['$scope', '$modalInstance', '$log', 'driver', function ($scope, $modalInstance, $log, driver) {
        $scope.driver = driver;

        $scope.inputCardNumbers = driver.cardNumber;

        $scope.okModal = function(){
            if ($scope.driverForm != undefined && $scope.driverForm.$invalid)
                return;

            // refresh driver cardNumbers
            angular.forEach( $scope.outputCardNumbers, function( value, key ) {
                $scope.driver.cardNumber = [];
                $scope.driver.cardNumber.push('A');
            });

            $modalInstance.close($scope.driver);
        }
        $scope.cancelModal = function(){
            $modalInstance.dismiss('cancel');
        }
    }])
});

HTML code:
=============
...
<section>
            <label class="label">Card number</label>
            <div angular-multi-select
                 input-model="inputCardNumbers"
                 output-model="outputCardNumbers"
                 item-label="<[ number ]>"
                 tick-property="active"
                 selection-mode="single"
                 helper-elements="noall nonone reset nofilter">
            </div>
        </section>
...

**Comment by isteven** [comment]
Hi, 

Well my first question is, are you sure you're using this directive? The latest release is version 4.0.0, not 5.5.4.

**Comment by masalinas** [comment]
Hi,
Yes I'm sure that I'm using your directive;), maybe the version was wrong, now I'm using other lower version: 3.0.0, so I must to reconfigure all the javascript access, etc and also the directive configuration with it:

            <div isteven-multi-select
                 input-model="inputCardNumbers"
                 output-model="outputCardNumbers"
                 button-label="number"
                 item-label="number"
                 tick-property="active"
                 selection-mode="single"
                 helper-elements="noall nonone reset nofilter">
            </div>

Now I show the number description of the driver card with the atribute button-label and also I can recover the result (single mode) with this.outputCardNumbers and not with $scope.outputCardNumbers and I don't know why, the $scope.outputCardNumbers is undefined again

Regards.

**Comment by isteven** [comment]
OK, can you replicate your codes in JsFiddler or Plunker? Surely I can see bigger picture there.

**Comment by masalinas** [comment]
It's so complicated for me because I use requirejs, but I'll try to decompose this part of the problem ...
The problem I think it's that, your component is used for me inside a floating form define like a directive, so this directive has it's one scope, so maybe your component create the outdata in other scope, I don't know.

The strange it's that why your component get correctly the input-data but not the out-data and always is undefined.

Regards.

**Comment by isteven** [comment]
If it's really a scope problem (and indeed quite many people had this problem), you may want to try adding a dot (basically use a child object), such as:

    output-model="output.data"

Then you can loop it like..

    angular.forEach( $scope.output.data, function( val, key ) {
    ....

**Comment by masalinas** [comment]
Sorry for this later response but with the version 3.0.0 outputModel is always undefined ...

**Comment by isteven** [comment]
@masalinas ,

Can you open the directive's JS code and check if it's version 4.0.0 or 3.0.0? The latest should be v4.0.0. 

If you're not sure, download the latest from Github's releases page; https://github.com/isteven/angular-multi-select/releases

If it still doesn't work then unfortunately I'll need you to replicate the problem in Plunker or JsFiddler.
