### ISSUE TITLE
Lateral button near multiselect

### ISSUE THREAD

**Issue by masalinas** [isteven/angular-multi-select#371]
How can add a lateral button on the right of the angular-multiselect component??

**Comment by isteven** [comment]
Hi,

What kind of lateral button? Can you show an example? And for what purpose?

**Comment by masalinas** [comment]
Hi,
  my question is because I would like to add entities in the datasource bound to the multiselect component (it's inside a form), so I thought add a button on the right of the component change the your component with a textbox and show two new buttons on the right to validate or cancel the textbox data and if validate add the new entity in the datatsource and refresh the multiselect and show this new entity. I hope you understand my problem, do you have other idea to resolve this necessity?, di you suggest other way??

Regards.

**Comment by isteven** [comment]
Hi @masalinas , 

Unfortunately I don't really understand the case here. 

If it's a button next to the directive's dropdown button, you can just use normal HTML & CSS to do it, and use ng-click on those buttons to validate (or whatever data operation you want).

If you mean a button inside the directive's popup (next to select all, none, reset etc), then you'll need to modify the directive code yourself.
