### ISSUE TITLE
Is there a way to change the button-label when select All?

### ISSUE THREAD

**Issue by BuKinoshita** [isteven/angular-multi-select#372]
I have a `button-label` (button-label="icon name") and what I want to do is when I select all, change the button-label.

I have an array of provinces, when I select all it's showing all my provinces like this:
```
[ name, name, name, name (n) ]
```

Instead of showing this, I want to show `All`.

What I tried to do was, I set a expression on the button-label and then `on-select-all="fSelectAll()"`

```
$scope.fSelectAll = function() {
    $scope.nice = 'All';
}
```

**Comment by isteven** [comment]
Hi @BuKinoshita , 

Unfortunately as for now it is not possible to modify the button-label like that, unless you modify the code internally.

**Comment by BuKinoshita** [comment]
Thanks @isteven !
