### ISSUE TITLE
Allow overrides of helper default behavior

### ISSUE THREAD

**Issue by atavakoli** [isteven/angular-multi-select#373]
I'm requesting a new feature to make the helper default behavior overridable with custom functions or callbacks.

For example, my "Select All" may need additional logic to exclude certain elements from being selected, or I may need to implement a custom "Reset" logic that depends on the current application/input-model state.

**Comment by isteven** [comment]
Hi @atavakoli, 

I understand your point of view, however, this is a very specific request - and unfortunately not really a priority, at least as for now.

Actually, If you only want to disable some items; you can use "disable-property". Read more here http://isteven.github.io/angular-multi-select/#/configs-options

**Comment by atavakoli** [comment]
Thanks @isteven. My motivating use-case was to have a "Reverse" (or "Invert") helper, that just inverts the current selection (i.e. selected become unselected & vice versa). I was hoping to rename/repurpose the "Reset" button for this functionality, but I can also do it outside of the directive too.

Is the feature above (an optional "Invert Selection" helper) something you'd consider including? If so, I'd be glad to submit the PR.

**Comment by isteven** [comment]
@atavakoli , 

Unfortunately there's no plan to include such feature, because I believe it is very specific. Not sure most of the userbase will benefit from it.
