### ISSUE TITLE
caret in button is appended to last buttonLabel

### ISSUE THREAD

**Issue by bolemeus** [isteven/angular-multi-select#378]
It seems the caret on the main button is being appended to the last buttonLabel.

I analysed the code a bit and I beleive that this piece of code is the culprit (line 539):

```
angular.forEach( $scope.inputModel, function( value, key ) {
    if ( typeof value !== 'undefined' && value[ attrs.tickProperty ] === true ) {                        
        if ( ctr < tempMaxLabels ) {                            
            $scope.varButtonLabel += ( $scope.varButtonLabel.length > 0 ? '</div><div class="buttonLabel">' : '<div class="buttonLabel">') + $scope.writeLabel( value, 'buttonLabel' );
        }
        ctr++;
    }
});      
```

I fixed it in your library by adding the following directly after the forEach loop...

```
if ( ctr > 0 ) {
    $scope.varButtonLabel += '</div>';
}          
```

I've already modified too much in the library file again, because I want to give it a bootstrap appearance, and so far the only way I figure I can accomplish this is modifying the template in the js file. That's why I can't really make a PR.

**Comment by isteven** [comment]
@bolemeus , 

Noted with thanks. Will check again later, quite occupied at the moment.
