### ISSUE TITLE
Dropdown not closing when opening normal select

### ISSUE THREAD

**Issue by timojuonoja** [isteven/angular-multi-select#381]
When you open isteven dropdown and after that open normal select, the isteven will remain open at least on webkit based browsers. On firefox it seems to work.

Here is 
https://plnkr.co/edit/4GpVyQsvILmwgTfwb2El?p=preview

**Comment by miguelfrias** [comment]
According to the documentation: http://isteven.github.io/angular-multi-select/#/configs-options

selection-mode: Single or multiple selection. If not specified, the default will be "multiple".

So the behavior it's expected.

**Comment by timojuonoja** [comment]
I guess you didn't understand the issue. It has nothing to do with selection-mode and by using 'single' or 'multiple', the issue remains.

So please try the plnkr example with webkit browser (for example Chromium/Chrome). Open the iSteven dropdown and keep it open and then open the normal <select>. They will both show the options at the same time and that is the issue. The expected result should be that iSteven closes the dropdown, when normal <select> shows its own dropdown.

I added one more <select> to plnkr so that you can demonstrate yourself also how focusing on "select <--> select" works compared to "isteven <--> select".

https://plnkr.co/edit/rDZqB1R9Jgemn7s8zxx6?p=preview

**Comment by isteven** [comment]
@timojuonoja 

I tried on both Firefox and Chrome, both works.. FYI my Chrome is version 47.0.2526.106

**Comment by timojuonoja** [comment]
![issue-381](https://cloud.githubusercontent.com/assets/7699788/12237384/14cdd3a0-b887-11e5-8fa4-03e66e48cabf.png)

I have exactly the same version of Chrome and here is a screenshot when I have first opened iSteven and afterwards open normal select.

**Comment by isteven** [comment]
This baffles me.. I tried both your Plunkers, and both work on Chrome and FF.

**Comment by timojuonoja** [comment]
Ok, thanks for testing. I tested also now on Windows with Chrome and it seems to work there. So this is apparently OS related thing and we have experienced this problem on iPad at least. And I verified the problem on my Linux machine and Chrome, where it behaves exactly the same way. That is why I thought that it is reproducible always, which was my fault.

I can get it working so that handling the clicks outside the multi select will listen 'mousedown' event instead of 'click'. The only side effect naturally is that it closes immediately when mouse is clicked down.

**Comment by isteven** [comment]
I see.. admitedly I didn't have access to Linux machine. Did some testing on iPad, but I didn't remember much - it was quite some months back.

I'll be closing this issue then. Let me know if you need to keep this opened.

**Comment by timojuonoja** [comment]
I'm a little confused. You marked the issue report as closed even though the issue is still present and valid.

**Comment by isteven** [comment]
@timojuonoja ,

Oh, I closed the issue because I thought you already had a solution (albeit with a compromise)?

**Comment by timojuonoja** [comment]
Yes, I have workaround, but that means that I have to fork iSteven component and modify the sources.

**Comment by isteven** [comment]
I thought that's the concept of open source software? You can grab a copy of the code and customize things as you need.

**Comment by timojuonoja** [comment]
Ok, I will fork it then.
