### ISSUE TITLE
Error: [$compile:nonassign] Expression 'undefined' used with directive 'istevenMultiSelect' is non-assignable!

### ISSUE THREAD

**Issue by kevincaradant** [isteven/angular-multi-select#383]
Hi i get this but i don't know why , any idea ? thank you  :)

Error: [$compile:nonassign] Expression 'undefined' used with directive 'istevenMultiSelect' is non-assignable!
http://errors.angularjs.org/1.3.15/$compile/nonassign?p0=undefined&p1=istevenMultiSelect
    at angular.js:63
    at parentSet (angular.js:7700)
    at parentValueWatch (angular.js:7713)
    at Object.regularInterceptedExpression (angular.js:12911)
    at Scope.$digest (angular.js:14300)
    at Scope.$apply (angular.js:14571)
    at bootstrapApply (angular.js:1455)
    at Object.invoke (angular.js:4203)
    at doBootstrap (angular.js:1453)
    at bootstrap (angular.js:1473)

my bower.json

 "dependencies": {
    "afkl-lazy-image": "0.1.4",
    "angular-bootstrap": "0.12.1",
    "angular-busy": "4.1.3",
    "angular-loading-bar": "0.8.0",
    "angular-mocks": "1.3.15",
    "angular-translate": "2.7.2",
    "angular-ui-router": "0.2.15",
    "font-awesome": "4.3.0",
    "less": "2.5.0",
    "angular-notify": "2.5.0",
    "angular-sanitize": "1.4.2"
  },
  "resolutions": {
    "angular": "1.4.3"
  }

**Comment by isteven** [comment]
@kevincaradant , 

Can please replicate the problem in a Plunker or JsFiddler? That'll help in debugging.

**Comment by kevincaradant** [comment]
OK i found my problem , a plunker was not usefull in this case, my problem come from the version of angular that i had in my bower.json. In my case, i selected angular V1.3 or something like that , now the version of angular is 1.4.2 and it's perfect ;)
