### ISSUE TITLE
Dynamic updating of input-model doesn't update output-model

### ISSUE THREAD

**Issue by anthonyresq** [isteven/angular-multi-select#385]
Setting the ticked status of an item in the input-model immediately updates the multi-select, but the output-model is not updated. running the process for a second time updates the output-model with the previous update's value

http://plnkr.co/edit/uJprKzalzFLOhZ1OzprU?p=info

**Comment by isteven** [comment]
Hi @anthonyresq , 

This is a problem faced by many; you can use $timeout like this:

    $timeout( function() {
        angular.forEach($scope.selectedOptions, function (item, key) {
            if (item.selected) {
                $scope.optionOutput = $scope.optionOutput + "-" + item.description;
            };
        });
    }, 0);
