### ISSUE TITLE
Fixed width dropdown

### ISSUE THREAD

**Issue by CallMeAnil** [isteven/angular-multi-select#389]
Hi, 
I'm using your plugin in one of my project and it works perfect. Now I need to fix the width of the dropdown how can I do that? 

I've tried setting width for dropdown it is working but the height is increasing.

Any other alternatives?

**Comment by miguelfrias** [comment]
.checkboxLayer.show {
      height: 200px;
     overflow-y: scroll;
}

**Comment by isteven** [comment]
@PassionatePro ,

A bit buggy, but actually there's a config "max-height". Check the manual to find out more.

CSS hack like what @miguelfrias suggested also works. I would personally suggest using max-height instead.
