### ISSUE TITLE
Select All, Select None, works only for filtered results.

### ISSUE THREAD

**Issue by miguelfrias** [isteven/angular-multi-select#390]
Select All, Select None and Reset button, works only for filtered results.

I think that should work on the entire inputModel.

https://plnkr.co/edit/zBfYpI1olLQbfaYZaxAQ?p=preview

Steps to replicate:

1.- Open https://plnkr.co/edit/zBfYpI1olLQbfaYZaxAQ?p=preview
2.- Open the dropdown and select the first three (Albania, Algeria, Argentina)
3.- Search 'united'
4.- Click select all button (filter). 

Notice that just the options displayed in the filter are been select. *Expected:* All options should be selected.

5.- Click select none button (filter). 

Notice that just the options displayed in the filter are been deselect, which means that you still have 3 in the output model. *Expected:* All options should be un-selected.

**Comment by miguelfrias** [comment]
#391 https://github.com/isteven/angular-multi-select/issues/390

**Comment by isteven** [comment]
@miguelfrias , 

This is actually intentional. Since v2.0.0 (https://github.com/isteven/angular-multi-select/releases), the buttons work on filtered results.

**Comment by molerat619** [comment]
Is there a way to disable that behavior and make the buttons always work on all results?
