### ISSUE TITLE
Get output-model just after init input-model

### ISSUE THREAD

**Issue by renotidus** [isteven/angular-multi-select#392]
Hello, 

I have an issue I can't resolve with the component but I think it is possible but I too noob in angular for that.
I have 2 multiselect, the second one depending of the first one.
I init the first one by 
```javascript
$scope.first-input-model = myData;
```
In myData, there is one element ticked.
Just after, I want to init my 2nd multiselect and for that I need the selected element in the first one.
I try :
```javascript
var firstValue = $scope.first-output-model[0].id;
```
but $scope.first-output-model[0] is undefined.
If I add a timeout, it works... But I don't consider that as a good solution.
Is there a way to wait output model is ready just after init the input-model ?

Thanks in advance.
Renaud.

**Comment by isteven** [comment]
@renotidus , 

It would be great if you can replicate your problem in Plunker or JsFiddler. It'll help a lot in debugging.

**Comment by renotidus** [comment]
Here is the Plunker
https://plnkr.co/edit/c9C4Itj4J5Y5jeUxfmX6?p=preview

Nothing appears on the screen. Open the console and look at my comments in the script.js file. You will understand what I said.

**Comment by miguelfrias** [comment]
You can set a watcher:

https://plnkr.co/edit/69b66oQHXZdImuU8mVzO?p=preview

It may not be the best solution, but it works.

**Comment by isteven** [comment]
@renotidus , 

After looking at the plunker; I understand that this is a problem faced by some as well where the output-model doesn't seem to update properly.

The "solution", unfortunately, are like what you & @miguelfrias described - use a $timeout, or $watch.

Another way to generate the output-model is that you can actually loop over the input-model as well, since it's also updated.

**Comment by renotidus** [comment]
@miguelfrias,

Thanks for the solution, it is not the best but it is better than a timeout (for my opinion).
