### ISSUE TITLE
group item click, not selecting group childrens

### ISSUE THREAD

**Issue by PassionatePro** [isteven/angular-multi-select#396]
Hi,
I'm using angular-multi-select plugin and it is working great, however I ran into problems when I tried with grouping.

When I click on group item ideally it should select all the children but it is not working on the very first time afterwards it is working.

P.S: This issue is for all group items.

Demo [plnkr](http://plnkr.co/edit/73MYrs7TFFOOERvjtN6C?p=preview)

**Comment by isteven** [comment]
Hi @PassionatePro , 

I saw your demo. You used "ticked" as your tick-property. This is a simple true or false variable which represents the whether an item is selected or deselected.

Have you provide this "ticked" attribute in your input-model?

**Comment by PassionatePro** [comment]
No I didn't but the same model worked well for multi-select without grouping. Is it necessary to provide ticked attribute in input-model?

**Comment by isteven** [comment]
@PassionatePro , 

Well, I can only say that you need to follow the manual. It's there for a reason.

**Comment by PassionatePro** [comment]
@isteven Thank you so much for your time.
