### ISSUE TITLE
CSS !important attributes

### ISSUE THREAD

**Issue by marksy** [isteven/angular-multi-select#397]
There are a lot of instances in the CSS of the !important attribute which is unnecessary

**Comment by isteven** [comment]
Understood. Unfortunately my CSS skill is not so good and I don't really have time to modify it now.

I assume users can modify the CSS themselves as necessary.

**Comment by marksy** [comment]
Can I modify it and pull request?

**Comment by isteven** [comment]
Thanks, but I'm not sure I can process a pull request into a new release for now. Quite occupied lately.
