### ISSUE TITLE
Multiselect not working at all with angular 1.4.7

### ISSUE THREAD

**Issue by Vortilion** [isteven/angular-multi-select#400]
Hi, 

I am trying to use your multiselect plugin with angular 1.4.7. I tried to use it exactly like your "Minimum" Demo.

excerpts:

```
<div
        isteven-multi-select
        input-model="smsReceivers"
        output-model="outSmsReceivers"
        button-label="name"
        item-label="name"
        ticket-property="selected"
        helper-elements="">
</div>

smsReceivers: {{smsReceivers}}<br>
outSmsReceivers: {{outSmsReceivers}}
```

```
[...]
var app = angular.module( 'sendSms', ['isteven-multi-select'] );
app.controller( 'SendSmsController', function($scope, $log) {
    $scope.smsReceivers = [
        {id: 1, name: "Steven Rogers", selected: false},
        {id: 2, name: "Tony Stark", selected: false},
        {id: 3, name: "Thor Odinsson", selected: false}
    ];

    $scope.outSmsReceivers = [];
[...]
}
```

 the elements from the scope array are being displayed when clicking on the button, BUT:

- I can't select any of them (they get the css class "selected", but aren't highlighted and can't be unselected
- "ticket-property" is being ignored, I can't set elements to being preselected
- "output-model" is being ignored, it stays empty when clicking on elements
- the only thing that happens when clicking on elements is a new attribute in the input-model ("undefined":true)
- when printing the input-model to my view, it shows strange attributes with cryptic values being added to it (e.g. "spc_DqZeF":0,"idx_DqZeF":0)

![multiselect-error](https://cloud.githubusercontent.com/assets/400503/12647652/78e61c06-c5d6-11e5-80df-7722bd2553b4.png)

- After I clicked on every item and close the dropdown, I can't open it anymore and firebug shows me an error on each click on the button:

![multiselect-error2](https://cloud.githubusercontent.com/assets/400503/12647746/0608d6fa-c5d7-11e5-8836-2a982852712a.png)

Hope you can help me :-(

**Comment by isteven** [comment]
@Vortilion , 

Possible to replicate the problem in JsFiddler or Plunker? It will help me a lot in debugging. 

FYI the cryptic values are internal IDs for grouping purpose :) You can safely ignore them.

**Comment by Vortilion** [comment]
Hi isteven,

thanks for your fast response!

Actually I could reproduce it:
https://plnkr.co/edit/tLCAGy2StH8j7N9O5pH5?p=preview

**Comment by isteven** [comment]
@Vortilion , 

Try to use "tick-property" instead of "ticket-property".

**Comment by Vortilion** [comment]
OMG

I am so embarrased right now. Really. I am so sorry for not seing that and wasting your time because of my stupidity. Jeez... Thanks so much for finding my mistake! Great support, thank you!

**Comment by Vortilion** [comment]
But, to help you in return: You forgot a comma in your Documentation, under "translation", next to "Undo all". :-D

**Comment by isteven** [comment]
Glad can help.. thanks for noticing. Yeah the documentation need update.
