### ISSUE TITLE
No way to close box

### ISSUE THREAD

**Issue by Sellitecture** [isteven/angular-multi-select#402]
There is no intuitive way to close the box.  You have to know to click off of it.   Is there a helper close button?

**Comment by isteven** [comment]
@Sellitecture , 

Unfortunately there's no close button. You'll need to create it yourself if you really need it.

The directive try to follow HTML's select element spec as close as possible. In the case of single selection mode, it's the same with HTML spec.

The only difference is in multi-select mode, where you don't need to hold CTRL (Windows) or Command (Mac OS) to select multiple items. You can close the box by clicking the button again, or clicking outside the element. This, i believe, is pretty much similar with dropdown menus or other multi-select plugins.

**Comment by maa42** [comment]
There seems to be a difference between how this works on IOS devices.   Clicking outside of the dropdown does not close the popup.

**Comment by CrackerakiUA** [comment]
I have same problem, how can we programmatically close the dropdown?
