### ISSUE TITLE
Pefomance issue over 1179 items

### ISSUE THREAD

**Issue by sumeshk** [isteven/angular-multi-select#405]
Hi,

I am having huge performance issue when there is a large number of items in my input model(1179 items to be exact). I had sliced it to only 30 items and it works fine. The page has 3 other multi select as well and they are not impacted(all 3 has less than 20 items each). All 3 of them works fine as well.

Also, the select with large input model, shows only few data when I open it. I assume this is for performance and some kind of pagination. But how do I see the rest as I don't see an auto scroll kind of pagination or any other button for that matter. Of course I can see the rest of the items if I start typing them.

Performance is hit badly that in IE it takes more than 6 seconds for the select to be shown. Also if we start typing something in that select, its getting stuck.

Please let me know if something can be done.

Thanks,
Sumesh

**Comment by isteven** [comment]
@sumeshk , 

Unfortunatley, as for now, there's nothing much I can do. This is a well documented issue, with some users in the past also experiencing slight delay on big data. I also mentioned this on the manual; http://isteven.github.io/angular-multi-select/#/faq

Some suggestions:
- Somehow cut or group the data into smaller chunks 
- Try to use earlier version; such as v1.2.0 or v2.x.x
- Use another multi-select directive. Perhaps the default HTML's multi-select element will work for you?
