### ISSUE TITLE
Label for Dropdown

### ISSUE THREAD

**Issue by sagarwasule** [isteven/angular-multi-select#407]
Is there any property or feasibility to have a Label for Dropdown ?

**Comment by isteven** [comment]
@sagarwasule , 

Can you explain what kind of label?

**Comment by sagarwasule** [comment]
Generally dropdown are used in forms which have Label followed with the dropdown, in order to utilize less space I'm looking to have Label on the dropdown itself clicking on which it will open the dropdown. while after selection I will have "max-labels="0"" which will not populate the selected values but will be available in the scope.

**Comment by isteven** [comment]
Try to find the "translation" - "None selected" in the manual. I think it'll do what you want.
