### ISSUE TITLE
Dynamic update for specific item (not position like [0]) 

### ISSUE THREAD

**Issue by transbetacism** [isteven/angular-multi-select#408]
I have have two selects (Company and Currency). The Company returns something like this:

`[{'companyName': 'Acme Co','defaultCurrency': 'USD'}{'companyName': 'Another Company','defaultCurrency': 'EUR']`

**I want to update the selected item in the Currency select whenever a Company is selected.**

So if "Acme Co" is selected in the first dropdown, it should automatically update the Currency dropdown based on the defaultCurrency (without knowing which position USD has in the Currency dropdown - so i can't use [1]).

**Is this possible? I would appreciate any help :)**

**Comment by isteven** [comment]
@transbetacism , 

Yes, you can define a callback when you click something. Trigger a callback when you click a company. In the callback function, populate the currency data.

**Comment by transbetacism** [comment]
Ok great. But how do I target a specific currency in the currency dropdown. I looked at the Dynamic Update specification and all I see there is the ability to target a position, like this:

`$scope.currency[0].ticked = true;`

Can I use anything else other than the position [0], [1] etc?

**Comment by isteven** [comment]
Unfortunately no, you need to find the value you want to update in the currency dropdown manually - as in comparing the value & getting the index.

**Comment by transbetacism** [comment]
Ok thanks, I'll do that! 

One more question. Even if I set it like this:
`$scope.currency[0].ticked = true;`

I can see that the ticket is in fact updated to true by logging it to the console, but the item is not selected in the select button (single select) - it still says Not selected. How do I fix that?

**Comment by isteven** [comment]
@transbetacism , 

Sorry for the late reply, I missed this one. Have you found a solution for that?

**Comment by transbetacism** [comment]
Yes, I solved it by setting the tick-property to selected on the second dropdown:

`<div
  isteven-multi-select
  class="isteven-multi-select"
  ng-class="{currencyautoselectedflash: startCurrencyautoselectedflash}"
  input-model="currencies"
  output-model="currenciesOutput"
  button-label="currencyCode"
  item-label="currencyCode"
  tick-property="selected"        <-----------
  selection-mode="single"
  helper-elements="filter">
</div>`

And I added this to the function that triggers after the first dropdown has been selected:

`$scope.currencies[i].selected = true;`
