### ISSUE TITLE
How to validate using ng-required="required" validation?

### ISSUE THREAD

**Issue by mlicht** [isteven/angular-multi-select#409]
I'm trying to implement validation using ng-required and am looking for some direction on a basic working example.  Simply adding ng-required="required" does nothing.

Sample here:
http://plnkr.co/edit/YOlzjtEXOseugxkyonWS?p=preview

**Comment by isteven** [comment]
@mlicht , 

Indeed, this directive does not support ng-required. AngularJS provided ng-required only on built-in HTML inputs.

As for now you'll need to validate things manually.
