### ISSUE TITLE
Can the display of input list be made scrollable?

### ISSUE THREAD

**Issue by fortesl** [isteven/angular-multi-select#413]
I cannot find an option to make the list scroll-able. is there an existing option or is it being considered on a future release?

Thanks,
Luis.

**Comment by isteven** [comment]
@fortesl

Have a look at "max-width" property in the config manual. 

It will add "style: width: xxx" in the multiple selection dropdown element.

**Comment by JihadMotii-REISys** [comment]
I don't think there is a max-width option as of yet, right ?

**Comment by isteven** [comment]
Apology, it should be max-height instead. 

@JihadMotii-REISys 
Thank you for noticing & informing us.

**Comment by fortesl** [comment]
The max-height property worked exactly as needed. Thank you!
