### ISSUE TITLE
Does This Tool Allow For Menu Population Via REST Service?

### ISSUE THREAD

**Issue by bigkype** [isteven/angular-multi-select#416]
Haven't seen any documentation on this, so I am wondering if it's even possible to do...

**Comment by isteven** [comment]
@bigkype , 

Yeah you can. Let's say your data input is $scope.employee. First, set it to empty array, such as

    $scope.employee = [];

Then do your REST call as usual, and assign the returned data into $scope.employee

    doRESTCall()...
    .success( data ) {
        $scope.employee = angular.copy( data )
    });

**Comment by bigkype** [comment]
Wish there was a working example available, but ok, I thank you...
