### ISSUE TITLE
Not displaying the label with special characters

### ISSUE THREAD

**Issue by atais** [isteven/angular-multi-select#418]
Hello.

So basically the items I need to select have one strange option of `<default>` and I noticed that the directive can not handle this type of label properly.

Reproduced here: https://plnkr.co/edit/st1yLh?p=preview

**Comment by isteven** [comment]
Hi @atais, 

Most likely because it's processed as HTML tag.

One solution is to modify the property and add a space inside, like <code>< someName ></code>. You can do it real time, the directive will then just update accordingly.

**Comment by atais** [comment]
There is no way to actually escape the HTML :(? It is quite a big difference for me.

**Comment by isteven** [comment]
I understand, but unfortunately nothing that I know of.

**Comment by atais** [comment]
Well then, its a feature ;-) You can close the issue if you like.

**Comment by suyalcinkaya** [comment]
+1
