### ISSUE TITLE
UI labels does not update on update of translation variable.

### ISSUE THREAD

**Issue by bjdash** [isteven/angular-multi-select#421]
I have language defined as below and it works as expected.
$scope.localLang = {
    selectAll       : "Tick all",
    selectNone      : "Tick none",
    reset           : "Undo all"
    search          : "Type here to search...",
    nothingSelected : "Nothing is selected"
}

But when I change/update $scope.localLang the UI doesn't reflect the same. Shouldn't it update the labels to serve the purpose of angular?

**Comment by FrogDevelopper** [comment]
not yet supported :'(
[Runtime translation change](https://github.com/isteven/angular-multi-select/issues/353)

**Comment by yeshwanthalampalli** [comment]
http://stackoverflow.com/questions/39284567/is-there-any-way-to-delay-translation-texts-in-angular-multiselect

Can someone please answer my query in above link
