### ISSUE TITLE
Trigger helper buttons events

### ISSUE THREAD

**Issue by pmomot** [isteven/angular-multi-select#423]
I suggest to add possibility to trigger helper buttons event from directive programmatically, for example clear all selected options after form submit.

For now, to deselect all options, I need to add 'Select None' helper button and trigger 'ng-click' event on it. This is dirty and hacky behaviour.

**Comment by isteven** [comment]
Hi, 

Sorry for the late reply.

The reason for not including so is because AngularJs flexibility with their models.. You can just loop over the <code>input-model</code>, and set the <code>tick-property</code> to true (to select all) or false (to select none)

In the case of the form submission;

```javascript
// Some form submission logic here

// Clear the multi select
angular.forEach( $scope.yourInputData, function( value, key ) {
    value.yourSelectionProperty = false;
});
