### ISSUE TITLE
Assigning Values for Selected Button/Menu Items

### ISSUE THREAD

**Issue by bigkype** [isteven/angular-multi-select#425]
Love this application! One last question, though. I have four of these menus on a page, with the intention of submitting the values of the selected items to a REST service with a POST method. The problem I have is assigning values to the selected items.

Is there any documentation on how this is to be done?

**Comment by isteven** [comment]
@bigkype , 

Can you provide me a sample of your code so I can have a look? You can use JsFiddler or Plunker (or any other JS online collab tool)
