### ISSUE TITLE
In some cases creates new scope and unable to update actual output-model

### ISSUE THREAD

**Issue by wojasso** [isteven/angular-multi-select#426]
I have an app when I use isteven multiselect multiple times on the same form. This is not via ng-include  - this is all in one html file. In some cases using multiselect causes creation of new scope inside and main scope where output-model should be is not updated at all. What more - all inputs with ng-model inside of the same blocks as multiselect (eg. <accordion-group>) uses the same new created scope as multiselect - this is causing actual data from main scope is not displayed at all inside of these block.
Removing output-model property from multiselect removes all the problem and new scope is not created, but multiselect without output-model (without any processed data) seems to make no sense.
I'm wondering about workaround - is there any other way to capture output-model instead of using actual property?
Thank you in advance for any comments - hopefully this will help :)

**Comment by isteven** [comment]
@wojasso , 

Just a quick suggestion you can combine & try:

1. Use child object for the output model, such as.. $scope.data.selectedItems

2. The input model is actually dynamically updated as well, so if you want to, you can loop over the input-model to find the selected items. Say, if your tick-property is "chosenOnes", then

<pre>
    angular.forEach( $scope.inputModelSomethingBlah, function( value, key ) {
        if ( value.chosenOnes == true ) {
                // do your stuff here
        }
    });
</pre>

However, do take note that there are two extra random properties added to the input-model (for display & grouping purposes), so you might want to take only the properties that you need.
