### ISSUE TITLE
Reset all button

### ISSUE THREAD

**Issue by TheWalnut** [isteven/angular-multi-select#427]
I have a table where each column contains a multi-select.  The select filters the table.  When multiple things are being filtered, I want a single button that will reset all.  This means it will uncheck everything and the label will be blank.  I am able to programmatically reset the outputmodel no problem, but this leaves the multi-selects with the labels they had before.  I am not sure how to reach inside of each directive to reset them.

**Comment by isteven** [comment]
@TheWalnut , 

Actually what you need to modify is not the output-model, but the input-model instead. 

Let's say for one multi-select;

- the input-model is <code>$scope.columnData</code>
- the tick-property is <code>isChecked</code>

If you want to de-select everything in a multi-select, you can do it like this:

    angular.forEach( $scope.columnData, function( value, key ) {
        value.isChecked = false;
    });

**Comment by TheWalnut** [comment]
@isteven Thanks so much, that worked perfectly.

**Comment by isteven** [comment]
@TheWalnut , 

Glad to hear that. 

If you're done, kindly help me to close the issue by clicking the close button below. Thanks.
