### ISSUE TITLE
Possible Memory Leaks ?

### ISSUE THREAD

**Issue by vinaynb** [isteven/angular-multi-select#429]
I read about other issues regarding memory leaks but i guess i am facing a new leak. My app has a heavy DOM and hence it causes lots of detached nodes which take up the memory. I am attaching a screenshot of the heap profiler wherein it shows the detached dom node and the retainer tree. I am not able to single out the code in the library that is stopping the reference from getting GC'd.

Specifically its the **element** variable and the **removeFocusSibling** function that are someway still maintaining DOM references.

Also let me know if i need to provide anything else to evaluate this.

![istevenleak](https://cloud.githubusercontent.com/assets/1573465/14350620/22b1cd1e-fce8-11e5-96a9-8bb60adc9019.png)

**Comment by isteven** [comment]
@vinaynb ,

There's a chance indeed that you're facing a new leak, and unfortunately I'm quite occupied to check further. You'll need to work on this yourself.

Some pointers:
- element is the directive's top most parent element. See AngularJs doc for further info.
- removeFocusStyle (NOT removeFocusSibling) is a function to remove css focus style from a previously focused item.

```javascript
$scope.removeFocusStyle = function( tabIndex ) {
    angular.element( formElements[ tabIndex ] ).parent().parent().parent().removeClass( 'multiSelectFocus' );
}
```

**Comment by vinaynb** [comment]
@isteven ok i would dig this further and let you know. Do you have doubts on jQuery causing this ?

**Comment by isteven** [comment]
@vinaynb , 

This library does not require jQuery.
