### ISSUE TITLE
treeview input-model

### ISSUE THREAD

**Issue by hectorcaban** [isteven/angular-multi-select#432]
Is there any way to use a hierarchal model for input-model ?

**Comment by isteven** [comment]
Hierarchal model as in.. ? Any example?

**Comment by hectorcaban** [comment]
I want to add the children items to the input-model. eg:
model =[
  {
     name = "opera",
     ticked: false,
     children: [
{
 ...
}
].
   }
]

I like to put a treeview control on the dropdown

**Comment by isteven** [comment]
@hectorcaban , 

If you simply want a treeview control , the best way is to add non-breaking space characters in the input-model before you load them into the directive, eg;

First level:
name = "Opera"

Second level:
name = "&nbsp;" + "Opera"

Third level:
name = "&nbsp;&nbsp;" + Opera

And so on.
