### ISSUE TITLE
Search isn't returning results when single letter type (iPad)

### ISSUE THREAD

**Issue by dilipms** [isteven/angular-multi-select#436]
Greetings!

From iPad, when a search is performed within the control by keying in single character, it isn't filtering the options. But when two characters are keyed-in, it performs the filtering and returns results perfectly.

PS. This issue is found in iPad. It works perfectly fine in desktop.

Have you ever come to this issue and do you have a workaround for this?

Kind regards,
Dilip.

**Comment by isteven** [comment]
@dilipms ,

Unfortunately I don't have access to iPad (or any other iOS nor MacOS device). As for now I won't be able to tell you why it happens. 

Regards,
Steven

**Comment by me7me7** [comment]
Another similar notice: when testing the demo by searching with just a single character 'g', it returns all items - while it should only match 'google chrome'
