### ISSUE TITLE
Add qa-ids

### ISSUE THREAD

**Issue by LoredanaRadu** [isteven/angular-multi-select#439]
Hello,

I want to know how can I access the dropdownlist from isteven multiselect and the Search input to be able to add ids for QA team for automated tests.

For example, I want to be able to add an id for the input (Search) from isteven and I've tried in javascript something like  var id = document.querySelector(".invest .multiSelect .inputFilter");
                  id.setAttribute("qa-id",  "id"); but it doesn't appear, so how can I access this input? and the dropdown with options, too? which are the classes that I have to use in my querySelector?

Thank you.

**Comment by isteven** [comment]
Unfortunately I'm not really knowledgeable in testing itself.. I can only say that, from what I see, your css selector seems correct.
