### ISSUE TITLE
Highlighting search field in all available results

### ISSUE THREAD

**Issue by aboursier** [isteven/angular-multi-select#440]
Hi,

As a multi-select component, the search feature could also provide in addition to the auto-completion the results with the 'bold' style, highlighting the search criteria in the list of available results

It would be a nice feature.

Alex

**Comment by isteven** [comment]
@aboursier , 

Yeah it's been mentioned by other people here, but it will impact the performance. 

This directive is not the best component performance-wise, and I don't want to make that worse :)

**Comment by aboursier** [comment]
Could you give me hints on how to enhance your library "properly" so i can try to do some tests with it ?

Many thanks :)

**Comment by isteven** [comment]
That's going to be a very broad topic.. I'm not sure if I can assist you that way. 

A more reasonable way would be for you to try it yourself and ask again when you experience any specific difficulty.
