### ISSUE TITLE
sort items multiselect for active = true

### ISSUE THREAD

**Issue by alex-oko** [isteven/angular-multi-select#441]
I wonder if there is a way of ordering the internal elements of multiselect, placing on top those who have been selected and to bring them in alphabetical order. ???

**Comment by isteven** [comment]
Hi @alex-oko , 

Unfortunately there's no such feature.

**Comment by molerat619** [comment]
Too bad, I am also looking for this. Can you suggest an approach?

Intuitively I would start sorting my input model array. Using the orderBy filter could be cool, too.

**Comment by arturouce** [comment]
Hi is very simply i customize code and here is the plugin customized

[isteven-multi-select-customized.zip](https://github.com/isteven/angular-multi-select/files/880509/isteven-multi-select-customized.zip)
