### ISSUE TITLE
How to get values from isteven multiselect

### ISSUE THREAD

**Issue by rontornambe** [isteven/angular-multi-select#443]
In the getting started section there is the following code that retrieves the selected values: 

angular.forEach( $scope.outputBrowsers, function( value, key ) {    
    /* do your stuff here */    
});

I am an angular newbie. Where is this code to be placed?

**Comment by isteven** [comment]
Well that's a very broad question, but one example is when - let's say you need to ajax-save a list of selected IDs from the multi-select. 

```javascript
// First we get the list of IDs
var selectedIds = []; 
angular.forEach( $scope.outputBrowsers, function( value, key ) {
    selectedIds.push( value.itemId );
});

// Then do your AJAX post, sending the list of IDs
$http({
  method: 'POST',
  url: '/someUrl',
  data: JSON.stringify( selectedIds );
}) ....

**Comment by rontornambe** [comment]
I really like your directive. Great stuff. Thanks for sharing.

Do I need to handle a close event to retrieve all selected values?

I have a child view that includes your dropdowns, I am having difficulty
executing the controller from within this form. Do you happen to know how
this is accomplished?

TIA,
Ron Tornambe

**Comment by isteven** [comment]
@rontornambe , 

Usually you'd want to retrieve the directive values during AJAX form submission (well, in fact, all the form values).

For the child view thingy, can you replicate in Plunker or JsFiddler so I can have a look?

**Comment by rontornambe** [comment]
It is a little complicated to do a fiddle. Perhaps my test-site
<http://writers-tryst.ron-tornambe.com> will do. We are only interested in
the Enablers view. The angular main controller is in pages.js, which is
accessible from View Source. I have attached the enablers.html which
includes the JS for the child controller. You will need to create an
account, which should only take a minute.

best,
Ron

**Comment by isteven** [comment]
@rontornambe ,

I think I'll need the fiddler / plunker.. it's kinda hard following piece of codes like the one you provided :)

**Comment by rontornambe** [comment]
No worries. I decided on another plugin,
