### ISSUE TITLE
Simple item-label option

### ISSUE THREAD

**Issue by freemind-** [isteven/angular-multi-select#446]
I wonder if I can display the count of selected elements rather than the list of all element properties?

i.e. If I checked 3 elements in the list it will simply display 3 Checked.

Thanks in advance for the answer.
Mathieu

**Comment by isteven** [comment]
Hi @freemind- 

Yes it's available. Please read the details in the manual.

**Comment by freemind-** [comment]
@isteven I read the doc + the code. I only figure out to set the default button label but I dont see how I can display my custom button label onItemClick... Could you please help. Thanks.

**Comment by freemind-** [comment]
@isteven nevermind, max-labels will do the job :)
