### ISSUE TITLE
Reset from controller.

### ISSUE THREAD

**Issue by Zamin12** [isteven/angular-multi-select#453]
Solved 
Add  event in directive:
            $scope.$on('Reset', function () {
                angular.forEach($scope.filteredModel, function (value, key) {
                    if (typeof value[attrs.groupProperty] === 'undefined' && typeof value !== 'undefined' && value[attrs.disableProperty] !== true) {
                        var temp = value[$scope.indexProperty];
                        value[$scope.tickProperty] = $scope.backUp[temp][$scope.tickProperty];
                    }
                });
                $scope.refreshOutputModel();
                $scope.refreshButton();
                $scope.onReset();
            });

Add broadcast in controller: 

$scope.$broadcast('Reset');

**Comment by isteven** [comment]
Usually.. to reset, I'll just create a back up copy of the input-model, and, re-copied them back when needed. 

But yeah if it works, then it works :)
