### ISSUE TITLE
Outputmodel with rootscope

### ISSUE THREAD

**Issue by mhortac** [isteven/angular-multi-select#458]
How can i use outputmodel with $rootScope ? I want to set/get  the outputmodel value from any controller

**Comment by isteven** [comment]
Hi @mhortac ,

By default it will use $scope variable.. A dirty solution is to use the directive's on-change callback to update (copy) the values into a $rootScope variable. Read more about on-change in the manual.

Another (and usually recommended) way to set/get value from another controller is by using factory method.
