### ISSUE TITLE
Multilanguage Search Support or Override Search Results

### ISSUE THREAD

**Issue by jjerrythimothy** [isteven/angular-multi-select#463]
I have a requirement:

Consider there are 3 names:
1. Alfredo
2. Pérez
3. Perez

When I type **Pérez** in the search input box, I need to list down:
2. Pérez
3. Perez
regardless of the language, I need to display something like the above.

OR

If I try to manipulate the search using javascript, I need to know whether there is an ability to override my search results with my result.

Thanks in advance... :)

**Comment by tim-lukacik** [comment]
I'd take a look at the `$scope.updateFilter` function. You could do your required manipulation there.

**Comment by isteven** [comment]
Hi @jjerrythimothy 

This is a valid challenge, and rather useful indeed. However, unfortunately I have no experience nor usage of such international characters. 

Tim is correct, $scope.updateFilter handles the filtering process. You can put some logic to process or "translate" those characters.

Just remember to do so as early as possible (for example, do it BEFORE the $scope.updateFilter is called). This can save some processing power.

**Comment by jjerrythimothy** [comment]
Is there a way to override that function? I mean I have them in bower components and I do not want to edit that. Is there a way to prevent that function from executing and execute my function?
