### ISSUE TITLE
Reset Selected Item

### ISSUE THREAD

**Issue by Sanjaygpatel** [isteven/angular-multi-select#464]
Hi

I can't remove selected item from multi select from any external button click event ?

if i remove input-model for control then automatically selection gone but then i need to reassign list input model. is there any way to only reset value,  not reassign list to input model 

thanks,

**Comment by isteven** [comment]
Hi @Sanjaygpatel , 

I'm not sure you can "reset" like that, but you indeed can update singular value, for example:

Let's say input -model is $scope.data, then you can do: 

$scope.data[ 2 ].name = "Hello!"

The directive should pick it up after closing & re-opening.
