### ISSUE TITLE
How can I add None Selected value to Single Select? 

### ISSUE THREAD

**Issue by vicheanak** [isteven/angular-multi-select#465]
I think the question describes all.

**Comment by isteven** [comment]
Hi @vicheanak , 

Sorry for the late reply. Unfortunately you'll need to modify the code yourself to do this.

**Comment by let-aurn** [comment]
@isteven, why can't this feature be added to this project?

This is just a matter of a line. 

[isteven-multi-select.js#L940](https://github.com/isteven/angular-multi-select/blob/master/isteven-multi-select.js#L940)
