### ISSUE TITLE
Multiple Drop-down 

### ISSUE THREAD

**Issue by Rizwan-Qamar** [isteven/angular-multi-select#467]
I have multiple  drop-downs on a page and i want to implement  limit (Max 3 Selections etc) functionality  using onclick event. Is it possible to get back the selectedModel in event handler  so i can i check how many items are selected  in the drop-down

**Comment by Rizwan-Qamar** [comment]
^ I want to implement limit functionality. (Not required functionality)

**Comment by isteven** [comment]
Hi @Rizwan-Qamar , 

Yes, you can use the on-item-click callback and check the input-model to see how many items are selected.
