### ISSUE TITLE
icons are gone in select list

### ISSUE THREAD

**Issue by duanp0128** [isteven/angular-multi-select#469]
Hi, I had an icon image display error when I used image lazy loading. 
`icon: '<img anx-src="/images/currencies/' + value + '.png" />'`, when I used my custom directive "anx-src" which for image lazy loading, all icon images are not display. 

I want to know whether multi-select support custom directive or image lazy loading? Thx.

**Comment by isteven** [comment]
hi @duanp0128 , 

Unfortunately I never did lazy loading like this, so I'm not sure about this.
