### ISSUE TITLE
Tab Index for items

### ISSUE THREAD

**Issue by mail2gopinath** [isteven/angular-multi-select#470]
Currently I notice the tabIndex for the multiselect it always set to the first item on opening the control. Also I observed the tab index for all the items is set to -1. Suggest me the way to set the tab index to selected item on opening the control.

**Comment by isteven** [comment]
@mail2gopinath , 

Sorry for the late reply. 

In short.. add 1 into that number. 

But you need to take into account these:
- If filter box is ON, the directive will focus to the filter box.
- If filter box is OFF, the directive will focus on the first item.
