### ISSUE TITLE
Slow when using several selects on a page

### ISSUE THREAD

**Issue by Eithcowich** [isteven/angular-multi-select#475]
I have a page which uses close to 10 multi-selects. They are populated from local storage with sometimes 100's of values. The result is that the page takes about 3 seconds to load (no images, just plain html.) 

Anyone else run into this issue? Any idea how to speed it up?

**Comment by isteven** [comment]
@Eithcowich,

Admittedly this is the weakness of this directive. Multiple directives in one page + a lot of data = slow. 

I'm currently occupied with other things in life and won't have time to explore this further, so I can only suggest to arrange the multi-selects into smaller groups across different pages.
