### ISSUE TITLE
Documentation for button-label and item-label should mention that HTML is not escaped

### ISSUE THREAD

**Issue by Dretch** [isteven/angular-multi-select#477]
Its quite handy that HTML can be used in the fields that `button-label` and `item-label` refer to, but if users don't realise that they need to escape the text in these fields then XSS vulnerbilities could be accidentally introduced (I did this myself, in-fact).

IMHO the documentation should mention that HTML should be escaped, or the behaviour should be changed to sanitize by default.

**Comment by isteven** [comment]
@Dretch, 

Sorry for the late reply; I guess you're right, it's a vulnerability.

If security is the utmost concern, I would also suggest you to open the code and include ngSanitize in the directive's module.
