### ISSUE TITLE
problem in multiple dropdown

### ISSUE THREAD

**Issue by amykmishra** [isteven/angular-multi-select#480]
Hi,

I  am using six multiselect on mdbootstrap with angularJs on SPA. Everytime I get the data and bind it successfully to the input-modal. But, the problem I am facing this is, the loaded content doesn't show the selected value, but hen I click on the dropdown or just press a key after focusing a field, the selected value comes. I want the selected value to come without any click or any key press.

HTML:-

<div isteven-multi-select selection-mode="single" on-item-click="fActionUserClick(data)" id="cloneusername" max-labels="1" translation="localActionUserLang"
                             helper-elements="filter" input-model="actionUsers" button-label="name role" max-height="250px"
                             item-label="name role" tick-property="ticked" ng-model="dpclonemodal.user"></div>

any help in this would be very helpful for me. Please suggest any solution.

**Comment by isteven** [comment]
Hi @amykmishra , 

Sorry for the late reply, can you replicate this in Plunker or JsFiddler?

**Comment by amykmishra** [comment]
Hi @isteven It was my bad. the issue resolved.

+1 for plugin.
Thanks
