### ISSUE TITLE
AJAX

### ISSUE THREAD

**Issue by zhiyangLau** [isteven/angular-multi-select#486]
Support Ajax?

**Comment by isteven** [comment]
In a way, yes. It depends on how you use it though.

**Comment by zhiyangLau** [comment]
Can give an example?

**Comment by zhiyangLau** [comment]
@isteven

**Comment by zhiyangLau** [comment]
@isteven 

on-search-change="getKeywords(data)"

But I found that the getkeywords method will be called, I don't know where the problem is.

**Comment by isteven** [comment]
Oh.. unfortunately no, the directive doesn't support such action.

It can only accept AJAX data once during initialization.

**Comment by zhiyangLau** [comment]
@isteven 

But I want to search through the Ajax pulling data, no way to achieve?

**Comment by isteven** [comment]
@zhiyangLau ,

I mean.. you can pull AJAX using that, but there's no way to re-build the input-model data (In short, you'll lose the data you've clicked every time you do AJAX pull).

**Comment by zhiyangLau** [comment]
@isteven Thank you very sorry that this plug-in can not meet my needs

**Comment by isteven** [comment]
@zhiyangLau , 

No problem. This is indeed the limitation of the directive.

**Comment by zhiyangLau** [comment]
@isteven 

Ask you about 

$scope.onSearchChange({ 
                            data: 
                            {
                                keyword: $scope.inputLabel.labelFilter, 
                                result: filterObj 
                            } 
                        });


Where is the onSearchChange method? I now encounter the problem is that many times the non-stop to launch Ajax request if you can continue to use the solution to solve the

**Comment by isteven** [comment]
First, you define the name of the function you want to call everytime you search using the 

```html
on-search-change="yourFunctionHere( data )"
```

Then, in your Js controller file, you define the function

```javascript
$scope.yourFunctionHere = function( data ) {
    // data is an object which contains the keyword you type and the filtered result.
    // do anything you like with the keyword & the filtered result
}

**Comment by andela-oadebayo** [comment]
Hello @isteven am also facing the same issue, will be happy if you can help, here is my code

```
$scope.getAilment = function(data){
        if(data.keyword.length > 3){
            AilmentService.searchAilment(data.keyword).then(function(res){
                $scope.ailments = res.ailments.data
            })
        }
    }
```

But the problem is that the call to the API never stop, it keeps calling the endpoint, any help will be really appreciated.

Thank you.

**Comment by balpreetbrar** [comment]
Hello @isteven  am also facing the same issue,
the problem is that the call to the API never stop, it keeps calling the endpoint, any help will be really appreciated

**Comment by isteven** [comment]
There's indeed a bug, and a hackish work around on this. Please have a look on this 

https://github.com/isteven/angular-multi-select/issues/277
