### ISSUE TITLE
disable cascade drop down 

### ISSUE THREAD

**Issue by fabomac** [isteven/angular-multi-select#493]
Hi! @isteven 

I have two multi-select on cascading. for example, First multi-select shows modern browsers and second one shows color names. I want to disable the color multi-select options list evaluating the modern browser name selected.

$scope.modernBrowsers = [
 	{icon: "[...]/opera.png...",	name: "Opera",maker: "Opera Software",ticked: false}
 	{icon: "[...]/internet_explorer.png...",name: "Internet Explorer",maker: "Microsoft",ticked: false}
 	{icon: "[...]/firefox-icon.png...",	name: "Firefox",maker: "Mozilla Foundation",	ticked: false}
 	{icon: "[...]/safari_browser.png...",name: "Safari",	maker: "Apple",ticked: true}
 	{icon: "[...]/chrome.png...",name: "Chrome",	maker: "Google",ticked: false}
];

This is my code of second multi-select: 

```
<div isteven-multi-select
         input-model="colors"
	output-model="outputColors"
	button-label="colorName"
	item-label="colorName"
	tick-property="ticked"
	selection-mode="single"
	helper-elements="filter"
	translation="localLang"
	is-disabled="outputBrowsers.name != 'Opera'">
</div>

```

but it is not working. Can you help me please.

**Comment by isteven** [comment]
@fabomac , 

Can you help to replicate this issue in Plunker or JsFiddler?
