### ISSUE TITLE
isteven-multi-select.htm  this html 404

### ISSUE THREAD

**Issue by liuzhiqi123** [isteven/angular-multi-select#504]
![wxid_6vfmwrmztv0d22_1487320888522_27](https://cloud.githubusercontent.com/assets/25840356/23058445/f9676f0e-f52f-11e6-958d-12d19c5cf62e.png)

**Comment by isteven** [comment]
I'm not sure what happened here, never found this error before.

**Comment by umair-khan1993** [comment]
I encountered the same problem...were you able to resolve this issue?

**Comment by umair-khan1993** [comment]
I resolved this issue by moving isteven-multi-select.js declaration above the directives declaration in html file

**Comment by isteven** [comment]
I assume there's a good solution on this. Will close the issue now.

**Comment by stl-winniechan** [comment]
I'm still having this problem upgrade to 4.0. I'm using bower install with bower.json script: 
` "angular-multi-select": "4.0.0"`
After update, I have these change in my stack:
```
        modified:   bower_components/angular-multi-select/.bower.json
        modified:   bower_components/angular-multi-select/bower.json
        modified:   bower_components/angular-multi-select/isteven-multi-select.css
        modified:   bower_components/angular-multi-select/isteven-multi-select.js

```
Does it suppose to install the "isteven-multi-select.htm" too?

**Comment by imisweet1** [comment]
Any updates for resolution ?

**Comment by omalyutin** [comment]
Please, check, that when the template is called by url, there is a url without any additional parameters after isteven-multi-select.htm part (you can check it in developer console in Chrome).

Correct:
http://127.0.0.1:8020/yun/oem/isteven-multi-select.htm
Incorrect:
http://127.0.0.1:8020/yun/oem/isteven-multi-select.htm?**token=....**

Check interceptions, usually there some additional parameters are injected (to prevent Browser caching as an example)

Hope my explanation make sense.

p.s. yes, somebody uses AngularJS in 2019 :-)
