### ISSUE TITLE
isteven-multi-select horizontal orientation issue

### ISSUE THREAD

**Issue by MadhuriGurumurthy11** [isteven/angular-multi-select#505]
I am using **ist-even-multi-select**  and it is so good. Currently, my code looks like this 

```javascript
<div isteven-multi-select 
            input-model="allMetros"
             output-model="newArray2"
             button-label="icon name"
             item-label="icon name maker"
             tick-property="ticked"
             orientation="horizontal"
             max-height="500px"
                >
        </div> 
```

But in the display, it looks like 

![multi](https://cloud.githubusercontent.com/assets/21213751/23281933/239283b0-f9ed-11e6-82e5-762ea7fcafed.png)

I wanted a clean orientation, How can I achieve it?

thanks in advance!

**Comment by isteven** [comment]
Hi, 

Sorry for the late reply; unfortunately you'll need to make the names shorter.
