### ISSUE TITLE
iPad - Multi Select Dropdown is not hide when tap outside area

### ISSUE THREAD

**Issue by maksud-appirio** [isteven/angular-multi-select#506]
Hi All,

Multi Select Dropdown is not gonna hide when I tap outside of the screen. Even it is not working when I try the demo page of your site.

http://isteven.github.io/angular-multi-select/#/main
Please try this on ipad, when you click on select dropdown it will appear then click any empty/other area you will find that it is not gonna hide.

Thanks
Maksud

**Comment by isteven** [comment]
@maksud-appirio , 

Sorry for the late reply; I don't have access to iPad. I hope you already managed to find a solution.
