### ISSUE TITLE
reflected in other places

### ISSUE THREAD

**Issue by ajayreddy56** [isteven/angular-multi-select#508]
Hi @isteven ,

i am using this library in multiple locations,when i select the friends in the upper area that friends also showing in the below model where i am using.
i am unable to produce the plunker ,am attaching the screen
![screenshot from 2017-04-17 16 27 25](https://cloud.githubusercontent.com/assets/23055758/25087227/f13bdf52-238a-11e7-9725-c84b2ccc29ac.png)

from the drop down i can select the individuals,from individuals when i select the members ,these members are reflected in other place(where i use this library)

**Comment by isteven** [comment]
Hi, 

You need to provide separate object to both directives, like doing a deep copy of the input-model you are using:

```javascript
var userList1 = [ { name: A, selected: false },  { name: B, selected: false },  { name: C, selected: false } ]
var userList2 = angular.copy( userList1 )
```

Note that you CANNOT use simple variable assignment like <code>var userList2 = userList1</code>, because js objects by default assign by reference.

**Comment by ajayreddy56** [comment]
Hi,

@isteven  i given two different names to directive objects.

**Comment by isteven** [comment]
I see. 

Can you replicate the problem in Plunker or JsFiddler, or any other online JS collaboration tool so I can have a look?

**Comment by ajayreddy56** [comment]
Hi,

@isteven  unable replicate the problem.could you please help me out

**Comment by isteven** [comment]
How can I help you if I cannot see your code to find out where the problem is?

**Comment by ajayreddy56** [comment]
Hi,
you can login into website and observe the bug ,while posting the post and commenting the post.

www.telekha.com

**Comment by isteven** [comment]
Please show me your JS & HTML codes instead either in Plunker or JsFiddler, that's the only way I can check. 

I also clearly stated it here that you need to replicate your problem so at least I can have a look.

https://github.com/isteven/angular-multi-select#bug-reporting

**Comment by ajayreddy56** [comment]
```
$scope.userFriends = [];
  FollowsService.getFriends($scope.loggedInUserId, function(res) {
    $scope.userFriends = res;
    for(var i = 0 ; i < $scope.userFriends.length ; i++) {
      $scope.userFriends[i].icon = '<img src="'+NameConverter.getURL('TELEKHA_PROFILE_THUMBS', $scope.userFriends[i].id)+'" class="img-circle" width="40" height="40" />';
      $scope.userFriends[i].label = $scope.userFriends[i].fullName;
    }
    angular.forEach( $scope.userFriends, function( value, key ) {
      value['ticked'] = false;
    });

  }, function() {});
```

```
  <div class="clearfix m-t-md m-b-md" style="width: 100%" ng-show="shareOptions == 'INDIVIDUAL'">
                                       <div
                                isteven-multi-select
                                input-model="userFriends"
                                output-model="outputUserFriends"
                                button-label="icon fullName"
                                item-label="icon fullName"
                                tick-property="ticked"
                                max-labels="5"
                                max-height="200px"
                                translation="localLang">
                              </div>

                              </div>
```
this is code i am using in two methods.

**Comment by isteven** [comment]
OK, so that's the code for the first multi-select.

Where's the code for the second multi-select?

**Comment by ajayreddy56** [comment]
<select class="m-t custom-select custom-select-sm pull-left" ng-model="$parent.shareOptions" ng-change="loadFriends()">
            <option value="PUBLIC" selected>{{'public'|translate}}</option>
            <option value="FOLLOWERS">{{'followers'|translate}}</option>
            <option value="INDIVIDUAL">{{'individuals'|translate}}</option>
          </select>
          <div class="pull-left m-t" style="width: 100%" ng-show="shareOptions == 'INDIVIDUAL'">
          <div
          isteven-multi-select
          input-model="userFriends"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>

        </div>
      </div>``

  $scope.loadFriends = function() {
    if($scope.shareOptions != 'INDIVIDUAL') {
      return;
    }

    FollowsService.getFriends(loggedInUser.id, function(res) {
      $scope.userFriends = res;
      for(var i = 0 ; i < $scope.userFriends.length ; i++) {
        $scope.userFriends[i].icon = '<img src="'+AWSBucketNameConverter.getAWSURL('TELEKHA_PROFILE_THUMBS', $scope.userFriends[i].id)+'" class="img-circle" width="40" height="40" /> ';
        $scope.userFriends[i].name = $scope.userFriends[i].firstName + ' ' + $scope.userFriends[i].lastName;
      }
    }, function() {});

   setTimeout(function(){
    angular.element(document.querySelectorAll('.multiSelect .reset'))[0].click();
    },50);

  };``

**Comment by ajayreddy56** [comment]
earlier you said ,change the directive name .Ans i given two different names to the input model and as well as output model

**Comment by isteven** [comment]
Hi, 

Your code is not displayed properly; please follow Github markdown syntax requirement to display codes.

![untitled](https://cloud.githubusercontent.com/assets/5432100/25473883/beeb0e70-2b63-11e7-85e3-61570079a711.png)

**Comment by ajayreddy56** [comment]
```
<select class="m-t custom-select custom-select-sm pull-left" ng-model="$parent.shareOptions" ng-change="loadFriends()">
            <option value="PUBLIC" selected>{{'public'|translate}}</option>
            <option value="FOLLOWERS">{{'followers'|translate}}</option>
            <option value="INDIVIDUAL">{{'individuals'|translate}}</option>
          </select>
          <div class="pull-left m-t" style="width: 100%" ng-show="shareOptions == 'INDIVIDUAL'">
          <div
          isteven-multi-select
          input-model="userFriends"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>

        </div>
      </div>
```
```
$scope.loadFriends = function() {
  if($scope.shareOptions != 'INDIVIDUAL') {
    return;
  }

  FollowsService.getFriends(loggedInUser.id, function(res) {
    $scope.userFriends = res;
    for(var i = 0 ; i < $scope.userFriends.length ; i++) {
      $scope.userFriends[i].icon = '<img src="'+AWSBucketNameConverter.getAWSURL('TELEKHA_PROFILE_THUMBS', $scope.userFriends[i].id)+'" class="img-circle" width="40" height="40" /> ';
      $scope.userFriends[i].name = $scope.userFriends[i].firstName + ' ' + $scope.userFriends[i].lastName;
    }
  }, function() {});

 setTimeout(function(){
  angular.element(document.querySelectorAll('.multiSelect .reset'))[0].click();
  },50);

};

```

**Comment by ajayreddy56** [comment]
updated with the rules please check it

**Comment by isteven** [comment]
OK, I still don't know HOW you have 2 multi-selects but only supplying one HTML code.. I'll just make assumption then. 

In short, each multi-select needs to have a unique input-model variable. You cannot use <code>userFriends</code> for all of the multi-select instances.

WRONG:
```javascript
$scope.userFriends = [ {...}, {...}, ... ];
```
```html
 <div
          isteven-multi-select
          input-model="userFriends"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>
 <div
          isteven-multi-select
          input-model="userFriends"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>
```

WRONG:
```javascript
$scope.userFriends1 = [ {...}, {...}, ... ];
$scope.userFriends2 = $scope.userFriends1;
```
```html
 <div
          isteven-multi-select
          input-model="userFriends1"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>

 <div
          isteven-multi-select
          input-model="userFriends2"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>
```

CORRECT::
```javascript
$scope.userFriends1 = [ {...}, {...}, ... ];
$scope.userFriends2 = angular.copy( $scope.userFriends1 );
```
```html
 <div
          isteven-multi-select
          input-model="userFriends1"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>

 <div
          isteven-multi-select
          input-model="userFriends2"
          output-model="$parent.outputUserFriends"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
          translation="localLang">
        </div>
```
If it's still doesn't work, please show the whole JS & HTML files.

**Comment by ajayreddy56** [comment]
userfriends1 coming from one file and userfriends2 coming from other js file ,how can i copy ?

**Comment by isteven** [comment]
This is as far as I can help without the whole JS & HTML file. Please copy the whole JS & HTML file in Plunker or JsFiddler and give me the URL - if you want to.

Please read https://github.com/isteven/angular-multi-select#bug-reporting, point number 3.

**Comment by ajayreddy56** [comment]
added html and js files here  https://plnkr.co/edit/dTolp3cy20dwek9cgMOQ?p=preview

**Comment by isteven** [comment]
How does `itemcontrol.htm`l get loaded in `dashboard.html`? I didn't see any `ng-view` or `ng-include` loading the `itemcontrol.htm`l.

Anyway, from what I see, there might be a scope conflict. 

To be safe, use different objects for the `input-model`, AND the `output-model` (especially because you use `$parent` in the output-model).

Example:

```html
<!-- dashboard.html -->
 <div
          isteven-multi-select
          input-model="userFriendsDashboard"
          output-model="outputUserFriendsDashboard"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
           translation="localLang">
        </div>
```
```html
<!-- itemcontrol.html -->
 <div
          isteven-multi-select
          input-model="userFriendsItemControl"
          output-model="outputUserFriendsItemControl"
          button-label=" icon fullName"
          item-label="icon fullName"
          tick-property="ticked"
          max-labels="5"
          max-height="200px"
           translation="localLang">
        </div>
```

(Adjust the controllers accordingly as well)
