### ISSUE TITLE
Caching model indices (indexProperty)

### ISSUE THREAD

**Issue by compborg** [isteven/angular-multi-select#509]
Hi,

In the [prepareIndex](https://github.com/isteven/angular-multi-select/blob/master/isteven-multi-select.js#L790) function , I assume, the goal is to cache the original indices. However I noticed that the loop is on the `$scope.filteredModel`. Isn't it supposed to be on `$scope.inputModel`?

Thanks,

Bora

**Comment by isteven** [comment]
Hi, 

prepareIndex is not for cache purpose. It's to create it's own internal index to be used together with the grouping functionality.

**Comment by compborg** [comment]
Sorry about the late reply. I have (finally) created a plunker to show an issue which gets fixed by using `$scope.input.model` instead of `$scope.filteredModel` . I haven't seen any side effects for doing so.

I have tried to describe the reproduction scenario in the README.

https://plnkr.co/edit/wjTae2G9fE2huvuToBJM

Thanks,

Bora
