### ISSUE TITLE
isteven-multi-select reset data issue

### ISSUE THREAD

**Issue by usrinivasa** [isteven/angular-multi-select#514]
In my code have nested multi select items.

Each selected item has a another multi-select item like below.
item-1
   item-1-A
      <div><select1/><select2/><select3/>
   item-1-B
     <div><select1/><select2/><select3/>
item-2
  ---------------same as item-1
item-3
     ---------------same as item-1

**issue :** If I select item-1 and item-1-A and selected some data in that, after that if I select item-2 then all the data is refreshed. All items under item-1 also deselected.

**Comment by isteven** [comment]
@usrinivasa , 

Can replicate the problem in Plunker or JsFiddler so I can have a look?
