### ISSUE TITLE
How to maintain data for each row in aggrid when I made Multiselect dropdown in aggrid

### ISSUE THREAD

**Issue by atulmayank23** [isteven/angular-multi-select#517]
I made this multiselect dropdown for a column in aggrid. but the issue is that when i select any value form one of them dropdown, then rest dropdown has been filled same as the first one in the particular column.Please give me appropriate solution. Thanx in advance.

**Comment by isteven** [comment]
Make sure you use different input model object. Do a deep copy, don't copy by reference.

If it doesn't help, I need you to copy your code & replicate the problem in Plunker / JsFiddler.

**Comment by atulmayank23** [comment]
Hi,

Below is the code which i have used.

i have taken json data in arr11.
{
	headerName: "Resource", field: "RESOURCES", width: 350,
	cellRenderer: function (params) {
		if (params.data.FLAG == 'L') {
			return '<span><div><isteven-multi-select input-model="arr11" output-model="data.RESOURCES" button-label="RESOURCENAME" item-label="RESOURCENAME" tick-property="ticked" class="isteven-multi-select" /></div></span>';
		}
	}
}

**Comment by atulmayank23** [comment]
[issue code.txt](https://github.com/isteven/angular-multi-select/files/1018338/issue.code.txt)

**Comment by isteven** [comment]
I need more than that; eg. the controller & view

**Comment by atulmayank23** [comment]
Please find the attached code:

[issue code.txt](https://github.com/isteven/angular-multi-select/files/1018513/issue.code.txt)

**Comment by isteven** [comment]
@atulmayank23 , 

I'm unable to help with chunks of code like that. As I said, please replicate your issue in JsFiddler or Plunker.

**Comment by panchaln0110** [comment]
@atulmayank23  How you have created multi select dropdown in ag-grid?
