### ISSUE TITLE
Page Up Page down issue

### ISSUE THREAD

**Issue by tnarender27** [isteven/angular-multi-select#520]
when we click on PageUp ,it goes to next page but the data is not getting refreshed.

Can anybody help in this issue

**Comment by isteven** [comment]
@tnarender27 , 

The directive doesn't register / interfere with PageUp button. Can you replicate your issue in JsFiddler or Plunker?

**Comment by tnarender27** [comment]
When I click on right arrow button to get the second page records,it is not expected results

Plunker
https://plnkr.co/edit/VRCrazPtgt4wJSAHltLs

**Comment by isteven** [comment]
@tnarender27 , 

I never create <code>page-size</code> attribute & arrow buttons in my directive.
