### ISSUE TITLE
How to call Reset button when data is change through ajax call?

### ISSUE THREAD

**Issue by ShivPandey** [isteven/angular-multi-select#521]
I am using multi-select in a form and want to clear it after submit the form through ajax.

**Comment by isteven** [comment]
During initialization, the directive saves a copy of your original input-model.

What the "Reset" button do is actually, copying back that data into the input-model.

So to replicate that.. you simply do it from the controller. Create a copy of the original input-model, and copy it back when you need it.

**Comment by shivpandey** [comment]
Well i use multiple select in a form. When i submit the form the multiple selected data is clear for next form submition

**Comment by ShivPandey** [comment]
Thanks Now its working 👍

**Comment by isteven** [comment]
Glad that you found a solution. I'll close the issue now.
