### ISSUE TITLE
MouseOver event

### ISSUE THREAD

**Issue by tandvu** [isteven/angular-multi-select#525]
Is there a support for a MouseOver (Hover) an item event?  At the moment, when I move the mouse over an item, it got highlighted.  I would like to write a function when the item got highlighted.

Thank you.

Tom

**Comment by isteven** [comment]
@tandvu , 

Unfortunately there's no such mouseover callback. You'll need to modify the directive yourself.

**Comment by tandvu** [comment]
I'm not good with directive but I would like to give it a try.  Would you be able to point me to where I should start?

Thank you so much.

Tom

**Comment by isteven** [comment]
@tandvu , 

It's just a matter of passing your callback into the directive and then call it during mouseover. For example, you can learn from the directive's <code>on-close</code> callback. 

1. Pass the callback function into the directive
Find this in the top of the directive code: <code>onClose: '&',</code>. So for mouseover, you just add something like.. <code>onMouseover: '&'</code> there.

2. Call it during mouseover
There are few ways to do it; one is to modify the template by adding ng-mouseover, or have a event listener in the <code>link</code> function. Both should work.

I highly suggest you to read a bit on AngularJS directive.
