### ISSUE TITLE
Don't save the values of the input object

### ISSUE THREAD

**Issue by Abdou00** [isteven/angular-multi-select#527]
Hello everyone,
I use this package for the first time, I have a form in which I have a task list and I would like to save the selected tasks in my mongodb database. All this goes well for the selection of tasks, when I validate my form too, but when I check in my mongo document the fields of the spots is empty. Would it have a track ??

My Controller:

       $scope.tasksList = [
        { icon: '<img src="../modules/plannings/client/img/tondeuse.jpg"/>', name: 'Tonte(rustique)', frequence: '1x/mois', ticked: false },
        { icon: '<img src="../modules/plannings/client/img/tondeuse.jpg"/>', name: 'Tonte(medium)', frequence: '3x/mois', ticked: false },
        { icon: '<img src="../modules/plannings/client/img/tondeuse.jpg"/>', name: 'Tonte(prestige)', frequence: '5x/mois', ticked: false },
        { icon: '<img src="../modules/plannings/client/img/brouette.jpg"/>', name: 'Ramassage(feuilles)', frequence: '2x/mois', ticked: false }
        { icon: '<img src="../modules/plannings/client/img/elagage.jpg"/>', name: 'Désherbage(rustique)', frequence: '2x/mois', ticked: false },
        { icon: '<img src="../modules/plannings/client/img/elagage.jpg"/>', name: 'Désherbage(medium)',  frequence: '2x/mois', ticked: false },
        { icon: '<img src="../modules/plannings/client/img/elagage.jpg"/>', name: 'Désherbage(prestige)',  frequence: '2x/mois', ticked: false }
      ];

     var selected = [];
     angular.forEach($scope.outputList, function (value, key) {
       selected.push(value.itemId);
       console.log(value.itemId);
    });

    $scope.localLang = {
      selectAll: 'Tous séléctionné',
      selectNone: 'Déselectionné',
      reset: 'Reset',
      search: 'Chercher',
      nothingSelected: 'Selectionner'
    };

My view:

    <isteven-multi-select input-model="teamsList" output-model="outputList" ng-model="vm.planning.team" name="team" id="team" value="team._id" button-label="  icon name" item-label="icon name" selection-mode="single" translation="localLang" directive-id="team" tick-property="ticked"></isteven-multi-select>

My model:

    'use strict';

    var mongoose = require('mongoose'),
     Schema = mongoose.Schema;

    var PlanningSchema = new Schema({
     name: { type: String, default: '', required: 'Nom requis', trim: true },
     start: { type: Date, default: '', required: 'Date requise' },
     end: { type: Date, default: '', required: 'Date requise' },
     team: { type: String, default: 'Team', required: 'Equipe requise' },
     site: { type: Schema.Types.ObjectId, ref: 'Lot', required: 'Site requise' },
     tasks: { type: Object, default: 'Tâches par défaut', required: 'Tâches requise' },
     created: { type: Date, default: Date.now },
     user: { type: Schema.ObjectId, ref: 'User' }
    }, { collection: 'plannings' });

    module.exports = mongoose.model('Planning', PlanningSchema);

I want to clarify if this may be useful that I have integrated this package into a MEANJS project.
Thank you !!

**Comment by isteven** [comment]
@Abdou00 ,

Your controller & view seem to be correct.

Just make sure you get the selected values when you submit your form. 

I have no experience using Mongo, but common REST method would be like this:

```javascript
// As an example, let's say you want to submit your form as JSON using AJAX / REST API
// This function is called when clicking the form's submit button
var submitForm = function() {

   // We prepare the object nicely
   var dataToSubmit = {
       name  : ....,
       start : ....,
       end   : ....,
       whateverSelection: outputList // this is the output model
       ...
   }

   // Then we POST it as JSON string to process.php
   $http({
      method  : 'POST',
      url     : 'process.php',
      data    : JSON.stringify( dataToSubmit )
   }). success(function(data, status, headers, config) {
        // success callback
   }).error(function(data, status, headers, config) {
        // error callback
   });
}
```
Hope this helps.
