### ISSUE TITLE
output-model needn't be a compulsory attribute

### ISSUE THREAD

**Issue by karancrazy007** [isteven/angular-multi-select#558]
@isteven 
![istevenmultiselect](https://user-images.githubusercontent.com/20480175/41911539-8ee41a72-796a-11e8-9df4-d92629f1fba0.png)

This error shows up when I dont provide a value for output-model, since I do not require it for my application.
Upon checking alternative solutions provided by angular, I came across a solution to make the bind optional. So is there any way I can raise a PR making the same change. I really need this fix for my application.

![angularmsg](https://user-images.githubusercontent.com/20480175/41911693-fce26790-796a-11e8-86a8-019ec4eecbcf.png)

For your reference: https://code.angularjs.org/1.5.9/docs/error/$compile/nonassign?p0=undefined&p1=outputModel&p2=istevenMultiSelect

**Comment by isteven** [comment]
May I know how do you define the multi select component in your view & the data in your controller?

**Comment by tarun1793** [comment]
If `output-model` isn't used for capturing the output you may be able to get past the issue just by defining a `foo` variable?

**Comment by karancrazy007** [comment]
```foo``` variable was all it took. I just an empty value through output-model, should've tried that earlier. Thanks @tarun1793, @isteven

**Comment by isteven** [comment]
Yes, like what others said, you can just specify an empty $scope variable there.

Glad you've found a solution. Please close this issue if your problem is solved. Thanks.

**Comment by karancrazy007** [comment]
```foo``` variable was all it took. I just sent an empty array through output-model, should've tried that earlier. Thanks @tarun1793, @isteven
