### ISSUE TITLE
Scrolling long lists

### ISSUE THREAD

**Issue by markbairlift** [isteven/angular-multi-select#6]
I'm considering using this in a project I'm working on. However some of the lists in my application can be rather long, maybe 100 items or more. I don't see any examples with long lists so I wanted to ask if you supported scrolling once the list of items got to a certain size.

**Comment by onnorh** [comment]
How you set the input control (NOT the drop down width) to be a fixed width?

**Comment by isteven** [comment]
HI @onnorh , 

Can you describe which input? Is it the search box?
