### ISSUE TITLE
Single Select Output Model Uses Previous Value

### ISSUE THREAD

**Issue by Alex-Mann** [isteven/angular-multi-select#68]
When angular-multi-select is in single selection mode and you want to return just the object that gets selected, the value that is sent to the output model lags and uses the previously checked value instead of the one that "just" gets clicked.

**Comment by sambitp** [comment]
is Single Select Output Model Uses Previous Value solved ?

**Comment by isteven** [comment]
Hi @sambitp , 

Unfortunately not yet. Currently very occupied with daily work.
