### ISSUE TITLE
Consider adding a package.json

### ISSUE THREAD

**Issue by aymericbeaumet** [isteven/angular-multi-select#80]
I'm currently using [napa](https://www.npmjs.org/package/napa) to install `angular-multi-select`, but I would love to be able to avoid this step and to directly use NPM.

Can you consider to add a `package.json` and publish the package to NPM?

This would be much more convenient for us (non-Bower users).

Thanks!

**Comment by michaeldjeffrey** [comment]
Did this ever get pushed to npm?

**Comment by aymericbeaumet** [comment]
Nope, but as a fallback you could at least provide its git address to npm.

**Comment by isteven** [comment]
Dang.. I just realized that I added the package.json BUT forgot to push it to NPM. 

Can anyone guide me how to do it?

**Comment by aymericbeaumet** [comment]
You need to create an account on [npm](https://www.npmjs.com/signup). Then `npm publish .` from the root folder of the project (where the `package.json` resides). You'll be asked for your credentials only once.

**Comment by jpetitcolas** [comment]
Any news about npm publication? :)

I still got:
> npm ERR! 404 'isteven-angular-multiselect' is not in the npm registry.

**Comment by isteven** [comment]
Hi all,

Gosh, sorry for the delay! 

https://www.npmjs.com/package/isteven-angular-multiselect
