### ISSUE TITLE
Remove dups form $scope.selectedItems

### ISSUE THREAD

**Issue by polojko** [isteven/angular-multi-select#83]
Hi;
I have to use grouping with multi-select list, and the items in groups aren't exclusive (e.g. item can be listed in more than one group). 
I'd like to remove dups from top button, but also from outputModel, as well...
Is there an obvious/easy way to do that?

Tnx;
- Paja

**Comment by jdeflaux** [comment]
Hi,

I know this ticket was closed, but I had the same requirements, and find a solution.

I want to have an item in multiple groups (countries, and some of them are in different groups of countries)

When you display the items of your dropdown using ```ng-repeat```, you can use a``` track by $index```, which means we track the items by index in the array and not track by reference (which is the default if not specified).

How do we proceed? Shall I create a pull request to solve this issue?
