### ISSUE TITLE
angular-multi-select inside ng-repeat

### ISSUE THREAD

**Issue by 12hys** [isteven/angular-multi-select#88]
I have the multi-select div inside of an ng-repeat and I'm having issues creating a separate scope variable for each mult-select. I know that it's a scope issue because any time I select an option in one multi-select, it changes the selection for _all_ of them. Any advice on how to do this cleanly?

HTML:

```
    <tr ng-repeat="feed in feeds">
        <div multi-select input-model="categories[feed.id]" button-label="name" item-label="name" tick-property="selected"></div>
    </tr>
```

JS:
...

```
function($scope) {
    $scope.categories = {};
    var tempCategories = [];
    Feed.query(function(feeds) {
        Category.query(function(data) {
            data.forEach(function(category){
                tempCategories.push(category);
            });

            feeds.forEach(function(elem) {
                 $scope.categories[ elem.id ] = tempCategories;
           });
            $scope.feeds = feeds;
        });
    });
}
```

**Comment by kevincaradant** [comment]
Any news about this feature , i have the same problem today :/. Thank you :)

**Comment by isteven** [comment]
@kevincaradant ,

Perhaps you can re-create your problem in JsFiddler or Plunker so we can have a look?

**Comment by mhmorales** [comment]
I also have the same problem! I used angular.copy to provide a new input-model but nothing changed.
